#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/BlogWidget/GetCategories.cshtml")]
    public partial class _Views_BlogWidget_GetCategories_cshtml : System.Web.Mvc.WebViewPage<IList<BetterCms.Module.Installation.Models.Blog.CategoryItem>>
    {
        public _Views_BlogWidget_GetCategories_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n");

            
            #line 30 "..\..\Views\BlogWidget\GetCategories.cshtml"
    
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\BlogWidget\GetCategories.cshtml"
      
        var blogCategory = Request.Params["blogCategory"] ?? null;
    
            
            #line default
            #line hidden
WriteLiteral("\n\n   \n    <div");

WriteLiteral(" class=\"submenu\"");

WriteLiteral(">\n        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1475), Tuple.Create("\"", 1495)
            
            #line 36 "..\..\Views\BlogWidget\GetCategories.cshtml"
, Tuple.Create(Tuple.Create("", 1482), Tuple.Create<System.Object, System.Int32>(Request.Path
            
            #line default
            #line hidden
, 1482), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 1496), Tuple.Create("\"", 1553)
            
            #line 36 "..\..\Views\BlogWidget\GetCategories.cshtml"
, Tuple.Create(Tuple.Create("", 1504), Tuple.Create<System.Object, System.Int32>(blogCategory == null ? "submenu-active" : null
            
            #line default
            #line hidden
, 1504), false)
);

WriteLiteral(">All</a>\n");

            
            #line 37 "..\..\Views\BlogWidget\GetCategories.cshtml"
        
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\BlogWidget\GetCategories.cshtml"
         foreach (var category in Model)
        {
            var active = blogCategory != null && blogCategory.ToUpper() == category.Name.ToUpper();

            
            #line default
            #line hidden
WriteLiteral("            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1728), Tuple.Create("\"", 1776)
            
            #line 40 "..\..\Views\BlogWidget\GetCategories.cshtml"
, Tuple.Create(Tuple.Create("", 1735), Tuple.Create<System.Object, System.Int32>(Request.Path
            
            #line default
            #line hidden
, 1735), false)
, Tuple.Create(Tuple.Create("", 1748), Tuple.Create("?blogCategory=", 1748), true)
            
            #line 40 "..\..\Views\BlogWidget\GetCategories.cshtml"
, Tuple.Create(Tuple.Create("", 1762), Tuple.Create<System.Object, System.Int32>(category.Name
            
            #line default
            #line hidden
, 1762), false)
);

WriteAttribute("class", Tuple.Create(" class=\"", 1777), Tuple.Create("\"", 1819)
            
            #line 40 "..\..\Views\BlogWidget\GetCategories.cshtml"
, Tuple.Create(Tuple.Create("", 1785), Tuple.Create<System.Object, System.Int32>(active ? "submenu-active": null
            
            #line default
            #line hidden
, 1785), false)
);

WriteLiteral(">");

            
            #line 40 "..\..\Views\BlogWidget\GetCategories.cshtml"
                                                                                                      Write(category.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\n");

            
            #line 41 "..\..\Views\BlogWidget\GetCategories.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>");

        }
    }
}
#pragma warning restore 1591
