#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/TestWidget.cshtml")]
    public partial class _Views_Widgets_TestWidget_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_TestWidget_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Widgets\TestWidget.cshtml"
 if (Model != null)
{

            
            #line default
            #line hidden
WriteLiteral("    <h2>Widget Name: ");

            
            #line 4 "..\..\Views\Widgets\TestWidget.cshtml"
                Write(Model.Widget.Name);

            
            #line default
            #line hidden
WriteLiteral("</h2>\n");

WriteLiteral("    <h3>Current Page: ");

            
            #line 5 "..\..\Views\Widgets\TestWidget.cshtml"
                 Write(Model.Page.PageUrl);

            
            #line default
            #line hidden
WriteLiteral("</h3>\n");

            
            #line 6 "..\..\Views\Widgets\TestWidget.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <p>Some widget content...</p>\n");

            
            #line 8 "..\..\Views\Widgets\TestWidget.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <p>Widget Preview...</p>\n");

            
            #line 12 "..\..\Views\Widgets\TestWidget.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
