#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Shared\TestLayout.cshtml"
    using BetterCms.Module.Blog.Helpers.Extensions;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Shared\TestLayout.cshtml"
    using BetterCms.Module.Pages.Helpers.Extensions;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Shared\TestLayout.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/TestLayout.cshtml")]
    public partial class _Views_Shared_TestLayout_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderPageViewModel>
    {
        public _Views_Shared_TestLayout_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 6 "..\..\Views\Shared\TestLayout.cshtml"
  
    Layout = "~/Areas/bcms-root/Views/Shared/BaseLayout.cshtml";

            
            #line default
            #line hidden
WriteLiteral("\n");

DefineSection("DoctypeTag", () => {

WriteLiteral("\n    <!DOCTYPE html>\n");

});

WriteLiteral("\n");

DefineSection("HtmlTag", () => {

WriteLiteral("\n<!--[if lte IE 7]><html class=\"ie7\"><![endif]-->  \n<!--[if IE 8]><html class=\"ie" +
"8\"><![endif]-->  \n<!--[if IE 9]><html class=\"ie9\"><![endif]-->  \n<!--[if !IE]><!" +
"--><html><!--<![endif]-->  \n");

});

WriteLiteral("\n");

DefineSection("BodyAttributes", () => {

WriteLiteral("\n    test=1\n");

});

WriteLiteral("\n\n");

DefineSection("Styles", () => {

WriteLiteral("    \n");

WriteLiteral("    ");

            
            #line 29 "..\..\Views\Shared\TestLayout.cshtml"
Write(RenderSection("Styles", false));

            
            #line default
            #line hidden
WriteLiteral("\n");

});

WriteLiteral("    <div>\n");

WriteLiteral("        ");

            
            #line 32 "..\..\Views\Shared\TestLayout.cshtml"
   Write(RenderSection("RegionA", false));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n");

WriteLiteral("    ");

            
            #line 34 "..\..\Views\Shared\TestLayout.cshtml"
Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\n    <div>\n");

WriteLiteral("        ");

            
            #line 36 "..\..\Views\Shared\TestLayout.cshtml"
   Write(RenderSection("RegionB", false));

            
            #line default
            #line hidden
WriteLiteral("\n    </div>\n    ");

        }
    }
}
#pragma warning restore 1591
