#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using BetterCms.Module.VTWebAPI;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Index.cshtml")]
    public partial class _Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"jumbotron\"");

WriteLiteral(">\r\n    <h1>ASP.NET</h1>\r\n    <p");

WriteLiteral(" class=\"lead\"");

WriteLiteral(">ASP.NET is a free web framework for building great Web sites and Web application" +
"s using HTML, CSS, and JavaScript.</p>\r\n    <p><a");

WriteLiteral(" href=\"http://asp.net\"");

WriteLiteral(" class=\"btn btn-primary btn-large\"");

WriteLiteral(">Learn more &raquo;</a></p>\r\n</div>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(@">
        <h2>Getting started</h2>
        <p>ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
        a broad range of clients, including browsers and mobile devices. ASP.NET Web API
        is an ideal platform for building RESTful applications on the .NET Framework.</p>
        <p><a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=301870\"");

WriteLiteral(">Learn more &raquo;</a></p>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n        <h2>Get more libraries</h2>\r\n        <p>NuGet is a free Visual Studio " +
"extension that makes it easy to add, remove, and update libraries and tools in V" +
"isual Studio projects.</p>\r\n        <p><a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=301871\"");

WriteLiteral(">Learn more &raquo;</a></p>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n        <h2>Web Hosting</h2>\r\n        <p>You can easily find a web hosting com" +
"pany that offers the right mix of features and price for your applications.</p>\r" +
"\n        <p><a");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=301872\"");

WriteLiteral(">Learn more &raquo;</a></p>\r\n    </div>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
