#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\accordion.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Widgets\accordion.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/accordion.cshtml")]
    public partial class _Views_Widgets_accordion_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_accordion_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 5 "..\..\Views\Widgets\accordion.cshtml"
  
    ViewBag.Title = "Slider";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script>\r\n    $(document).ready(function () {\r\n        $(\'#accordion div.pane" +
"l div.panel-collapse:first\').addClass(\'in\', changeicon());\r\n\r\n\r\n        $(\'#acco" +
"rdion div.panel div.collapse\').parent().find(\'div.panel-heading span.btn\').html(" +
"\'<span class=\"glyphicon glyphicon-collapse-down\"></span>\');\r\n        $(\'#accordi" +
"on div.panel div.collapse.in \').parent().find(\'div.panel-heading span.btn\').html" +
"(\'<span class=\"glyphicon glyphicon-collapse-up\"></span>\');\r\n        $(\'#accordio" +
"n2 div.panel div.collapse\').parent().find(\'div.panel-heading span.subbtn\').html(" +
"\'<span class=\"glyphicon glyphicon-collapse-down\"></span>\');\r\n\r\n\r\n      function " +
" changeicon () {\r\n            $(\'#accordion div.panel div.panel-collapse:first\')" +
".parent().find(\'div.panel-heading span.btn\').html(\'<span class=\"glyphicon glyphi" +
"con-collapse-up\"></span>\');\r\n        };\r\n\r\n        $(\"#accordion div.panel div.c" +
"ollapse\").on(\"hide.bs.collapse\", function () {\r\n             $(this).parent().fi" +
"nd(\'div.panel-heading span.btn\').html(\'<span class=\"glyphicon glyphicon-collapse" +
"-down\"></span>\');\r\n        });\r\n        $(\"#accordion div.panel div.collapse\").o" +
"n(\"show.bs.collapse\", function () {       \r\n            $(this).parent().find(\'d" +
"iv.panel-heading span.btn\').html(\'<span class=\"glyphicon glyphicon-collapse-up\">" +
"</span>\');\r\n         });\r\n        $(\"#accordion2 div.panel div.collapse\").on(\"hi" +
"de.bs.collapse\", function () {\r\n            $(this).parent().find(\'div.panel-hea" +
"ding span.subbtn\').html(\'<span class=\"glyphicon glyphicon-collapse-down\"></span>" +
"\');\r\n        });\r\n        $(\"#accordion2 div.panel div.collapse\").on(\"show.bs.co" +
"llapse\", function () {          \r\n            $(this).parent().find(\'div.panel-h" +
"eading span.subbtn\').html(\'<span class=\"glyphicon glyphicon-collapse-up\"></span>" +
"\');\r\n         });\r\n    });\r\n\r\n</script>\r\n<style>\r\n    a, a:hover, a:focus {\r\n   " +
"     text-decoration: none !important;\r\n        color: black;\r\n    }\r\n\r\n    a {\r" +
"\n        text-decoration: none !important;\r\n        color: black;\r\n    }\r\n</styl" +
"e>\r\n\r\n");

            
            #line 50 "..\..\Views\Widgets\accordion.cshtml"
 if (Model != null && Model.Options != null)
{
    foreach (var option in Model.Options)
    {
        
        string accordiontitle = string.Empty;
        string accordiontext = string.Empty;

        if (@option.Key == "json")
        {
            RenderWidgetViewModel.SliderRootObject robj = null;
            robj = RenderWidgetViewModel.jsSerial.Deserialize<RenderWidgetViewModel.SliderRootObject>(@option.Value);
            if (robj != null)
            {
                if (robj.accordion != null && robj.accordion.Count > 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"panel-group\"");

WriteLiteral(" id=\"accordion\"");

WriteLiteral(">\r\n");

            
            #line 67 "..\..\Views\Widgets\accordion.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 67 "..\..\Views\Widgets\accordion.cshtml"
                         foreach (var obj in robj.accordion)
                        {


            
            #line default
            #line hidden
WriteLiteral("                            <div");

WriteLiteral(" class=\"panel panel-default\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"panel-heading\"");

WriteAttribute("style", Tuple.Create(" style=\"", 3089), Tuple.Create("\"", 3167)
, Tuple.Create(Tuple.Create("", 3097), Tuple.Create("background-color:", 3097), true)
            
            #line 71 "..\..\Views\Widgets\accordion.cshtml"
   , Tuple.Create(Tuple.Create("", 3114), Tuple.Create<System.Object, System.Int32>(robj.acordionbackground
            
            #line default
            #line hidden
, 3114), false)
, Tuple.Create(Tuple.Create("", 3138), Tuple.Create("!important;text-align:center;", 3138), true)
);

WriteLiteral(">\r\n                                    <h4");

WriteLiteral(" class=\"panel-title\"");

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 73 "..\..\Views\Widgets\accordion.cshtml"
                                   Write(Html.Raw(obj.accordiontitle));

            
            #line default
            #line hidden
WriteLiteral("                                       \r\n                                    </h4" +
">\r\n                                </div>                                \r\n");

WriteLiteral("                                ");

            
            #line 76 "..\..\Views\Widgets\accordion.cshtml"
                           Write(Html.Raw(obj.accordiontext));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n");

            
            #line 78 "..\..\Views\Widgets\accordion.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n");

            
            #line 80 "..\..\Views\Widgets\accordion.cshtml"
                }
            }
        }
    }
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
