#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\BasicFooter.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Widgets\BasicFooter.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/BasicFooter.cshtml")]
    public partial class _Views_Widgets_BasicFooter_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_BasicFooter_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/cssStyles.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n \r\n");

            
            #line 8 "..\..\Views\Widgets\BasicFooter.cshtml"
 if (Model != null && Model.Options != null)
{
    string guid = Guid.NewGuid().ToString();
    string objId = "footer" + guid;
    string imgLogoUrl = null;
    string addressText = null, contactText = null;
    string copyrightText = null, imgTopUrl = null, bgcolor=null;
    foreach (var options in Model.Options)
    {
        if (options.Key == "imgLogoUrl")
        {
            imgLogoUrl = options.Value;
        }
        else if (options.Key == "addressText")
        {
            addressText = options.Value;
        }
        else if (options.Key == "contactText")
        {
            contactText = options.Value;
        }
        else if (options.Key == "copyrightText")
        {
            copyrightText = options.Value;
        }
        else if (options.Key == "imgTopUrl")
        {
            imgTopUrl = @options.Value;
        }
        else if (options.Key == "bgcolor")
        {
            bgcolor = @options.Value;
        }
    }






            
            #line default
            #line hidden
WriteLiteral("<div");

WriteAttribute("id", Tuple.Create(" id=\"", 1349), Tuple.Create("\"", 1360)
            
            #line 47 "..\..\Views\Widgets\BasicFooter.cshtml"
, Tuple.Create(Tuple.Create("", 1354), Tuple.Create<System.Object, System.Int32>(objId
            
            #line default
            #line hidden
, 1354), false)
);

WriteLiteral(" class=\"main-content\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" id=\"footertop\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1408), Tuple.Create("\"", 1441)
, Tuple.Create(Tuple.Create("", 1416), Tuple.Create("background-color:", 1416), true)
            
            #line 48 "..\..\Views\Widgets\BasicFooter.cshtml"
, Tuple.Create(Tuple.Create("", 1433), Tuple.Create<System.Object, System.Int32>(bgcolor
            
            #line default
            #line hidden
, 1433), false)
);

WriteLiteral(">\r\n        <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1457), Tuple.Create("\"", 1474)
            
            #line 49 "..\..\Views\Widgets\BasicFooter.cshtml"
, Tuple.Create(Tuple.Create("", 1463), Tuple.Create<System.Object, System.Int32>(imgLogoUrl
            
            #line default
            #line hidden
, 1463), false)
);

WriteLiteral(" style=\"margin:0 auto;\"");

WriteLiteral("/>\r\n        <p");

WriteLiteral(" id=\"\"");

WriteLiteral(">");

            
            #line 50 "..\..\Views\Widgets\BasicFooter.cshtml"
            Write(Html.Raw(@addressText));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n        <p");

WriteLiteral(" id=\"\"");

WriteLiteral(">");

            
            #line 51 "..\..\Views\Widgets\BasicFooter.cshtml"
            Write(Html.Raw(@contactText));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"footerbottom\"");

WriteLiteral(" style=\"text-align:center;\"");

WriteLiteral(">\r\n        \r\n        <span>");

            
            #line 55 "..\..\Views\Widgets\BasicFooter.cshtml"
         Write(Html.Raw(@copyrightText));

            
            #line default
            #line hidden
WriteLiteral(" </span>\r\n        <div");

WriteLiteral(" id=\"uparrow\"");

WriteLiteral(" class=\"dmtop\"");

WriteLiteral(">\r\n            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1779), Tuple.Create("\"", 1795)
            
            #line 57 "..\..\Views\Widgets\BasicFooter.cshtml"
, Tuple.Create(Tuple.Create("", 1785), Tuple.Create<System.Object, System.Int32>(imgTopUrl
            
            #line default
            #line hidden
, 1785), false)
);

WriteLiteral(" style=\"cursor:pointer;\"");

WriteLiteral("/>\r\n        </div>\r\n    </div>\r\n\r\n</div>\r\n");

            
            #line 62 "..\..\Views\Widgets\BasicFooter.cshtml"


            
            #line default
            #line hidden
WriteLiteral(@"    <script>
        (function ($) {
            ""use strict""

            // Back to top
            jQuery(window).scroll(function () {
                if (jQuery(this).scrollTop() > 1) {
                    jQuery('.dmtop').css({ bottom: ""25px"" });
                } else {
                    jQuery('.dmtop').css({ bottom: ""-100px"" });
                }
            });
            jQuery('.dmtop').click(function () {
                jQuery('html, body').animate({ scrollTop: '0px' }, 800);
                return false;
            });

        })(jQuery);
    </script>
");

            
            #line 82 "..\..\Views\Widgets\BasicFooter.cshtml"

}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
