#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Widgets\Contact.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Widgets\Contact.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/Contact.cshtml")]
    public partial class _Views_Widgets_Contact_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_Contact_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/colors.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n");

            
            #line 9 "..\..\Views\Widgets\Contact.cshtml"
 if (Model != null && Model.Options != null)
{
    string guid = Guid.NewGuid().ToString();
    string objId = "contact" + guid;
    string bgImageUrl = null;
    string bgSize = null, leftContent = null;
    string paddingBottom = null, buttonMargin = null, fontcolor = null, buttonCaption = null;
    foreach (var options in Model.Options)
    {
        if (options.Key == "backgroundImage")
        {
            bgImageUrl = options.Value;
        }
        else if (options.Key == "bgSize")
        {
            bgSize = options.Value;
        }
        else if (options.Key == "paddingBottom")
        {
            paddingBottom = options.Value;
        }
        else if (options.Key == "fontcolor")
        {
            fontcolor = options.Value;
        }
        else if (options.Key == "buttonMargin")
        {
            buttonMargin = @options.Value;
        }
        else if (options.Key == "buttonCaption")
        {
            buttonCaption = @options.Value;
        }
        else if (options.Key == "leftContent")
        {
            leftContent = @options.Value;
        }
    }




            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <section");

WriteAttribute("id", Tuple.Create(" id=\"", 1602), Tuple.Create("\"", 1613)
            
            #line 51 "..\..\Views\Widgets\Contact.cshtml"
, Tuple.Create(Tuple.Create("", 1607), Tuple.Create<System.Object, System.Int32>(objId
            
            #line default
            #line hidden
, 1607), false)
);

WriteLiteral(" class=\"section-whitebg\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1638), Tuple.Create("\"", 1727)
, Tuple.Create(Tuple.Create("", 1646), Tuple.Create("background:url(", 1646), true)
            
            #line 51 "..\..\Views\Widgets\Contact.cshtml"
, Tuple.Create(Tuple.Create("", 1661), Tuple.Create<System.Object, System.Int32>(bgImageUrl
            
            #line default
            #line hidden
, 1661), false)
, Tuple.Create(Tuple.Create("", 1672), Tuple.Create(");background-size:", 1672), true)
            
            #line 51 "..\..\Views\Widgets\Contact.cshtml"
                        , Tuple.Create(Tuple.Create("", 1690), Tuple.Create<System.Object, System.Int32>(bgSize
            
            #line default
            #line hidden
, 1690), false)
, Tuple.Create(Tuple.Create("", 1697), Tuple.Create(";padding-bottom:", 1697), true)
            
            #line 51 "..\..\Views\Widgets\Contact.cshtml"
                                               , Tuple.Create(Tuple.Create("", 1713), Tuple.Create<System.Object, System.Int32>(paddingBottom
            
            #line default
            #line hidden
, 1713), false)
);

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-8 col-md-8 col-sm-8 col-xs-12\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1833), Tuple.Create("\"", 1857)
, Tuple.Create(Tuple.Create("", 1841), Tuple.Create("color:", 1841), true)
            
            #line 53 "..\..\Views\Widgets\Contact.cshtml"
, Tuple.Create(Tuple.Create("", 1847), Tuple.Create<System.Object, System.Int32>(fontcolor
            
            #line default
            #line hidden
, 1847), false)
);

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 54 "..\..\Views\Widgets\Contact.cshtml"
               Write(Html.Raw(@leftContent));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-lg-4 col-md-4 col-sm-4 col-xs-12\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1995), Tuple.Create("\"", 2028)
, Tuple.Create(Tuple.Create("", 2003), Tuple.Create("margin-top:", 2003), true)
            
            #line 56 "..\..\Views\Widgets\Contact.cshtml"
    , Tuple.Create(Tuple.Create("", 2014), Tuple.Create<System.Object, System.Int32>(buttonMargin
            
            #line default
            #line hidden
, 2014), false)
, Tuple.Create(Tuple.Create("", 2027), Tuple.Create(";", 2027), true)
);

WriteLiteral(">\r\n                    <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(">");

            
            #line 57 "..\..\Views\Widgets\Contact.cshtml"
                                                   Write(buttonCaption);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </div>\r\n            </div>\r\n        </section>\r\n    </div>\r" +
"\n");

            
            #line 62 "..\..\Views\Widgets\Contact.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
