#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Widgets\ContentWithRightImage.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Widgets\ContentWithRightImage.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/ContentWithRightImage.cshtml")]
    public partial class _Views_Widgets_ContentWithRightImage_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_ContentWithRightImage_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/colors.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/cssStyles.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<!DOCTYPE html>\r\n");

            
            #line 10 "..\..\Views\Widgets\ContentWithRightImage.cshtml"
 if (Model != null && Model.Options != null)
{
    string guid = Guid.NewGuid().ToString();
    string objId = "contentwithRightImage" + guid;
    string img = string.Empty;
    string bgimg = string.Empty;
    string leftPartTxt = string.Empty;
    string leftTxt = string.Empty;
    foreach (var options in Model.Options)
    {
        if (options.Key == "imageurl")
        {
            img = options.Value;
        }
        else if (options.Key == "backgroundimageurl")
        {
            bgimg = options.Value;
        }
        else if (options.Key == "leftparttext")
        {
            leftPartTxt = options.Value;
        }
    }

            
            #line default
            #line hidden
WriteLiteral("    <html>\r\n    <head>\r\n        <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n        <title></title>\r\n    </head>\r\n    <body>\r\n        <div>\r\n           " +
" <section");

WriteAttribute("id", Tuple.Create(" id=\"", 1367), Tuple.Create("\"", 1378)
            
            #line 40 "..\..\Views\Widgets\ContentWithRightImage.cshtml"
, Tuple.Create(Tuple.Create("", 1372), Tuple.Create<System.Object, System.Int32>(objId
            
            #line default
            #line hidden
, 1372), false)
);

WriteLiteral(" class=\"section-whitebg\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1403), Tuple.Create("\"", 1436)
, Tuple.Create(Tuple.Create("", 1411), Tuple.Create("background:url(", 1411), true)
            
            #line 40 "..\..\Views\Widgets\ContentWithRightImage.cshtml"
, Tuple.Create(Tuple.Create(" ", 1426), Tuple.Create<System.Object, System.Int32>(bgimg
            
            #line default
            #line hidden
, 1427), false)
, Tuple.Create(Tuple.Create(" ", 1433), Tuple.Create(");", 1434), true)
);

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-lg-7 col-md-7 col-sm-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"widget clearfix\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"services_lists\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" id=\"ContentWithRightImage_LeftPart\"");

WriteLiteral(">");

            
            #line 45 "..\..\Views\Widgets\ContentWithRightImage.cshtml"
                                                                    Write(Html.Raw(@leftPartTxt));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                            </div><!-- services_lists -->\r\n              " +
"          </div><!-- end widget -->\r\n                    </div><!-- end col-lg-6" +
" -->\r\n                    <div");

WriteLiteral(" class=\"col-lg-5 col-md-5 col-sm-12\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"widget\"");

WriteLiteral(" data-effect=\"slide-left\"");

WriteLiteral(">\r\n                            <img");

WriteLiteral(" style=\"margin-top:115px;\"");

WriteLiteral(" alt=\"\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2119), Tuple.Create("\"", 2129)
            
            #line 51 "..\..\Views\Widgets\ContentWithRightImage.cshtml"
, Tuple.Create(Tuple.Create("", 2125), Tuple.Create<System.Object, System.Int32>(img
            
            #line default
            #line hidden
, 2125), false)
);

WriteLiteral(">\r\n                        </div>\r\n                    </div><!-- end col-lg-6 --" +
">\r\n                </div><!-- end container -->\r\n            </section>\r\n       " +
" </div>\r\n    </body>\r\n</html>\r\n");

            
            #line 59 "..\..\Views\Widgets\ContentWithRightImage.cshtml"
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
