#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\CounterWidget.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Widgets\CounterWidget.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/CounterWidget.cshtml")]
    public partial class _Views_Widgets_CounterWidget_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_CounterWidget_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteAttribute("href", Tuple.Create(" href=\"", 180), Tuple.Create("\"", 217)
, Tuple.Create(Tuple.Create("", 187), Tuple.Create<System.Object, System.Int32>(Href("~/content/font-awesome.min.css")
, 187), false)
);

WriteLiteral(">\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/scripts/waypoints.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/scripts/jquery.counterup.min.js\"");

WriteLiteral(@"></script>
<style>
    .countersection {
        
        background-size: cover;        
        background:fixed;
        width: 100%;
        padding: 100px 0px;
    }
    .count {
        padding: 25px 0px;
        overflow: hidden;
    }
    .count i {
            float: left;
            color: #d14836;
            margin: 5px 0 0 0;
        }
    
    .count .count-numbers {
        float: left;
        overflow: hidden;
        margin: 0 0 0 20px;
    }
    .count .count-numbers h2 {
            color: #fff;
            margin-top: 0px;
            font-weight: 700;
        }
    .count .count-numbers h4 {
            color: #898989;
            font-weight: 700;
        }

</style>
");

            
            #line 43 "..\..\Views\Widgets\CounterWidget.cshtml"
 if (Model != null && Model.Options != null)
{
    string bgimage = string.Empty;
    string bgcolor = string.Empty;
    foreach (var option in Model.Options)
    {

        if (@option.Key == "BackgroundImage")
        {
            bgimage = @option.Value;
        }
        else if (@option.Key == "BackgroundColor")
        {
            bgcolor = @option.Value;
        }
        else if (@option.Key == "Json")
        {

            RenderWidgetViewModel.CounterRootObject robj = null;
            robj = RenderWidgetViewModel.jsSerial.Deserialize<RenderWidgetViewModel.CounterRootObject>(@option.Value);
            if (robj != null)
            {
                if (robj.html != null && robj.html.Count > 0)
                {
                    


            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"countersection\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1930), Tuple.Create("\"", 1996)
, Tuple.Create(Tuple.Create("", 1938), Tuple.Create("background-color:", 1938), true)
            
            #line 69 "..\..\Views\Widgets\CounterWidget.cshtml"
, Tuple.Create(Tuple.Create("", 1955), Tuple.Create<System.Object, System.Int32>(bgcolor
            
            #line default
            #line hidden
, 1955), false)
, Tuple.Create(Tuple.Create("", 1963), Tuple.Create(";", 1963), true)
, Tuple.Create(Tuple.Create(" ", 1964), Tuple.Create("background-image:url(", 1965), true)
            
            #line 69 "..\..\Views\Widgets\CounterWidget.cshtml"
                       , Tuple.Create(Tuple.Create("", 1986), Tuple.Create<System.Object, System.Int32>(bgimage
            
            #line default
            #line hidden
, 1986), false)
, Tuple.Create(Tuple.Create("", 1994), Tuple.Create(");", 1994), true)
);

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 72 "..\..\Views\Widgets\CounterWidget.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 72 "..\..\Views\Widgets\CounterWidget.cshtml"
                                 foreach (var obj in robj.html)
                                {
                                    
            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\Widgets\CounterWidget.cshtml"
                               Write(Html.Raw(obj.text));

            
            #line default
            #line hidden
            
            #line 74 "..\..\Views\Widgets\CounterWidget.cshtml"
                                                       
                                }

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"         </div>\r\n");

            
            #line 80 "..\..\Views\Widgets\CounterWidget.cshtml"
                }
            }
        }
        
            
            #line default
            #line hidden
            
            #line 83 "..\..\Views\Widgets\CounterWidget.cshtml"
                                                                
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n    $(\'.counter\').counterUp();\r\n    \r\n</script>");

        }
    }
}
#pragma warning restore 1591
