#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Widgets\FlexSlider.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Widgets\FlexSlider.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/FlexSlider.cshtml")]
    public partial class _Views_Widgets_FlexSlider_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_FlexSlider_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/colors.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/flexslider.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title></title>\r\n</head>\r\n<body>\r\n    <div>\r\n        <section");

WriteLiteral(" class=\"section-slider\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"flexslider\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"slides\"");

WriteLiteral(">\r\n                    <li>\r\n                        <img");

WriteLiteral(" src=\"/uploads/widgetimage/flexslider_banner1.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"desc\"");

WriteLiteral(">\r\n                            <h2");

WriteLiteral(" class=\"bigtitle\"");

WriteLiteral(">The Best Hospital With All Features You Want</h2>\r\n                            <" +
"span");

WriteLiteral(" class=\"text\"");

WriteLiteral(">Extraordinary People Providing Extraordinary Care</span>\r\n                      " +
"  </div>\r\n                    </li>\r\n                    <li>\r\n                 " +
"       <img");

WriteLiteral(" src=\"/uploads/widgetimage/flexslider_banner2.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"desc\"");

WriteLiteral(">\r\n                            <h2");

WriteLiteral(" class=\"bigtitle\"");

WriteLiteral(">Our Team - a Collaboration of Experts </h2>\r\n                            <span");

WriteLiteral(" class=\"text\"");

WriteLiteral(">A Team of Professionals that you can trust</span>\r\n                        </div" +
">\r\n                    </li>\r\n                    <li>\r\n                        " +
"<img");

WriteLiteral(" src=\"/uploads/widgetimage/flexslider_banner3.png\"");

WriteLiteral(" alt=\"\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"desc\"");

WriteLiteral(">\r\n                            <h2");

WriteLiteral(" class=\"bigtitle\"");

WriteLiteral(">Better Health, Better Care, Better Value</h2>\r\n                            <span" +
"");

WriteLiteral(" class=\"text\"");

WriteLiteral(">A Journey Toward Perfection</span>\r\n                        </div>\r\n            " +
"        </li>\r\n                </ul>\r\n            </div>\r\n            <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.flexslider.js\"");

WriteLiteral("></script>\r\n            <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.js\"");

WriteLiteral("></script>\r\n            <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/bootstrap.js\"");

WriteLiteral("></script>\r\n            <script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/widget/jquery.isotope.min.js\"");

WriteLiteral("></script>\r\n            <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
                $(function () {
                    SyntaxHighlighter.all();
                });
                $(window).load(function () {
                    $('.flexslider').flexslider({
                        animation: ""fade"",
                        controlNav: false,
                        start: function (slider) {
                            $('body').removeClass('loading');
                        }
                    });
                });
            </script>
        </section><!-- end section-slider -->
    </div>
</body>
</html>
");

        }
    }
}
#pragma warning restore 1591
