#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\Marquee.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Widgets\Marquee.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/Marquee.cshtml")]
    public partial class _Views_Widgets_Marquee_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_Marquee_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n\r\n\r\n");

            
            #line 57 "..\..\Views\Widgets\Marquee.cshtml"
 if (Model != null && Model.Options != null)
{
    string guid = Guid.NewGuid().ToString();
    string objDivId = "marquee" + guid;
    RenderWidgetViewModel.MarqueeRootObject robj = null;
    string imgWidth = "200";
    //string compWidth = "100%";

    foreach (var options in Model.Options)
    {
        string bgcolor = string.Empty;
        if (options.Key == "width")
        {

            
            #line default
            #line hidden
WriteLiteral("            <script>\r\n                var width = \'");

            
            #line 71 "..\..\Views\Widgets\Marquee.cshtml"
                        Write(options.Value);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            </script>\r\n");

            
            #line 73 "..\..\Views\Widgets\Marquee.cshtml"
            //compWidth = @options.Value + "px";
        }
        else if (options.Key == "speed")
        {

            
            #line default
            #line hidden
WriteLiteral("            <script>\r\n                var speed = \'");

            
            #line 78 "..\..\Views\Widgets\Marquee.cshtml"
                        Write(options.Value);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            </script>\r\n");

            
            #line 80 "..\..\Views\Widgets\Marquee.cshtml"
        }
        else if (options.Key == "backgroundcolor")
        {

            
            #line default
            #line hidden
WriteLiteral("            <script>\r\n                var bgcolor = \'");

            
            #line 84 "..\..\Views\Widgets\Marquee.cshtml"
                          Write(options.Value);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            </script>\r\n");

            
            #line 86 "..\..\Views\Widgets\Marquee.cshtml"
        }
        else if (options.Key == "imagewidth")
        {
            imgWidth = @options.Value;
        }
        else if (options.Key == "jsonFile")
        {
            robj = RenderWidgetViewModel.jsSerial.Deserialize<RenderWidgetViewModel.MarqueeRootObject>(options.Value);
        }
    }

    

    imgWidth = imgWidth + "px";

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" xclass=\"container\"");

WriteLiteral(" style=\"overflow:hidden; padding-left:0px; padding-right:0px; margin-left:auto; m" +
"argin-right:auto;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"margin:0px;\"");

WriteLiteral(">\r\n            <div");

WriteAttribute("id", Tuple.Create(" id=\"", 3479), Tuple.Create("\"", 3493)
            
            #line 102 "..\..\Views\Widgets\Marquee.cshtml"
, Tuple.Create(Tuple.Create("", 3484), Tuple.Create<System.Object, System.Int32>(objDivId
            
            #line default
            #line hidden
, 3484), false)
);

WriteLiteral(" class=\"marquee\"");

WriteLiteral(">\r\n");

            
            #line 103 "..\..\Views\Widgets\Marquee.cshtml"
                
            
            #line default
            #line hidden
            
            #line 103 "..\..\Views\Widgets\Marquee.cshtml"
                 if (robj != null)
                {
                    if (robj.marquee != null && robj.marquee.Count > 0)
                    {
                        string[] marqueeimages;
                        foreach (var opt in robj.marquee)
                        {
                            marqueeimages = opt.marquee_images.Split(',');
                            for (int i = 0; i < marqueeimages.Length; i++)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4018), Tuple.Create("\"", 4042)
            
            #line 113 "..\..\Views\Widgets\Marquee.cshtml"
, Tuple.Create(Tuple.Create("", 4024), Tuple.Create<System.Object, System.Int32>(marqueeimages[i]
            
            #line default
            #line hidden
, 4024), false)
, Tuple.Create(Tuple.Create("", 4041), Tuple.Create(";", 4041), true)
);

WriteAttribute("style", Tuple.Create(" style=\"", 4043), Tuple.Create("\"", 4100)
, Tuple.Create(Tuple.Create("", 4051), Tuple.Create("width:", 4051), true)
            
            #line 113 "..\..\Views\Widgets\Marquee.cshtml"
, Tuple.Create(Tuple.Create("", 4057), Tuple.Create<System.Object, System.Int32>(imgWidth
            
            #line default
            #line hidden
, 4057), false)
, Tuple.Create(Tuple.Create(" ", 4066), Tuple.Create("!important;", 4067), true)
, Tuple.Create(Tuple.Create(" ", 4078), Tuple.Create("display:inline-block;", 4079), true)
);

WriteLiteral(" />\r\n");

            
            #line 114 "..\..\Views\Widgets\Marquee.cshtml"
                            }
                        }
                    }
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n");

            
            #line 121 "..\..\Views\Widgets\Marquee.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <style>\r\n        .marquee {\r\n            background: #eee;\r\n            overf" +
"low: hidden;\r\n            white-space: nowrap;\r\n        }\r\n    </style>\r\n");

            
            #line 129 "..\..\Views\Widgets\Marquee.cshtml"


            
            #line default
            #line hidden
WriteLiteral("    <script>\r\n\r\n        ");

WriteLiteral("\r\n\r\n        if (typeof width != \'undefined\') {\r\n            var containerWidth = " +
"$(\'#");

            
            #line 138 "..\..\Views\Widgets\Marquee.cshtml"
                                Write(objDivId);

            
            #line default
            #line hidden
WriteLiteral("\').parent().parent().css(\'width\');\r\n            if (width > containerWidth)\r\n    " +
"            width = containerWidth;\r\n            $(\'#");

            
            #line 141 "..\..\Views\Widgets\Marquee.cshtml"
           Write(objDivId);

            
            #line default
            #line hidden
WriteLiteral("\').parent().css(\'width\', width + \'px\');\r\n            $(\'#");

            
            #line 142 "..\..\Views\Widgets\Marquee.cshtml"
           Write(objDivId);

            
            #line default
            #line hidden
WriteLiteral(@"').parent().parent().css('width', width + 'px');
        }
        var speed1 = 50;
        if (typeof speed != 'undefined' && speed > 0)
            speed1 = parseInt(speed);

        if (typeof bgcolor != 'undefined')
            //$('#marquee').css('background-color', bgcolor);
            $('#");

            
            #line 150 "..\..\Views\Widgets\Marquee.cshtml"
           Write(objDivId);

            
            #line default
            #line hidden
WriteLiteral(@"').css('background-color', bgcolor);

        (function () {
            function start_marquee() {
                function go() {
                    i = i < width ? i + step : 1;
                    m.style.marginLeft = -i + 'px';
                }
                var i = 0,
                    step = 3,
                    space = '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;';
                //var m = document.getElementById('marquee');
                var m = document.getElementById('");

            
            #line 162 "..\..\Views\Widgets\Marquee.cshtml"
                                            Write(objDivId);

            
            #line default
            #line hidden
WriteLiteral(@"');
                var t = m.innerHTML; //text
                m.innerHTML = t + space;
                m.style.position = 'absolute'; // http://stackoverflow.com/questions/2057682/determine-pixel-length-of-string-in-javascript-jquery/2057789#2057789
                var width = (m.clientWidth + 1);
                m.style.position = '';
                m.innerHTML = t + space + t + space + t + space + t + space + t + space + t + space + t + space;
                if (m.addEventListener) {
                    m.addEventListener('mouseenter', function () {
                        step = 0;
                    }, false);
                    m.addEventListener('mouseleave', function () {
                        step = 3;
                    }, false);
                }
                var x = setInterval(go, speed1);
            }

            if (window.addEventListener) {
                window.addEventListener('load', start_marquee, false);
            } else if (window.attachEvent) { //IE7-8
                window.attachEvent('onload', start_marquee);
            }
        })();
    </script>
");

            
            #line 187 "..\..\Views\Widgets\Marquee.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n\r\n\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
