#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/MyBasicSliderWidgetTrial.cshtml")]
    public partial class _Views_Widgets_MyBasicSliderWidgetTrial_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_MyBasicSliderWidgetTrial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/cssStyles.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n\r\n");

            
            #line 9 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
 if (Model != null && Model.Options != null)
{
    int count = 0;
    string guid = Guid.NewGuid().ToString();
    string objId = "myCarousel" + guid;
    string imgUrlLeftArrow = null, imgUrlRightArrow = null;
    
    foreach (var options in Model.Options)
    {
        if (options.Key.Contains("sliderimgurl"))
        {
            count++;
        }
        if (options.Key == "imgUrlLeftArrow")
        {
            imgUrlLeftArrow = options.Value;
        }
        else if (options.Key == "imgUrlRightArrow")
        {
            imgUrlRightArrow = options.Value;
        }

    }

    string[] sliderdataimg = new string[count+1];
    string[] sliderdatacaption = new string[count+1];
    string[] sliderdatatext = new string[count+1];
    
    for (int i = 1; i <= count; i++)
    {
        foreach (var options in Model.Options)
        {
            if (options.Key == ("sliderimgurl" + i))
            {
                sliderdataimg[i] = options.Value;
            }
            else if (options.Key == ("slidercaption" + i))
            {
                sliderdatacaption[i] = options.Value;
            }
            else if (options.Key == ("slidersmalltext" + i))
            {
                sliderdatatext[i] = options.Value;
            }
        }
    }


            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <div");

WriteLiteral(" class=\"main-content sliders\"");

WriteLiteral(">\r\n\r\n            <div");

WriteAttribute("id", Tuple.Create(" id=\"", 1740), Tuple.Create("\"", 1751)
            
            #line 59 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
, Tuple.Create(Tuple.Create("", 1745), Tuple.Create<System.Object, System.Int32>(objId
            
            #line default
            #line hidden
, 1745), false)
);

WriteLiteral(" class=\"carousel slide\"");

WriteLiteral(" data-ride=\"carousel\"");

WriteLiteral(">\r\n                <!-- Indicators -->\r\n                <ol");

WriteLiteral(" class=\"carousel-indicators\"");

WriteLiteral(">\r\n                       \r\n");

            
            #line 63 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 63 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
                              
                                for(int j=0;j<count;j++)
                                {
                                    if (j == 0)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li");

WriteLiteral(" data-target=\"#");

            
            #line 68 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
                                                     Write(objId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-slide-to=\"0\"");

WriteLiteral(" class=\"active\"");

WriteLiteral("></li>\r\n");

            
            #line 69 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li");

WriteLiteral(" data-target=\"#");

            
            #line 72 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
                                                     Write(objId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-slide-to=\"");

            
            #line 72 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
                                                                            Write(j);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></li>\r\n");

            
            #line 73 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
                                    }
                                }
                            
            
            #line default
            #line hidden
WriteLiteral("\r\n                        \r\n                </ol>\r\n\r\n                <!-- Wrapper" +
" for slides -->\r\n                <div");

WriteLiteral(" class=\"carousel-inner\"");

WriteLiteral(">\r\n                    \r\n");

            
            #line 82 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 82 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
                      
                        for(int k=1;k<=count;k++)
                        {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 2849), Tuple.Create("\"", 2883)
, Tuple.Create(Tuple.Create("", 2857), Tuple.Create("item", 2857), true)
            
            #line 85 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
, Tuple.Create(Tuple.Create(" ", 2861), Tuple.Create<System.Object, System.Int32>((k==1)?"active":""
            
            #line default
            #line hidden
, 2862), false)
);

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2927), Tuple.Create("\"", 2950)
            
            #line 86 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
, Tuple.Create(Tuple.Create("", 2933), Tuple.Create<System.Object, System.Int32>(sliderdataimg[k]
            
            #line default
            #line hidden
, 2933), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" style=\"width:100%;\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"sliders-overlay-msg\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"sliders-overlay-msg-besthospital slider-caption\"");

WriteLiteral(">\r\n                                            <span>");

            
            #line 89 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
                                             Write(sliderdatacaption[k]);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                        </div>\r\n                        " +
"                <div");

WriteLiteral(" class=\"sliders-overlay-msg-extrappl slider-caption\"");

WriteLiteral(">\r\n                                            <span>");

            
            #line 92 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
                                             Write(sliderdatatext[k]);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                        </div>\r\n                        " +
"            </div>\r\n                                 </div>\r\n");

            
            #line 96 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
                                
                            }
                        
                    
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                                </div>\r\n\r\n                <!-- Left and right" +
" controls -->\r\n                <a");

WriteLiteral(" class=\"left carousel-control\"");

WriteAttribute("style", Tuple.Create(" style=\"", 3848), Tuple.Create("\"", 3907)
, Tuple.Create(Tuple.Create("", 3856), Tuple.Create("background-image:url(\'", 3856), true)
            
            #line 104 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
, Tuple.Create(Tuple.Create("", 3878), Tuple.Create<System.Object, System.Int32>(imgUrlLeftArrow
            
            #line default
            #line hidden
, 3878), false)
, Tuple.Create(Tuple.Create("", 3894), Tuple.Create("\')!important;", 3894), true)
);

WriteAttribute("href", Tuple.Create(" href=\"", 3908), Tuple.Create("\"", 3922)
, Tuple.Create(Tuple.Create("", 3915), Tuple.Create("#", 3915), true)
            
            #line 104 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
                                    , Tuple.Create(Tuple.Create("", 3916), Tuple.Create<System.Object, System.Int32>(objId
            
            #line default
            #line hidden
, 3916), false)
);

WriteLiteral(" data-slide=\"prev\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Previous</span>\r\n                </a>\r\n                <a");

WriteLiteral(" class=\"right carousel-control\"");

WriteAttribute("style", Tuple.Create(" style=\"", 4118), Tuple.Create("\"", 4178)
, Tuple.Create(Tuple.Create("", 4126), Tuple.Create("background-image:url(\'", 4126), true)
            
            #line 108 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
, Tuple.Create(Tuple.Create("", 4148), Tuple.Create<System.Object, System.Int32>(imgUrlRightArrow
            
            #line default
            #line hidden
, 4148), false)
, Tuple.Create(Tuple.Create("", 4165), Tuple.Create("\')!important;", 4165), true)
);

WriteAttribute("href", Tuple.Create(" href=\"", 4179), Tuple.Create("\"", 4193)
, Tuple.Create(Tuple.Create("", 4186), Tuple.Create("#", 4186), true)
            
            #line 108 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"
                                      , Tuple.Create(Tuple.Create("", 4187), Tuple.Create<System.Object, System.Int32>(objId
            
            #line default
            #line hidden
, 4187), false)
);

WriteLiteral(" data-slide=\"next\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Next</span>\r\n                </a>\r\n            </div>\r\n        </div>\r\n    </div" +
">\r\n");

            
            #line 115 "..\..\Views\Widgets\MyBasicSliderWidgetTrial.cshtml"

}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
