#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/MyBasicSliderWidget.cshtml")]
    public partial class _Views_Widgets_MyBasicSliderWidget_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_MyBasicSliderWidget_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/cssStyles.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n\r\n");

            
            #line 8 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
 if (Model != null && Model.Options != null)
{
    string guid = Guid.NewGuid().ToString();
    string objId = "myCarousel" + guid;
    string imgUrlLeftArrow = null, imgUrlRightArrow = null;
    RenderWidgetViewModel.BasicSliderRootObject robj = null;
    foreach (var options in Model.Options)
    {
        if (options.Key == "imgUrlLeftArrow")
        {
            imgUrlLeftArrow = options.Value;
        }
        else if (options.Key == "imgUrlRightArrow")
        {
            imgUrlRightArrow = options.Value;
        }
        else if (options.Key == "jsonFile")
        {
            robj = RenderWidgetViewModel.jsSerial.Deserialize<RenderWidgetViewModel.BasicSliderRootObject>(options.Value);
        }
    }



            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <div");

WriteLiteral(" class=\"main-content sliders\"");

WriteLiteral(">\r\n\r\n            <div");

WriteAttribute("id", Tuple.Create(" id=\"", 1158), Tuple.Create("\"", 1169)
            
            #line 34 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
, Tuple.Create(Tuple.Create("", 1163), Tuple.Create<System.Object, System.Int32>(objId
            
            #line default
            #line hidden
, 1163), false)
);

WriteLiteral(" class=\"carousel slide\"");

WriteLiteral(" data-ride=\"carousel\"");

WriteLiteral(">\r\n                <!-- Indicators -->\r\n                <ol");

WriteLiteral(" class=\"carousel-indicators\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n\r\n                   \r\n");

            
            #line 42 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
                         if (robj != null)
                        {
                            if (robj.sliderdata != null && robj.sliderdata.Count > 0)
                            {
                                int i = 0;
                                foreach (var opt in robj.sliderdata)
                                {
                                    if (i == 0)
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li");

WriteLiteral(" data-target=\"#");

            
            #line 51 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
                                                     Write(objId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-slide-to=\"0\"");

WriteLiteral(" class=\"active\"");

WriteLiteral("></li>\r\n");

            
            #line 52 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
                                        i++;
                                    }
                                    else
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <li");

WriteLiteral(" data-target=\"#");

            
            #line 56 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
                                                     Write(objId);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" data-slide-to=\"");

            
            #line 56 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
                                                                            Write(i);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral("></li>\r\n");

            
            #line 57 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
                                        i++;
                                    }
                                }
                            }
                        }

            
            #line default
            #line hidden
WriteLiteral("                </ol>\r\n\r\n                <!-- Wrapper for slides -->\r\n           " +
"     <div");

WriteLiteral(" class=\"carousel-inner\"");

WriteLiteral(">\r\n                    ");

WriteLiteral("\r\n");

            
            #line 101 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 101 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
                     if (robj != null)
                    {
                        if (robj.sliderdata != null && robj.sliderdata.Count > 0)
                        {
                            int i = 0;
                            foreach (var opt in robj.sliderdata)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteAttribute("class", Tuple.Create(" class=\"", 5039), Tuple.Create("\"", 5073)
, Tuple.Create(Tuple.Create("", 5047), Tuple.Create("item", 5047), true)
            
            #line 108 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
, Tuple.Create(Tuple.Create(" ", 5051), Tuple.Create<System.Object, System.Int32>((i==0)?"active":""
            
            #line default
            #line hidden
, 5052), false)
);

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 5117), Tuple.Create("\"", 5139)
            
            #line 109 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
, Tuple.Create(Tuple.Create("", 5123), Tuple.Create<System.Object, System.Int32>(opt.sliderimage
            
            #line default
            #line hidden
, 5123), false)
);

WriteLiteral(" alt=\"\"");

WriteLiteral(" style=\"width:100%;\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"sliders-overlay-msg\"");

WriteLiteral(">\r\n                                        <div");

WriteLiteral(" class=\"sliders-overlay-msg-besthospital slider-caption\"");

WriteLiteral(">\r\n                                            <span>");

            
            #line 112 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
                                             Write(opt.sliderCaption);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                        </div>\r\n                        " +
"                <div");

WriteLiteral(" class=\"sliders-overlay-msg-extrappl slider-caption\"");

WriteLiteral(">\r\n                                            <span>");

            
            #line 115 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
                                             Write(opt.slidersmalltext);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                        </div>\r\n                        " +
"            </div>\r\n                                 </div>\r\n");

            
            #line 119 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
                                i++;
                            }
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n\r\n                <!-- Left and right c" +
"ontrols -->\r\n                <a");

WriteLiteral(" class=\"left carousel-control\"");

WriteAttribute("style", Tuple.Create(" style=\"", 6041), Tuple.Create("\"", 6100)
, Tuple.Create(Tuple.Create("", 6049), Tuple.Create("background-image:url(\'", 6049), true)
            
            #line 127 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
, Tuple.Create(Tuple.Create("", 6071), Tuple.Create<System.Object, System.Int32>(imgUrlLeftArrow
            
            #line default
            #line hidden
, 6071), false)
, Tuple.Create(Tuple.Create("", 6087), Tuple.Create("\')!important;", 6087), true)
);

WriteAttribute("href", Tuple.Create(" href=\"", 6101), Tuple.Create("\"", 6115)
, Tuple.Create(Tuple.Create("", 6108), Tuple.Create("#", 6108), true)
            
            #line 127 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
                                    , Tuple.Create(Tuple.Create("", 6109), Tuple.Create<System.Object, System.Int32>(objId
            
            #line default
            #line hidden
, 6109), false)
);

WriteLiteral(" data-slide=\"prev\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Previous</span>\r\n                </a>\r\n                <a");

WriteLiteral(" class=\"right carousel-control\"");

WriteAttribute("style", Tuple.Create(" style=\"", 6311), Tuple.Create("\"", 6371)
, Tuple.Create(Tuple.Create("", 6319), Tuple.Create("background-image:url(\'", 6319), true)
            
            #line 131 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
, Tuple.Create(Tuple.Create("", 6341), Tuple.Create<System.Object, System.Int32>(imgUrlRightArrow
            
            #line default
            #line hidden
, 6341), false)
, Tuple.Create(Tuple.Create("", 6358), Tuple.Create("\')!important;", 6358), true)
);

WriteAttribute("href", Tuple.Create(" href=\"", 6372), Tuple.Create("\"", 6386)
, Tuple.Create(Tuple.Create("", 6379), Tuple.Create("#", 6379), true)
            
            #line 131 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"
                                      , Tuple.Create(Tuple.Create("", 6380), Tuple.Create<System.Object, System.Int32>(objId
            
            #line default
            #line hidden
, 6380), false)
);

WriteLiteral(" data-slide=\"next\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Next</span>\r\n                </a>\r\n            </div>\r\n        </div>\r\n    </div" +
">\r\n");

            
            #line 138 "..\..\Views\Widgets\MyBasicSliderWidget.cshtml"

}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
