#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\MyMenuWidget.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Widgets\MyMenuWidget.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/MyMenuWidget.cshtml")]
    public partial class _Views_Widgets_MyMenuWidget_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_MyMenuWidget_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/animate.css\"");

WriteLiteral(">\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/content/styles/bootstrap-dropdown-hover.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/scripts/js/bootstrap-dropdownhover.min.js\"");

WriteLiteral("></script>\r\n\r\n");

            
            #line 11 "..\..\Views\Widgets\MyMenuWidget.cshtml"
 if (Model != null && Model.Options != null)
{
    foreach (var option in Model.Options)
    {
        string menuname = string.Empty;
        string menulogo = string.Empty;
        string text = string.Empty;
        string homeimage = string.Empty;
        string link = string.Empty;
        string subLink = string.Empty;
        string subText = string.Empty;

        string mainbgcolor = string.Empty;
        string menubackcolor = string.Empty;
        string listbackcolor = string.Empty;
        string menubackcoloronhover = string.Empty;

        string bordercolor = string.Empty;

        string textcolorheader = string.Empty;
        string textcolormenu = string.Empty;
        string textcolorsubmenu = string.Empty;

        string animation = string.Empty;
        string navbarstyle = string.Empty;

        string fontfamilyheader = string.Empty;
        string fontfamilymenu = string.Empty;
        string fontfamilysubmenu = string.Empty;

        string fontsizeheader = string.Empty;
        string fontsizemenu = string.Empty;
        string fontsizesubmenu = string.Empty;

        string fontweightheader = string.Empty;
        string fontweightmenu = string.Empty;
        string fontweightsubmenu = string.Empty;

        string lastdividercolor = string.Empty;
        string maindividercolor = string.Empty;
        string listbackcoloronhover = string.Empty;

        string textcolorheaderhover = string.Empty;
        string textcolormenuhover = string.Empty;
        string textcolorsubmenuhover = string.Empty;

        string togglebordercolor = string.Empty;
        string togglebackcolor = string.Empty;
        string togglebackcoloronhover = string.Empty;
        string toggleiconcolor = string.Empty;

        string navbarbrandpaddingtop = string.Empty;
        string navbarbrandpaddingbottom = string.Empty;
        string navbarbrandpaddingleft = string.Empty;
        string navbarbrandpaddingright = string.Empty;

        string navbarpaddingtop = string.Empty;
        string navbarpaddingbottom = string.Empty;
        string navbarpaddingleft = string.Empty;
        string navbarpaddingright = string.Empty;

        string dropdownpaddingtop = string.Empty;
        string dropdownpaddingbottom = string.Empty;
        string dropdownpaddingleft = string.Empty;
        string dropdownpaddingright = string.Empty;

        int count = 0;
        int cnt = 1;
        if (option.Key == "jsonFile")
        {
            RenderWidgetViewModel.MenuRootObject robj = null;
            robj = RenderWidgetViewModel.jsSerial.Deserialize<RenderWidgetViewModel.MenuRootObject>(option.Value);


            foreach (var opt in Model.Options)
            {
                if (opt.Key == "menuname_or_menulogo")
                { menuname = opt.Value; }

                if (opt.Key == "mainBackgroundColor")
                { mainbgcolor = opt.Value; }

                if (opt.Key == "border-color")
                { bordercolor = opt.Value; }

                if (opt.Key == "dataAnimation")
                { animation = opt.Value; }

                if (opt.Key == "menuBackgroundColor")
                { menubackcolor = opt.Value; }

                if (opt.Key == "menubackcoloronhover")
                { menubackcoloronhover = opt.Value; }

                if (opt.Key == "listBackgroundColor")
                { listbackcolor = opt.Value; }

                if (opt.Key == "font-family-header")
                { fontfamilyheader = opt.Value; }

                if (opt.Key == "font-family-menu")
                { fontfamilymenu = opt.Value; }

                if (opt.Key == "font-family-submenu")
                { fontfamilysubmenu = opt.Value; }

                if (opt.Key == "font-size-header")
                { fontsizeheader = opt.Value; }

                if (opt.Key == "font-size-menu")
                { fontsizemenu = opt.Value; }

                if (opt.Key == "font-size-submenu")
                { fontsizesubmenu = opt.Value; }

                if (opt.Key == "font-weight-header")
                { fontweightheader = opt.Value; }

                if (opt.Key == "font-weight-menu")
                { fontweightmenu = opt.Value; }

                if (opt.Key == "font-weight-submenu")
                { fontweightsubmenu = opt.Value; }

                if (opt.Key == "textcolor-header")
                { textcolorheader = opt.Value; }

                if (opt.Key == "textcolor-menu")
                { textcolormenu = opt.Value; }

                if (opt.Key == "text-color-submenu")
                { textcolorsubmenu = opt.Value; }

                if (opt.Key == "textcolor-headerhover")
                { textcolorheaderhover = opt.Value; }

                if (opt.Key == "textcolor-menuhover")
                { textcolormenuhover = opt.Value; }

                if (opt.Key == "textcolor-submenuhover")
                { textcolorsubmenuhover = opt.Value; }

                if (opt.Key == "last-divider-color")
                { lastdividercolor = opt.Value; }

                if (opt.Key == "listbackcoloronhover")
                { listbackcoloronhover = opt.Value; }

                if (opt.Key == "toggle-border-color")
                { togglebordercolor = opt.Value; }

                if (opt.Key == "toggle-backcolor")
                { togglebackcolor = opt.Value; }

                if (opt.Key == "toggle-backcoloronhover")
                { togglebackcoloronhover = opt.Value; }

                if (opt.Key == "toggle-iconcolor")
                { toggleiconcolor = opt.Value; }

                if (opt.Key == "navbarbrand-paddingtop")
                { navbarbrandpaddingtop = opt.Value; }

                if (opt.Key == "navbarbrand-paddingbottom")
                { navbarbrandpaddingbottom = opt.Value; }

                if (opt.Key == "navbarbrand-paddingleft")
                { navbarbrandpaddingleft = opt.Value; }

                if (opt.Key == "navbarbrand-paddingright")
                { navbarbrandpaddingright = opt.Value; }

                if (opt.Key == "navbar-paddingtop")
                { navbarpaddingtop = opt.Value; }

                if (opt.Key == "navbar-paddingbottom")
                { navbarpaddingbottom = opt.Value; }

                if (opt.Key == "navbar-paddingleft")
                { navbarpaddingleft = opt.Value; }

                if (opt.Key == "navbar-paddingright")
                { navbarpaddingright = opt.Value; }

                if (opt.Key == "dropdown-paddingtop")
                { dropdownpaddingtop = opt.Value; }

                if (opt.Key == "dropdown-paddingbottom")
                { dropdownpaddingbottom = opt.Value; }

                if (opt.Key == "dropdown-paddingleft")
                { dropdownpaddingleft = opt.Value; }

                if (opt.Key == "dropdown-paddingright")
                { dropdownpaddingright = opt.Value; }

                if (opt.Key == "dividercolor")
                { maindividercolor = opt.Value; }

                if (opt.Key == "navbarstyle")
                {
                    navbarstyle = opt.Value;
                    if (navbarstyle == null || navbarstyle == "")
                    {
                        navbarstyle = "navbar-default";
                    }
                    else if (navbarstyle.ToLower().Contains("static-top"))
                    {
                        navbarstyle = "navbar-static-top";
                    }
                    else if (navbarstyle.ToLower().Contains("fixed-top"))
                    {
                        navbarstyle = "navbar-fixed-top";
                    }
                    else
                    {
                        navbarstyle = "navbar-default";
                    }
                }
            }
            if (robj != null)
            {
                if (robj.menu != null && robj.menu.Count > 0 && robj.data != null && robj.data.Count > 0)
                {
                    foreach (var options in robj.menu)
                    {
                        menuname = options.menuname_or_menulogo;
                        //menulogo = options.menuLogo;
                        if (menuname.StartsWith("http"))
                        {
                            menulogo = menuname;
                            menuname = string.Empty;
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <nav");

WriteAttribute("class", Tuple.Create(" class=\"", 9085), Tuple.Create("\"", 9127)
, Tuple.Create(Tuple.Create("", 9093), Tuple.Create("navbar", 9093), true)
, Tuple.Create(Tuple.Create(" ", 9099), Tuple.Create("navbar-default", 9100), true)
            
            #line 244 "..\..\Views\Widgets\MyMenuWidget.cshtml"
, Tuple.Create(Tuple.Create(" ", 9114), Tuple.Create<System.Object, System.Int32>(navbarstyle
            
            #line default
            #line hidden
, 9115), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 9128), Tuple.Create("\"", 9303)
, Tuple.Create(Tuple.Create("", 9136), Tuple.Create("background-color:", 9136), true)
            
            #line 244 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                , Tuple.Create(Tuple.Create("", 9153), Tuple.Create<System.Object, System.Int32>(mainbgcolor
            
            #line default
            #line hidden
, 9153), false)
, Tuple.Create(Tuple.Create("", 9165), Tuple.Create(";", 9165), true)
, Tuple.Create(Tuple.Create(" ", 9166), Tuple.Create("padding-top:", 9167), true)
            
            #line 244 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                          , Tuple.Create(Tuple.Create("", 9179), Tuple.Create<System.Object, System.Int32>(navbarpaddingtop
            
            #line default
            #line hidden
, 9179), false)
, Tuple.Create(Tuple.Create("", 9196), Tuple.Create(";", 9196), true)
, Tuple.Create(Tuple.Create(" ", 9197), Tuple.Create("padding-bottom:", 9198), true)
            
            #line 244 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                            , Tuple.Create(Tuple.Create("", 9213), Tuple.Create<System.Object, System.Int32>(navbarpaddingbottom
            
            #line default
            #line hidden
, 9213), false)
, Tuple.Create(Tuple.Create("", 9233), Tuple.Create(";", 9233), true)
, Tuple.Create(Tuple.Create(" ", 9234), Tuple.Create("padding-left:", 9235), true)
            
            #line 244 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                               , Tuple.Create(Tuple.Create("", 9248), Tuple.Create<System.Object, System.Int32>(navbarpaddingleft
            
            #line default
            #line hidden
, 9248), false)
, Tuple.Create(Tuple.Create("", 9266), Tuple.Create(";", 9266), true)
, Tuple.Create(Tuple.Create(" ", 9267), Tuple.Create("padding-right:", 9268), true)
            
            #line 244 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                 , Tuple.Create(Tuple.Create("", 9282), Tuple.Create<System.Object, System.Int32>(navbarpaddingright
            
            #line default
            #line hidden
, 9282), false)
, Tuple.Create(Tuple.Create("", 9301), Tuple.Create(";", 9301), true)
, Tuple.Create(Tuple.Create(" ", 9302), Tuple.Create("", 9302), true)
);

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"navbar-header\"");

WriteAttribute("style", Tuple.Create(" style=\"", 9418), Tuple.Create("\"", 9489)
, Tuple.Create(Tuple.Create("", 9426), Tuple.Create("font-family:", 9426), true)
            
            #line 246 "..\..\Views\Widgets\MyMenuWidget.cshtml"
, Tuple.Create(Tuple.Create(" ", 9438), Tuple.Create<System.Object, System.Int32>(fontfamilyheader
            
            #line default
            #line hidden
, 9439), false)
, Tuple.Create(Tuple.Create("", 9456), Tuple.Create(";", 9456), true)
, Tuple.Create(Tuple.Create("  ", 9457), Tuple.Create("font-weight:", 9459), true)
            
            #line 246 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                               , Tuple.Create(Tuple.Create("", 9471), Tuple.Create<System.Object, System.Int32>(fontweightheader
            
            #line default
            #line hidden
, 9471), false)
, Tuple.Create(Tuple.Create("", 9488), Tuple.Create(";", 9488), true)
);

WriteLiteral(">\r\n                                    <button");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteAttribute("style", Tuple.Create(" style=\"", 9612), Tuple.Create("\"", 9688)
, Tuple.Create(Tuple.Create("", 9620), Tuple.Create("border-color:", 9620), true)
            
            #line 247 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                            , Tuple.Create(Tuple.Create("", 9633), Tuple.Create<System.Object, System.Int32>(togglebordercolor
            
            #line default
            #line hidden
, 9633), false)
, Tuple.Create(Tuple.Create("", 9651), Tuple.Create(";", 9651), true)
, Tuple.Create(Tuple.Create("  ", 9652), Tuple.Create("background-color:", 9654), true)
            
            #line 247 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                  , Tuple.Create(Tuple.Create("", 9671), Tuple.Create<System.Object, System.Int32>(togglebackcolor
            
            #line default
            #line hidden
, 9671), false)
, Tuple.Create(Tuple.Create("", 9687), Tuple.Create(";", 9687), true)
);

WriteAttribute("onmouseover", Tuple.Create(" onmouseover=\"", 9689), Tuple.Create("\"", 9756)
, Tuple.Create(Tuple.Create("", 9703), Tuple.Create("this.style.backgroundColor=\'", 9703), true)
            
            #line 247 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                              , Tuple.Create(Tuple.Create("", 9731), Tuple.Create<System.Object, System.Int32>(togglebackcoloronhover
            
            #line default
            #line hidden
, 9731), false)
, Tuple.Create(Tuple.Create("", 9754), Tuple.Create("\';", 9754), true)
);

WriteAttribute("onmouseout", Tuple.Create(" onmouseout=\"", 9757), Tuple.Create("\"", 9816)
, Tuple.Create(Tuple.Create("", 9770), Tuple.Create("this.style.backgroundColor=\'", 9770), true)
            
            #line 247 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                 , Tuple.Create(Tuple.Create("", 9798), Tuple.Create<System.Object, System.Int32>(togglebackcolor
            
            #line default
            #line hidden
, 9798), false)
, Tuple.Create(Tuple.Create("", 9814), Tuple.Create("\';", 9814), true)
);

WriteLiteral(">\r\n                                        <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle Navigation</span>\r\n                                        <span");

WriteLiteral(" class=\"icon-bar\"");

WriteAttribute("style", Tuple.Create(" style=\"", 9970), Tuple.Create("\"", 10012)
, Tuple.Create(Tuple.Create("", 9978), Tuple.Create("background-color:", 9978), true)
            
            #line 249 "..\..\Views\Widgets\MyMenuWidget.cshtml"
       , Tuple.Create(Tuple.Create("", 9995), Tuple.Create<System.Object, System.Int32>(toggleiconcolor
            
            #line default
            #line hidden
, 9995), false)
, Tuple.Create(Tuple.Create("", 10011), Tuple.Create(";", 10011), true)
);

WriteLiteral("></span>\r\n                                        <span");

WriteLiteral(" class=\"icon-bar\"");

WriteAttribute("style", Tuple.Create(" style=\"", 10085), Tuple.Create("\"", 10127)
, Tuple.Create(Tuple.Create("", 10093), Tuple.Create("background-color:", 10093), true)
            
            #line 250 "..\..\Views\Widgets\MyMenuWidget.cshtml"
      , Tuple.Create(Tuple.Create("", 10110), Tuple.Create<System.Object, System.Int32>(toggleiconcolor
            
            #line default
            #line hidden
, 10110), false)
, Tuple.Create(Tuple.Create("", 10126), Tuple.Create(";", 10126), true)
);

WriteLiteral("></span>\r\n                                        <span");

WriteLiteral(" class=\"icon-bar\"");

WriteAttribute("style", Tuple.Create(" style=\"", 10200), Tuple.Create("\"", 10242)
, Tuple.Create(Tuple.Create("", 10208), Tuple.Create("background-color:", 10208), true)
            
            #line 251 "..\..\Views\Widgets\MyMenuWidget.cshtml"
      , Tuple.Create(Tuple.Create("", 10225), Tuple.Create<System.Object, System.Int32>(toggleiconcolor
            
            #line default
            #line hidden
, 10225), false)
, Tuple.Create(Tuple.Create("", 10241), Tuple.Create(";", 10241), true)
);

WriteLiteral("></span>\r\n                                    </button>\r\n                        " +
"            <a");

WriteLiteral(" id=\"imganchor\"");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" href=\"#\"");

WriteAttribute("style", Tuple.Create(" style=\"", 10383), Tuple.Create("\"", 10678)
, Tuple.Create(Tuple.Create("", 10391), Tuple.Create("color:", 10391), true)
            
            #line 253 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                , Tuple.Create(Tuple.Create("", 10397), Tuple.Create<System.Object, System.Int32>(textcolorheader
            
            #line default
            #line hidden
, 10397), false)
, Tuple.Create(Tuple.Create("", 10413), Tuple.Create(";", 10413), true)
, Tuple.Create(Tuple.Create(" ", 10414), Tuple.Create("background-image:url(", 10415), true)
            
            #line 253 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                       , Tuple.Create(Tuple.Create("", 10436), Tuple.Create<System.Object, System.Int32>(menulogo
            
            #line default
            #line hidden
, 10436), false)
, Tuple.Create(Tuple.Create("", 10445), Tuple.Create(");", 10445), true)
, Tuple.Create(Tuple.Create(" ", 10447), Tuple.Create("background-repeat:no-repeat;", 10448), true)
, Tuple.Create(Tuple.Create(" ", 10476), Tuple.Create("padding:0px", 10477), true)
, Tuple.Create(Tuple.Create(" ", 10488), Tuple.Create("10px;", 10489), true)
, Tuple.Create(Tuple.Create(" ", 10494), Tuple.Create("font-size:", 10495), true)
            
            #line 253 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                            , Tuple.Create(Tuple.Create("", 10505), Tuple.Create<System.Object, System.Int32>(fontsizeheader
            
            #line default
            #line hidden
, 10505), false)
, Tuple.Create(Tuple.Create("", 10520), Tuple.Create(";", 10520), true)
, Tuple.Create(Tuple.Create(" ", 10521), Tuple.Create("padding-top:", 10522), true)
            
            #line 253 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                         , Tuple.Create(Tuple.Create("", 10534), Tuple.Create<System.Object, System.Int32>(navbarbrandpaddingtop
            
            #line default
            #line hidden
, 10534), false)
, Tuple.Create(Tuple.Create("", 10556), Tuple.Create(";", 10556), true)
, Tuple.Create(Tuple.Create(" ", 10557), Tuple.Create("padding-bottom:", 10558), true)
            
            #line 253 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                , Tuple.Create(Tuple.Create("", 10573), Tuple.Create<System.Object, System.Int32>(navbarbrandpaddingbottom
            
            #line default
            #line hidden
, 10573), false)
, Tuple.Create(Tuple.Create("", 10598), Tuple.Create(";", 10598), true)
, Tuple.Create(Tuple.Create(" ", 10599), Tuple.Create("padding-left:", 10600), true)
            
            #line 253 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                        , Tuple.Create(Tuple.Create("", 10613), Tuple.Create<System.Object, System.Int32>(navbarbrandpaddingleft
            
            #line default
            #line hidden
, 10613), false)
, Tuple.Create(Tuple.Create("", 10636), Tuple.Create(";", 10636), true)
, Tuple.Create(Tuple.Create(" ", 10637), Tuple.Create("padding-right:", 10638), true)
            
            #line 253 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                                                               , Tuple.Create(Tuple.Create("", 10652), Tuple.Create<System.Object, System.Int32>(navbarbrandpaddingright
            
            #line default
            #line hidden
, 10652), false)
, Tuple.Create(Tuple.Create("", 10676), Tuple.Create(";", 10676), true)
, Tuple.Create(Tuple.Create(" ", 10677), Tuple.Create("", 10677), true)
);

WriteAttribute("onmouseover", Tuple.Create(" onmouseover=\"", 10679), Tuple.Create("\"", 10734)
, Tuple.Create(Tuple.Create("", 10693), Tuple.Create("this.style.color=\'", 10693), true)
            
            #line 253 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                                                                                                                          , Tuple.Create(Tuple.Create("", 10711), Tuple.Create<System.Object, System.Int32>(textcolorheaderhover
            
            #line default
            #line hidden
, 10711), false)
, Tuple.Create(Tuple.Create("", 10732), Tuple.Create("\'", 10732), true)
, Tuple.Create(Tuple.Create(" ", 10733), Tuple.Create("", 10733), true)
);

WriteAttribute("onmouseout", Tuple.Create(" onmouseout=\"", 10735), Tuple.Create("\"", 10784)
, Tuple.Create(Tuple.Create("", 10748), Tuple.Create("this.style.color=\'", 10748), true)
            
            #line 253 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                                 , Tuple.Create(Tuple.Create("", 10766), Tuple.Create<System.Object, System.Int32>(textcolorheader
            
            #line default
            #line hidden
, 10766), false)
, Tuple.Create(Tuple.Create("", 10782), Tuple.Create("\'", 10782), true)
, Tuple.Create(Tuple.Create(" ", 10783), Tuple.Create("", 10783), true)
);

WriteLiteral(">\r\n");

WriteLiteral("                                        ");

            
            #line 254 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                   Write(menuname);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </a>\r\n\r\n                                </d" +
"iv>\r\n                                <div");

WriteLiteral(" class=\"collapse navbar-collapse\"");

WriteLiteral(" id=\"bs-example-navbar-collapse-1\"");

WriteLiteral(" data-hover=\"dropdown\"");

WriteLiteral(" data-animations=\"");

            
            #line 258 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                          Write(animation);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n                                    <ul");

WriteLiteral(" class=\"nav navbar-nav navbar-right\"");

WriteLiteral(">\r\n");

            
            #line 260 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 260 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                         foreach (var dataobj in robj.data)
                                        {
                                            text = dataobj.text;
                                            link = dataobj.link;
                                            if (text.StartsWith("http"))
                                            {
                                                homeimage = text;
                                                text = string.Empty;
                                            }

                                            if (dataobj.sub != null && dataobj.sub.Count > 0)
                                            {

            
            #line default
            #line hidden
WriteLiteral("                                                <li");

WriteLiteral(" class=\"dropdown\"");

WriteAttribute("style", Tuple.Create(" style=\"", 11927), Tuple.Create("\"", 12052)
, Tuple.Create(Tuple.Create("", 11935), Tuple.Create("font-family:", 11935), true)
            
            #line 272 "..\..\Views\Widgets\MyMenuWidget.cshtml"
       , Tuple.Create(Tuple.Create(" ", 11947), Tuple.Create<System.Object, System.Int32>(fontfamilymenu
            
            #line default
            #line hidden
, 11948), false)
, Tuple.Create(Tuple.Create("", 11963), Tuple.Create(";", 11963), true)
, Tuple.Create(Tuple.Create("  ", 11964), Tuple.Create("font-size:", 11966), true)
            
            #line 272 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                    , Tuple.Create(Tuple.Create("", 11976), Tuple.Create<System.Object, System.Int32>(fontsizemenu
            
            #line default
            #line hidden
, 11976), false)
, Tuple.Create(Tuple.Create("", 11989), Tuple.Create(";", 11989), true)
, Tuple.Create(Tuple.Create(" ", 11990), Tuple.Create("font-weight:", 11991), true)
            
            #line 272 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                               , Tuple.Create(Tuple.Create("", 12003), Tuple.Create<System.Object, System.Int32>(fontweightmenu
            
            #line default
            #line hidden
, 12003), false)
, Tuple.Create(Tuple.Create("", 12018), Tuple.Create(";", 12018), true)
, Tuple.Create(Tuple.Create(" ", 12019), Tuple.Create("background-color:", 12020), true)
            
            #line 272 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                 , Tuple.Create(Tuple.Create("", 12037), Tuple.Create<System.Object, System.Int32>(menubackcolor
            
            #line default
            #line hidden
, 12037), false)
, Tuple.Create(Tuple.Create("", 12051), Tuple.Create(";", 12051), true)
);

WriteLiteral(">\r\n");

            
            #line 273 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                    
            
            #line default
            #line hidden
            
            #line 273 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                     if (homeimage != "")
                                                    {
                                                        

            
            #line default
            #line hidden
WriteLiteral("                                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 12302), Tuple.Create("\"", 12314)
            
            #line 276 "..\..\Views\Widgets\MyMenuWidget.cshtml"
, Tuple.Create(Tuple.Create("", 12309), Tuple.Create<System.Object, System.Int32>(link
            
            #line default
            #line hidden
, 12309), false)
);

WriteLiteral(" class=\"dropdown-toggle listdrop \"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteAttribute("style", Tuple.Create(" style=\"", 12408), Tuple.Create("\"", 12437)
, Tuple.Create(Tuple.Create("", 12416), Tuple.Create("color:", 12416), true)
            
            #line 276 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                 , Tuple.Create(Tuple.Create("", 12422), Tuple.Create<System.Object, System.Int32>(textcolormenu
            
            #line default
            #line hidden
, 12422), false)
, Tuple.Create(Tuple.Create("", 12436), Tuple.Create(";", 12436), true)
);

WriteAttribute("onmouseover", Tuple.Create(" onmouseover=\"", 12438), Tuple.Create("\"", 12543)
, Tuple.Create(Tuple.Create("", 12452), Tuple.Create("this.style.color=\'", 12452), true)
            
            #line 276 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                 , Tuple.Create(Tuple.Create("", 12470), Tuple.Create<System.Object, System.Int32>(textcolormenuhover
            
            #line default
            #line hidden
, 12470), false)
, Tuple.Create(Tuple.Create("", 12489), Tuple.Create("\';", 12489), true)
, Tuple.Create(Tuple.Create(" ", 12491), Tuple.Create("this.style.backgroundColor=\'", 12492), true)
            
            #line 276 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                   , Tuple.Create(Tuple.Create("", 12520), Tuple.Create<System.Object, System.Int32>(menubackcoloronhover
            
            #line default
            #line hidden
, 12520), false)
, Tuple.Create(Tuple.Create("", 12541), Tuple.Create("\'", 12541), true)
, Tuple.Create(Tuple.Create(" ", 12542), Tuple.Create("", 12542), true)
);

WriteAttribute("onmouseout", Tuple.Create(" onmouseout=\"", 12544), Tuple.Create("\"", 12637)
, Tuple.Create(Tuple.Create("", 12557), Tuple.Create("this.style.color", 12557), true)
, Tuple.Create(Tuple.Create(" ", 12573), Tuple.Create("=", 12574), true)
, Tuple.Create(Tuple.Create(" ", 12575), Tuple.Create("\'", 12576), true)
            
            #line 276 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                                            , Tuple.Create(Tuple.Create("", 12577), Tuple.Create<System.Object, System.Int32>(textcolormenu
            
            #line default
            #line hidden
, 12577), false)
, Tuple.Create(Tuple.Create("", 12591), Tuple.Create("\';", 12591), true)
, Tuple.Create(Tuple.Create(" ", 12593), Tuple.Create("this.style.backgroundColor=\'", 12594), true)
            
            #line 276 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                                                                                         , Tuple.Create(Tuple.Create("", 12622), Tuple.Create<System.Object, System.Int32>(menubackcolor
            
            #line default
            #line hidden
, 12622), false)
, Tuple.Create(Tuple.Create("", 12636), Tuple.Create("\'", 12636), true)
);

WriteLiteral(">\r\n                                                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 12705), Tuple.Create("\"", 12721)
            
            #line 277 "..\..\Views\Widgets\MyMenuWidget.cshtml"
, Tuple.Create(Tuple.Create("", 12711), Tuple.Create<System.Object, System.Int32>(homeimage
            
            #line default
            #line hidden
, 12711), false)
);

WriteLiteral("/>\r\n                                                            <span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span>\r\n                                                        </a>");

            
            #line 279 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                            homeimage = string.Empty;
                                                    }
                                                    else
                                                    {


            
            #line default
            #line hidden
WriteLiteral("                                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 13130), Tuple.Create("\"", 13142)
            
            #line 284 "..\..\Views\Widgets\MyMenuWidget.cshtml"
, Tuple.Create(Tuple.Create("", 13137), Tuple.Create<System.Object, System.Int32>(link
            
            #line default
            #line hidden
, 13137), false)
);

WriteLiteral(" class=\"dropdown-toggle listdrop \"");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" aria-expanded=\"false\"");

WriteAttribute("style", Tuple.Create(" style=\"", 13236), Tuple.Create("\"", 13265)
, Tuple.Create(Tuple.Create("", 13244), Tuple.Create("color:", 13244), true)
            
            #line 284 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                 , Tuple.Create(Tuple.Create("", 13250), Tuple.Create<System.Object, System.Int32>(textcolormenu
            
            #line default
            #line hidden
, 13250), false)
, Tuple.Create(Tuple.Create("", 13264), Tuple.Create(";", 13264), true)
);

WriteAttribute("onmouseover", Tuple.Create(" onmouseover=\"", 13266), Tuple.Create("\"", 13371)
, Tuple.Create(Tuple.Create("", 13280), Tuple.Create("this.style.color=\'", 13280), true)
            
            #line 284 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                 , Tuple.Create(Tuple.Create("", 13298), Tuple.Create<System.Object, System.Int32>(textcolormenuhover
            
            #line default
            #line hidden
, 13298), false)
, Tuple.Create(Tuple.Create("", 13317), Tuple.Create("\';", 13317), true)
, Tuple.Create(Tuple.Create(" ", 13319), Tuple.Create("this.style.backgroundColor=\'", 13320), true)
            
            #line 284 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                   , Tuple.Create(Tuple.Create("", 13348), Tuple.Create<System.Object, System.Int32>(menubackcoloronhover
            
            #line default
            #line hidden
, 13348), false)
, Tuple.Create(Tuple.Create("", 13369), Tuple.Create("\'", 13369), true)
, Tuple.Create(Tuple.Create(" ", 13370), Tuple.Create("", 13370), true)
);

WriteAttribute("onmouseout", Tuple.Create(" onmouseout=\"", 13372), Tuple.Create("\"", 13465)
, Tuple.Create(Tuple.Create("", 13385), Tuple.Create("this.style.color", 13385), true)
, Tuple.Create(Tuple.Create(" ", 13401), Tuple.Create("=", 13402), true)
, Tuple.Create(Tuple.Create(" ", 13403), Tuple.Create("\'", 13404), true)
            
            #line 284 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                                            , Tuple.Create(Tuple.Create("", 13405), Tuple.Create<System.Object, System.Int32>(textcolormenu
            
            #line default
            #line hidden
, 13405), false)
, Tuple.Create(Tuple.Create("", 13419), Tuple.Create("\';", 13419), true)
, Tuple.Create(Tuple.Create(" ", 13421), Tuple.Create("this.style.backgroundColor=\'", 13422), true)
            
            #line 284 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                                                                                         , Tuple.Create(Tuple.Create("", 13450), Tuple.Create<System.Object, System.Int32>(menubackcolor
            
            #line default
            #line hidden
, 13450), false)
, Tuple.Create(Tuple.Create("", 13464), Tuple.Create("\'", 13464), true)
);

WriteLiteral(">\r\n");

WriteLiteral("                                                            ");

            
            #line 285 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                       Write(text);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                                            <span");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></span>\r\n                                                        </a>\r\n");

WriteLiteral("                                                        <ul");

WriteLiteral(" class=\"dropdown-menu submenu\"");

WriteAttribute("style", Tuple.Create(" style=\"", 13776), Tuple.Create("\"", 13817)
, Tuple.Create(Tuple.Create("", 13784), Tuple.Create("background-color:", 13784), true)
            
            #line 288 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                 , Tuple.Create(Tuple.Create("", 13801), Tuple.Create<System.Object, System.Int32>(listbackcolor
            
            #line default
            #line hidden
, 13801), false)
, Tuple.Create(Tuple.Create("", 13815), Tuple.Create(";", 13815), true)
, Tuple.Create(Tuple.Create(" ", 13816), Tuple.Create("", 13816), true)
);

WriteLiteral(" role=\"menu\"");

WriteLiteral(">\r\n");

            
            #line 289 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                            
            
            #line default
            #line hidden
            
            #line 289 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                             foreach (var submenu in dataobj.sub)
                                                            {
                                                                count = dataobj.sub.Count;
                                                                subText = submenu.text;
                                                                subLink = submenu.link;


            
            #line default
            #line hidden
WriteLiteral("                                                                <li");

WriteAttribute("style", Tuple.Create(" style=\"", 14334), Tuple.Create("\"", 14405)
, Tuple.Create(Tuple.Create("", 14342), Tuple.Create("font-family:", 14342), true)
            
            #line 295 "..\..\Views\Widgets\MyMenuWidget.cshtml"
      , Tuple.Create(Tuple.Create(" ", 14354), Tuple.Create<System.Object, System.Int32>(fontfamilysubmenu
            
            #line default
            #line hidden
, 14355), false)
, Tuple.Create(Tuple.Create("", 14373), Tuple.Create(";", 14373), true)
, Tuple.Create(Tuple.Create("  ", 14374), Tuple.Create("font-size:", 14376), true)
            
            #line 295 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                      , Tuple.Create(Tuple.Create("", 14386), Tuple.Create<System.Object, System.Int32>(fontsizesubmenu
            
            #line default
            #line hidden
, 14386), false)
, Tuple.Create(Tuple.Create("", 14402), Tuple.Create(";", 14402), true)
, Tuple.Create(Tuple.Create("  ", 14403), Tuple.Create("", 14403), true)
);

WriteLiteral(">\r\n                                                                    <a");

WriteAttribute("href", Tuple.Create(" href=\"", 14479), Tuple.Create("\"", 14494)
            
            #line 296 "..\..\Views\Widgets\MyMenuWidget.cshtml"
, Tuple.Create(Tuple.Create("", 14486), Tuple.Create<System.Object, System.Int32>(subLink
            
            #line default
            #line hidden
, 14486), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 14495), Tuple.Create("\"", 14703)
, Tuple.Create(Tuple.Create("", 14503), Tuple.Create("color:", 14503), true)
            
            #line 296 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                   , Tuple.Create(Tuple.Create("", 14509), Tuple.Create<System.Object, System.Int32>(textcolorsubmenu
            
            #line default
            #line hidden
, 14509), false)
, Tuple.Create(Tuple.Create("", 14526), Tuple.Create(";", 14526), true)
, Tuple.Create(Tuple.Create(" ", 14527), Tuple.Create("font-weight:", 14528), true)
            
            #line 296 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                  , Tuple.Create(Tuple.Create("", 14540), Tuple.Create<System.Object, System.Int32>(fontweightsubmenu
            
            #line default
            #line hidden
, 14540), false)
, Tuple.Create(Tuple.Create("", 14558), Tuple.Create(";", 14558), true)
, Tuple.Create(Tuple.Create(" ", 14559), Tuple.Create("padding-top:", 14560), true)
            
            #line 296 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                  , Tuple.Create(Tuple.Create("", 14572), Tuple.Create<System.Object, System.Int32>(dropdownpaddingtop
            
            #line default
            #line hidden
, 14572), false)
, Tuple.Create(Tuple.Create("", 14591), Tuple.Create(";", 14591), true)
, Tuple.Create(Tuple.Create(" ", 14592), Tuple.Create("padding-bottom:", 14593), true)
            
            #line 296 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                      , Tuple.Create(Tuple.Create("", 14608), Tuple.Create<System.Object, System.Int32>(dropdownpaddingbottom
            
            #line default
            #line hidden
, 14608), false)
, Tuple.Create(Tuple.Create("", 14630), Tuple.Create(";", 14630), true)
, Tuple.Create(Tuple.Create(" ", 14631), Tuple.Create("padding-left:", 14632), true)
            
            #line 296 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                           , Tuple.Create(Tuple.Create("", 14645), Tuple.Create<System.Object, System.Int32>(dropdownpaddingleft
            
            #line default
            #line hidden
, 14645), false)
, Tuple.Create(Tuple.Create("", 14665), Tuple.Create(";", 14665), true)
, Tuple.Create(Tuple.Create(" ", 14666), Tuple.Create("padding-right:", 14667), true)
            
            #line 296 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                               , Tuple.Create(Tuple.Create("", 14681), Tuple.Create<System.Object, System.Int32>(dropdownpaddingright
            
            #line default
            #line hidden
, 14681), false)
, Tuple.Create(Tuple.Create("", 14702), Tuple.Create(";", 14702), true)
);

WriteAttribute("onmouseover", Tuple.Create(" onmouseover=\"", 14704), Tuple.Create("\"", 14813)
, Tuple.Create(Tuple.Create("", 14718), Tuple.Create("this.style.backgroundColor=\'", 14718), true)
            
            #line 296 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                                                , Tuple.Create(Tuple.Create("", 14746), Tuple.Create<System.Object, System.Int32>(listbackcoloronhover
            
            #line default
            #line hidden
, 14746), false)
, Tuple.Create(Tuple.Create("", 14767), Tuple.Create("\';", 14767), true)
, Tuple.Create(Tuple.Create(" ", 14769), Tuple.Create("this.style.color=\'", 14770), true)
            
            #line 296 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                                                                                          , Tuple.Create(Tuple.Create("", 14788), Tuple.Create<System.Object, System.Int32>(textcolorsubmenuhover
            
            #line default
            #line hidden
, 14788), false)
, Tuple.Create(Tuple.Create("", 14810), Tuple.Create("\';", 14810), true)
, Tuple.Create(Tuple.Create(" ", 14812), Tuple.Create("", 14812), true)
);

WriteAttribute("onmouseout", Tuple.Create(" onmouseout=\"", 14814), Tuple.Create("\"", 14914)
, Tuple.Create(Tuple.Create("", 14827), Tuple.Create("this.style.backgroundColor", 14827), true)
, Tuple.Create(Tuple.Create(" ", 14853), Tuple.Create("=", 14854), true)
, Tuple.Create(Tuple.Create(" ", 14855), Tuple.Create("\'", 14856), true)
            
            #line 296 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                                                                                                                                                               , Tuple.Create(Tuple.Create("", 14857), Tuple.Create<System.Object, System.Int32>(listbackcolor
            
            #line default
            #line hidden
, 14857), false)
, Tuple.Create(Tuple.Create("", 14871), Tuple.Create("\';", 14871), true)
, Tuple.Create(Tuple.Create(" ", 14873), Tuple.Create("this.style.color", 14874), true)
, Tuple.Create(Tuple.Create(" ", 14890), Tuple.Create("=", 14891), true)
, Tuple.Create(Tuple.Create(" ", 14892), Tuple.Create("\'", 14893), true)
            
            #line 296 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                                                    , Tuple.Create(Tuple.Create("", 14894), Tuple.Create<System.Object, System.Int32>(textcolorsubmenu
            
            #line default
            #line hidden
, 14894), false)
, Tuple.Create(Tuple.Create("", 14911), Tuple.Create("\';", 14911), true)
, Tuple.Create(Tuple.Create(" ", 14913), Tuple.Create("", 14913), true)
);

WriteLiteral(">");

            
            #line 296 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      Write(subText);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                                                </li>\r\n");

WriteLiteral("                                                                <li");

WriteLiteral(" class=\"divider\"");

WriteAttribute("style", Tuple.Create(" style=\"", 15084), Tuple.Create("\"", 15115)
, Tuple.Create(Tuple.Create("", 15092), Tuple.Create("color:", 15092), true)
            
            #line 298 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                , Tuple.Create(Tuple.Create("", 15098), Tuple.Create<System.Object, System.Int32>(maindividercolor
            
            #line default
            #line hidden
, 15098), false)
);

WriteLiteral("></li>\r\n");

            
            #line 299 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                            }

            
            #line default
            #line hidden
WriteLiteral("                                                            ");

            
            #line 300 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                             for (cnt = 1; cnt <= count + 1; cnt++)
                                                            {
                                                                if (cnt > count)
                                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                                    <li");

WriteLiteral(" class=\"divider-color\"");

WriteAttribute("style", Tuple.Create(" style=\"", 15593), Tuple.Create("\"", 15630)
, Tuple.Create(Tuple.Create("", 15601), Tuple.Create("background:", 15601), true)
            
            #line 304 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                               , Tuple.Create(Tuple.Create("", 15612), Tuple.Create<System.Object, System.Int32>(lastdividercolor
            
            #line default
            #line hidden
, 15612), false)
, Tuple.Create(Tuple.Create("", 15629), Tuple.Create(";", 15629), true)
);

WriteLiteral("></li>\r\n");

            
            #line 305 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                }
                                                            }

            
            #line default
            #line hidden
WriteLiteral("                                                        </ul>\r\n");

            
            #line 308 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                    }

            
            #line default
            #line hidden
WriteLiteral("                                                </li>\r\n");

            
            #line 310 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                            }
                                            else
                                            {


            
            #line default
            #line hidden
WriteLiteral("                                                <li");

WriteAttribute("style", Tuple.Create(" style=\"", 16139), Tuple.Create("\"", 16286)
, Tuple.Create(Tuple.Create("", 16147), Tuple.Create("font-family:", 16147), true)
            
            #line 314 "..\..\Views\Widgets\MyMenuWidget.cshtml"
, Tuple.Create(Tuple.Create("", 16159), Tuple.Create<System.Object, System.Int32>(fontfamilymenu
            
            #line default
            #line hidden
, 16159), false)
, Tuple.Create(Tuple.Create("", 16174), Tuple.Create(";", 16174), true)
, Tuple.Create(Tuple.Create("  ", 16175), Tuple.Create("font-size:", 16177), true)
            
            #line 314 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                  , Tuple.Create(Tuple.Create("", 16187), Tuple.Create<System.Object, System.Int32>(fontsizemenu
            
            #line default
            #line hidden
, 16187), false)
, Tuple.Create(Tuple.Create("", 16200), Tuple.Create(";", 16200), true)
, Tuple.Create(Tuple.Create(" ", 16201), Tuple.Create("font-weight:", 16202), true)
            
            #line 314 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                             , Tuple.Create(Tuple.Create("", 16214), Tuple.Create<System.Object, System.Int32>(fontweightmenu
            
            #line default
            #line hidden
, 16214), false)
, Tuple.Create(Tuple.Create("", 16229), Tuple.Create(";", 16229), true)
, Tuple.Create(Tuple.Create(" ", 16230), Tuple.Create("color:", 16231), true)
            
            #line 314 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                    , Tuple.Create(Tuple.Create("", 16237), Tuple.Create<System.Object, System.Int32>(textcolormenu
            
            #line default
            #line hidden
, 16237), false)
, Tuple.Create(Tuple.Create("", 16251), Tuple.Create(";", 16251), true)
, Tuple.Create(Tuple.Create(" ", 16252), Tuple.Create("background-color:", 16253), true)
            
            #line 314 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                     , Tuple.Create(Tuple.Create("", 16270), Tuple.Create<System.Object, System.Int32>(menubackcolor
            
            #line default
            #line hidden
, 16270), false)
, Tuple.Create(Tuple.Create("", 16284), Tuple.Create(";", 16284), true)
, Tuple.Create(Tuple.Create(" ", 16285), Tuple.Create("", 16285), true)
);

WriteLiteral(">\r\n");

            
            #line 315 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                    
            
            #line default
            #line hidden
            
            #line 315 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                     if (homeimage != "")
                                                    {

            
            #line default
            #line hidden
WriteLiteral("                                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 16478), Tuple.Create("\"", 16490)
            
            #line 317 "..\..\Views\Widgets\MyMenuWidget.cshtml"
, Tuple.Create(Tuple.Create("", 16485), Tuple.Create<System.Object, System.Int32>(link
            
            #line default
            #line hidden
, 16485), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 16491), Tuple.Create("\"", 16522)
, Tuple.Create(Tuple.Create("", 16499), Tuple.Create("color:", 16499), true)
            
            #line 317 "..\..\Views\Widgets\MyMenuWidget.cshtml"
    , Tuple.Create(Tuple.Create("", 16505), Tuple.Create<System.Object, System.Int32>(textcolormenu
            
            #line default
            #line hidden
, 16505), false)
, Tuple.Create(Tuple.Create("", 16519), Tuple.Create(";", 16519), true)
, Tuple.Create(Tuple.Create("  ", 16520), Tuple.Create("", 16520), true)
);

WriteAttribute("onmouseover", Tuple.Create(" onmouseover=\"", 16523), Tuple.Create("\"", 16628)
, Tuple.Create(Tuple.Create("", 16537), Tuple.Create("this.style.color=\'", 16537), true)
            
            #line 317 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                      , Tuple.Create(Tuple.Create("", 16555), Tuple.Create<System.Object, System.Int32>(textcolormenuhover
            
            #line default
            #line hidden
, 16555), false)
, Tuple.Create(Tuple.Create("", 16574), Tuple.Create("\';", 16574), true)
, Tuple.Create(Tuple.Create(" ", 16576), Tuple.Create("this.style.backgroundColor=\'", 16577), true)
            
            #line 317 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                        , Tuple.Create(Tuple.Create("", 16605), Tuple.Create<System.Object, System.Int32>(menubackcoloronhover
            
            #line default
            #line hidden
, 16605), false)
, Tuple.Create(Tuple.Create("", 16626), Tuple.Create("\'", 16626), true)
, Tuple.Create(Tuple.Create(" ", 16627), Tuple.Create("", 16627), true)
);

WriteAttribute("onmouseout", Tuple.Create(" onmouseout=\"", 16629), Tuple.Create("\"", 16722)
, Tuple.Create(Tuple.Create("", 16642), Tuple.Create("this.style.color", 16642), true)
, Tuple.Create(Tuple.Create(" ", 16658), Tuple.Create("=", 16659), true)
, Tuple.Create(Tuple.Create(" ", 16660), Tuple.Create("\'", 16661), true)
            
            #line 317 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                 , Tuple.Create(Tuple.Create("", 16662), Tuple.Create<System.Object, System.Int32>(textcolormenu
            
            #line default
            #line hidden
, 16662), false)
, Tuple.Create(Tuple.Create("", 16676), Tuple.Create("\';", 16676), true)
, Tuple.Create(Tuple.Create(" ", 16678), Tuple.Create("this.style.backgroundColor=\'", 16679), true)
            
            #line 317 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                              , Tuple.Create(Tuple.Create("", 16707), Tuple.Create<System.Object, System.Int32>(menubackcolor
            
            #line default
            #line hidden
, 16707), false)
, Tuple.Create(Tuple.Create("", 16721), Tuple.Create("\'", 16721), true)
);

WriteLiteral(">\r\n                                                            <img");

WriteAttribute("src", Tuple.Create(" src=\"", 16790), Tuple.Create("\"", 16806)
            
            #line 318 "..\..\Views\Widgets\MyMenuWidget.cshtml"
, Tuple.Create(Tuple.Create("", 16796), Tuple.Create<System.Object, System.Int32>(homeimage
            
            #line default
            #line hidden
, 16796), false)
);

WriteLiteral(" />                                                          \r\n                  " +
"                                      </a>");

            
            #line 319 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                            homeimage = string.Empty;
                                                    }
                                                    else
                                                    {


            
            #line default
            #line hidden
WriteLiteral("                                                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 17185), Tuple.Create("\"", 17197)
            
            #line 324 "..\..\Views\Widgets\MyMenuWidget.cshtml"
, Tuple.Create(Tuple.Create("", 17192), Tuple.Create<System.Object, System.Int32>(link
            
            #line default
            #line hidden
, 17192), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 17198), Tuple.Create("\"", 17227)
, Tuple.Create(Tuple.Create("", 17206), Tuple.Create("color:", 17206), true)
            
            #line 324 "..\..\Views\Widgets\MyMenuWidget.cshtml"
    , Tuple.Create(Tuple.Create("", 17212), Tuple.Create<System.Object, System.Int32>(textcolormenu
            
            #line default
            #line hidden
, 17212), false)
, Tuple.Create(Tuple.Create("", 17226), Tuple.Create(";", 17226), true)
);

WriteAttribute("onmouseover", Tuple.Create(" onmouseover=\"", 17228), Tuple.Create("\"", 17332)
, Tuple.Create(Tuple.Create("", 17242), Tuple.Create("this.style.color=\'", 17242), true)
            
            #line 324 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                    , Tuple.Create(Tuple.Create("", 17260), Tuple.Create<System.Object, System.Int32>(textcolormenuhover
            
            #line default
            #line hidden
, 17260), false)
, Tuple.Create(Tuple.Create("", 17279), Tuple.Create("\';", 17279), true)
, Tuple.Create(Tuple.Create(" ", 17281), Tuple.Create("this.style.backgroundColor=\'", 17282), true)
            
            #line 324 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                      , Tuple.Create(Tuple.Create("", 17310), Tuple.Create<System.Object, System.Int32>(menubackcoloronhover
            
            #line default
            #line hidden
, 17310), false)
, Tuple.Create(Tuple.Create("", 17331), Tuple.Create("\'", 17331), true)
);

WriteAttribute("onmouseout", Tuple.Create(" onmouseout=\"", 17333), Tuple.Create("\"", 17428)
, Tuple.Create(Tuple.Create("", 17346), Tuple.Create("this.style.color", 17346), true)
, Tuple.Create(Tuple.Create(" ", 17362), Tuple.Create("=", 17363), true)
, Tuple.Create(Tuple.Create(" ", 17364), Tuple.Create("\'", 17365), true)
            
            #line 324 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                              , Tuple.Create(Tuple.Create("", 17366), Tuple.Create<System.Object, System.Int32>(textcolormenu
            
            #line default
            #line hidden
, 17366), false)
, Tuple.Create(Tuple.Create("", 17380), Tuple.Create("\';", 17380), true)
, Tuple.Create(Tuple.Create(" ", 17382), Tuple.Create("this.style.backgroundColor", 17383), true)
, Tuple.Create(Tuple.Create(" ", 17409), Tuple.Create("=", 17410), true)
, Tuple.Create(Tuple.Create(" ", 17411), Tuple.Create("\'", 17412), true)
            
            #line 324 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                             , Tuple.Create(Tuple.Create("", 17413), Tuple.Create<System.Object, System.Int32>(menubackcolor
            
            #line default
            #line hidden
, 17413), false)
, Tuple.Create(Tuple.Create("", 17427), Tuple.Create("\'", 17427), true)
);

WriteLiteral(">");

            
            #line 324 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                                                                                                                                                                                                                                                                          Write(text);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 325 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                                    }

            
            #line default
            #line hidden
WriteLiteral("                                                </li>\r\n");

            
            #line 327 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                                            }
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </ul>\r\n\r\n                                </di" +
"v>\r\n                            </div>\r\n                        </nav>\r\n");

            
            #line 334 "..\..\Views\Widgets\MyMenuWidget.cshtml"
                    }
                }
            }

        }
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .navbar-brand {\r\n        float: left;\r\n        height: 50px;\r\n        padd" +
"ing: 10px 15px;\r\n        line-height: 20px;\r\n    }\r\n\r\n    .navbar-default {\r\n   " +
"     background: #fff;\r\n        border: none;\r\n        border-radius: 0px;\r\n    " +
"    /*padding: 20px 10px 20px;*/\r\n        margin-bottom: 0px;\r\n        text-tran" +
"sform: capitalize;\r\n        font-size: 14px;\r\n    }\r\n\r\n        .navbar-default ." +
"navbar-nav > li {\r\n            background: #fff;\r\n        }\r\n\r\n    .navbar-nav >" +
" li > a {\r\n        line-height: 35px;\r\n    }\r\n\r\n    .navbar-default .navbar-nav " +
"> li > ul; {\r\n        background: #fff;\r\n    }\r\n\r\n    .navbar-header {\r\n        " +
"font-family: sans-serif;\r\n        font-size: 18px;\r\n        font-weight: 100;\r\n " +
"   }\r\n\r\n    navbar-default .navbar-header .navbar-brand {\r\n        color: #36363" +
"6;\r\n    }\r\n\r\n\r\n    .navbar-nav > li {\r\n        font-family: sans-serif;\r\n       " +
" font-size: 16px;\r\n        font-weight: 100;\r\n    }\r\n\r\n        .navbar-nav > li " +
"> ul > li {\r\n            font-family: sans-serif;\r\n            font-size: 14px;\r" +
"\n        }\r\n\r\n    .navbar-default .navbar-nav > li > a {\r\n        color: #363636" +
";\r\n    }\r\n\r\n    .navbar-nav > ul > li > a :hover {\r\n    }\r\n\r\n    .navbar-nav > l" +
"i > .dropdown-menu {\r\n        margin-top: 20px;\r\n        border-top-left-radius:" +
" 0;\r\n        border-top-right-radius: 0;\r\n    }\r\n\r\n    .navbar-default .navbar-b" +
"rand:focus, .navbar-default .navbar-brand:hover {\r\n        color: #4532BF;\r\n    " +
"}\r\n\r\n    .navbar-default .navbar-nav > .open > a, .navbar-default .navbar-nav > " +
".open > a:focus, .navbar-default .navbar-nav > .open > a:hover {\r\n        color:" +
" #4532BF;\r\n        background-color: #fff;\r\n    }\r\n\r\n    .navbar-default .navbar" +
"-nav > li > a:focus, .navbar-default .navbar-nav > li > a:hover {\r\n        color" +
": #4532BF;\r\n        background-color: #fff;\r\n    }\r\n\r\n    .dropdown-menu .divide" +
"r {\r\n        margin: 0px;\r\n    }\r\n\r\n    .dropdown-menu > li > a {\r\n        text-" +
"transform: capitalize;\r\n        padding: 10px;\r\n        color: #363636;\r\n       " +
" font-weight: 100;\r\n    }\r\n\r\n        .dropdown-menu > li > a:hover {\r\n          " +
"  background: #4532BF;\r\n            color: #fff;\r\n        }\r\n\r\n    .divider-colo" +
"r {\r\n        background: #4532BF;\r\n        height: 2px;\r\n    }\r\n\r\n    html {\r\n  " +
"      overflow-y: scroll;\r\n    }\r\n\r\n    .navbar-default .navbar-toggle .icon-bar" +
" {\r\n        background-color: black;\r\n    }\r\n\r\n\r\n\r\n    .navbar-default .navbar-t" +
"oggle {\r\n        border-color: #4532BF;\r\n    }\r\n\r\n    .navbar-default .navbar-to" +
"ggle {\r\n        background-color: #fff;\r\n    }\r\n\r\n        .navbar-default .navba" +
"r-toggle:focus, .navbar-default .navbar-toggle:hover {\r\n            background-c" +
"olor: #4532BF;\r\n        }\r\n\r\n    ");

WriteLiteral("@media (max-width:767px) {\r\n        .navbar-default .navbar-nav .open .dropdown-m" +
"enu > li > a:focus, .navbar-default .navbar-nav .open .dropdown-menu > li > a:ho" +
"ver {\r\n            color: #fff;\r\n            background-color: #4532BF;\r\n       " +
" }\r\n\r\n        .navbar-default .navbar-brand:focus, .navbar-default .navbar-brand" +
":hover {\r\n            color: #4532BF;\r\n        }\r\n\r\n        .navbar-default .nav" +
"bar-nav .open .dropdown-menu > li > a {\r\n            color: #363636;\r\n        }\r" +
"\n\r\n        .navbar-brand {\r\n            float: left;\r\n            height: 50px;\r" +
"\n            padding: 11px 15px;\r\n            line-height: 20px;\r\n        }\r\n\r\n " +
"       .navbar-default {\r\n            background: #fff;\r\n            border: non" +
"e;\r\n            border-radius: 0px;\r\n            padding: 20px 10px 20px;\r\n     " +
"       margin-bottom: 0px;\r\n            text-transform: capitalize;\r\n           " +
" font-size: 14px;\r\n        }\r\n\r\n            .navbar-default .navbar-nav > li {\r\n" +
"                background: #fff;\r\n            }\r\n\r\n                .navbar-defa" +
"ult .navbar-nav > li > ul {\r\n                    background: #fff;\r\n            " +
"    }\r\n\r\n\r\n\r\n        .navbar-header {\r\n            font-family: sans-serif;\r\n   " +
"         font-size: 18px;\r\n            font-weight: 100;\r\n        }\r\n\r\n        n" +
"avbar-default .navbar-header .navbar-brand {\r\n            color: #363636;\r\n     " +
"   }\r\n\r\n\r\n        .navbar-nav > li {\r\n            font-family: sans-serif;\r\n    " +
"        font-size: 16px;\r\n            font-weight: 100;\r\n        }\r\n\r\n          " +
"  .navbar-nav > li > ul > li {\r\n                font-family: sans-serif;\r\n      " +
"          font-size: 14px;\r\n            }\r\n\r\n        .navbar-default .navbar-nav" +
" > li > a {\r\n            color: #363636;\r\n        }\r\n\r\n        .navbar-nav > li " +
"> .dropdown-menu {\r\n            margin-top: 20px;\r\n            border-top-left-r" +
"adius: 0;\r\n            border-top-right-radius: 0;\r\n        }\r\n\r\n        .navbar" +
"-default .navbar-brand:focus, .navbar-default .navbar-brand:hover {\r\n           " +
" color: #4532BF;\r\n        }\r\n\r\n        .navbar-default .navbar-nav > .open > a, " +
".navbar-default .navbar-nav > .open > a:focus, .navbar-default .navbar-nav > .op" +
"en > a:hover {\r\n            color: #4532BF;\r\n            background-color: #fff;" +
"\r\n        }\r\n\r\n        .navbar-default .navbar-nav > li > a:focus, .navbar-defau" +
"lt .navbar-nav > li > a:hover {\r\n            color: #4532BF;\r\n            backgr" +
"ound-color: #fff;\r\n        }\r\n\r\n        .dropdown-menu .divider {\r\n            m" +
"argin: 0px;\r\n        }\r\n\r\n        .dropdown-menu > li > a {\r\n            text-tr" +
"ansform: capitalize;\r\n            padding: 10px;\r\n            color: #363636;\r\n " +
"           font-weight: 100;\r\n        }\r\n\r\n            .dropdown-menu > li > a:h" +
"over {\r\n                background: #4532BF;\r\n                color: #fff;\r\n    " +
"        }\r\n\r\n        .divider-color {\r\n            background: #4532BF;\r\n       " +
"     height: 2px;\r\n        }\r\n\r\n        html {\r\n            overflow-y: scroll;\r" +
"\n        }\r\n\r\n        .navbar-default .navbar-toggle .icon-bar {\r\n            ba" +
"ckground-color: black;\r\n        }\r\n\r\n\r\n        .navbar-default .navbar-toggle {\r" +
"\n            border-color: #4532BF;\r\n        }\r\n\r\n        .navbar-default .navba" +
"r-toggle {\r\n            background-color: #fff;\r\n        }\r\n\r\n            .navba" +
"r-default .navbar-toggle:focus, .navbar-default .navbar-toggle:hover {\r\n        " +
"        background-color: #4532BF;\r\n            }\r\n    }\r\n</style>\r\n");

        }
    }
}
#pragma warning restore 1591
