#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\MyNewWidget.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/MyNewWidget.cshtml")]
    public partial class _Views_Widgets_MyNewWidget_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_MyNewWidget_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 4 "..\..\Views\Widgets\MyNewWidget.cshtml"
 if (Model != null)
{


            
            #line default
            #line hidden
WriteLiteral("    <h2>");

            
            #line 7 "..\..\Views\Widgets\MyNewWidget.cshtml"
   Write(Model.Widget.Name);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 8 "..\..\Views\Widgets\MyNewWidget.cshtml"
    var divcount = "";
    var text = "";
   
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Widgets\MyNewWidget.cshtml"
     if (Model != null && Model.Options != null)
    {

        divcount = Model.Options[0].Value;
        text = Model.Options[1].Value;
        

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 19 "..\..\Views\Widgets\MyNewWidget.cshtml"
                
            
            #line default
            #line hidden
            
            #line 19 "..\..\Views\Widgets\MyNewWidget.cshtml"
                 for (var count = 0; count < Convert.ToInt32(divcount); count++)
                {


            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(" style=\"background-color:lavender;margin:20px;\"");

WriteLiteral(">\r\n                        <img");

WriteLiteral(" src=\"/file/bcms-installation/content/styles/images/banner_img.jpg\"");

WriteLiteral(" style=\"height:200px;\"");

WriteLiteral(" />\r\n                        <h3>");

            
            #line 24 "..\..\Views\Widgets\MyNewWidget.cshtml"
                       Write(text);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n\r\n                    </div>\r\n");

            
            #line 27 "..\..\Views\Widgets\MyNewWidget.cshtml"

                }
            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

            
            #line 31 "..\..\Views\Widgets\MyNewWidget.cshtml"




       
      }
            
            #line default
            #line hidden
            
            #line 36 "..\..\Views\Widgets\MyNewWidget.cshtml"
       
}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
