#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/MyPortfolioWidget.cshtml")]
    public partial class _Views_Widgets_MyPortfolioWidget_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_MyPortfolioWidget_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<link");

WriteAttribute("href", Tuple.Create(" href=\"", 163), Tuple.Create("\"", 200)
, Tuple.Create(Tuple.Create("", 170), Tuple.Create<System.Object, System.Int32>(Href("~/Content/font-awesome.min.css")
, 170), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/magnific-popup.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/animate.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/imagehover.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n\r\n\r\n\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/isotope.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/Scripts/Js/magnific-popup.min.js\"");

WriteLiteral("></script>\r\n");

WriteLiteral("\r\n");

            
            #line 16 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
 if (Model != null && Model.Options != null)
{
    string myPortFolioId = "MyPortfolio";
    string[] filter;
    string[] filterGroup;
    string filterGroups = string.Empty;
    string imghvr = string.Empty;
    string filterTextColor = string.Empty;
    string filterTextColorOnClick = string.Empty;
    string filterTextFontFamily = string.Empty;
    string filterTextFontSize = string.Empty;
    string filterTextFontWeight = string.Empty;
    string searchSymbolColor = string.Empty;
    //int noofportfolio = 0;
    int noofportfolioCol = 4;
    int portfolioNo = 0;
    int portFolioWidth = 0;
    RenderWidgetViewModel.PortfolioRootObject robj = null;
    foreach (var option in Model.Options)
    {
        if (option.Key == "imagehover")
        { imghvr = option.Value; }

        if (option.Key == "filterTextColor")
        { filterTextColor = option.Value; }

        if (option.Key == "filterTextColorOnClick")
        { filterTextColorOnClick = option.Value; }

        if (option.Key == "filterTextFontFamily")
        { filterTextFontFamily = option.Value; }

        if (option.Key == "filterTextFontSize")
        { filterTextFontSize = option.Value; }

        if (option.Key == "filterTextFontWeight")
        { filterTextFontWeight = option.Value; }

        if (option.Key == "searchSymbolColor")
        { searchSymbolColor = option.Value; }
        if (option.Key == "noofportfolio")
        {
            if (Convert.ToInt32(option.Value) != 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <script>\r\n                    var noofportfolio = \'");

            
            #line 61 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                    Write(option.Value);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n                </script>\r\n");

            
            #line 63 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                portfolioNo = Convert.ToInt32(option.Value);
                //noofportfolio = 12 / Convert.ToInt32(option.Value);
                noofportfolioCol = 12 / Convert.ToInt32(option.Value);
            }
        }
        if (option.Key == "width")
        {

            
            #line default
            #line hidden
WriteLiteral("            <script>\r\n                var width = \'");

            
            #line 71 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                        Write(option.Value);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            </script>\r\n");

            
            #line 73 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
            portFolioWidth = int.Parse(@option.Value);
        }
        if (option.Key == "jsonFile")
        {
            robj = RenderWidgetViewModel.jsSerial.Deserialize<RenderWidgetViewModel.PortfolioRootObject>(option.Value);
        }
    }
    if (robj != null)
    {
        string guid = Guid.NewGuid().ToString();
        myPortFolioId = "MyPortfolio" + guid;
        //if (noofportfolio < 1 && noofportfolio > 12)
        //{
        //    noofportfolio = 4;
        //}
        //if (noofportfolioCol < 1 && noofportfolioCol > 12)
        if (noofportfolioCol < 1 || noofportfolioCol > 12)
        {
            noofportfolioCol = 4;
        }
        if (robj.portfolioFilters != null && robj.portfolioFilters.Count > 0)
        {
            foreach (var options in robj.portfolioFilters)
            {
                filter = options.filter.Split(',');

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteAttribute("id", Tuple.Create(" id=\"", 3659), Tuple.Create("\"", 3678)
            
            #line 98 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
, Tuple.Create(Tuple.Create("", 3664), Tuple.Create<System.Object, System.Int32>(myPortFolioId
            
            #line default
            #line hidden
, 3664), false)
);

WriteLiteral(">\r\n                    <section");

WriteLiteral(" class=\"portfolio section-padding\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"portfolioFilter text-center\"");

WriteLiteral(">\r\n                                        ");

WriteLiteral("\r\n                                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" id=\"all-categories\"");

WriteLiteral(" data-filter=\"*\"");

WriteLiteral(" class=\"current changecolor\"");

WriteAttribute("style", Tuple.Create(" style=\"", 4392), Tuple.Create("\"", 4524)
, Tuple.Create(Tuple.Create("", 4400), Tuple.Create("color:", 4400), true)
            
            #line 105 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                                 , Tuple.Create(Tuple.Create("", 4406), Tuple.Create<System.Object, System.Int32>(filterTextColor
            
            #line default
            #line hidden
, 4406), false)
, Tuple.Create(Tuple.Create("", 4422), Tuple.Create(";", 4422), true)
, Tuple.Create(Tuple.Create(" ", 4423), Tuple.Create("font-family:", 4424), true)
            
            #line 105 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                                                               , Tuple.Create(Tuple.Create("", 4436), Tuple.Create<System.Object, System.Int32>(filterTextFontFamily
            
            #line default
            #line hidden
, 4436), false)
, Tuple.Create(Tuple.Create("", 4457), Tuple.Create(";", 4457), true)
, Tuple.Create(Tuple.Create(" ", 4458), Tuple.Create("font-size:", 4459), true)
            
            #line 105 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                                                                                                , Tuple.Create(Tuple.Create("", 4469), Tuple.Create<System.Object, System.Int32>(filterTextFontSize
            
            #line default
            #line hidden
, 4469), false)
, Tuple.Create(Tuple.Create("", 4488), Tuple.Create(";", 4488), true)
, Tuple.Create(Tuple.Create(" ", 4489), Tuple.Create("font-weight:", 4490), true)
            
            #line 105 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                                                                                                                                 , Tuple.Create(Tuple.Create("", 4502), Tuple.Create<System.Object, System.Int32>(filterTextFontWeight
            
            #line default
            #line hidden
, 4502), false)
, Tuple.Create(Tuple.Create("", 4523), Tuple.Create(";", 4523), true)
);

WriteLiteral(">All Categories</a>\r\n\r\n");

            
            #line 107 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 107 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                         for (int i = 0; i <= filter.Length - 1; i++)
                                    {
                                        
            
            #line default
            #line hidden
            
            #line 109 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                                                                                                                                                                                                                                                                            

            
            #line default
            #line hidden
WriteLiteral("                                        <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-filter=\".");

            
            #line 110 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                                             Write(filter[i].ToLower());

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteAttribute("style", Tuple.Create(" style=\"", 5047), Tuple.Create("\"", 5179)
, Tuple.Create(Tuple.Create("", 5055), Tuple.Create("color:", 5055), true)
            
            #line 110 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                     , Tuple.Create(Tuple.Create("", 5061), Tuple.Create<System.Object, System.Int32>(filterTextColor
            
            #line default
            #line hidden
, 5061), false)
, Tuple.Create(Tuple.Create("", 5077), Tuple.Create(";", 5077), true)
, Tuple.Create(Tuple.Create(" ", 5078), Tuple.Create("font-family:", 5079), true)
            
            #line 110 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                                   , Tuple.Create(Tuple.Create("", 5091), Tuple.Create<System.Object, System.Int32>(filterTextFontFamily
            
            #line default
            #line hidden
, 5091), false)
, Tuple.Create(Tuple.Create("", 5112), Tuple.Create(";", 5112), true)
, Tuple.Create(Tuple.Create(" ", 5113), Tuple.Create("font-size:", 5114), true)
            
            #line 110 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                                                                    , Tuple.Create(Tuple.Create("", 5124), Tuple.Create<System.Object, System.Int32>(filterTextFontSize
            
            #line default
            #line hidden
, 5124), false)
, Tuple.Create(Tuple.Create("", 5143), Tuple.Create(";", 5143), true)
, Tuple.Create(Tuple.Create(" ", 5144), Tuple.Create("font-weight:", 5145), true)
            
            #line 110 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                                                                                                     , Tuple.Create(Tuple.Create("", 5157), Tuple.Create<System.Object, System.Int32>(filterTextFontWeight
            
            #line default
            #line hidden
, 5157), false)
, Tuple.Create(Tuple.Create("", 5178), Tuple.Create(";", 5178), true)
);

WriteLiteral(" class=\"changecolor\"");

WriteLiteral(">");

            
            #line 110 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                                                                                                                                                                                                                            Write(filter[i]);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 111 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    </div>\r\n                                    <" +
"div");

WriteLiteral(" class=\"portfolioContainer isotope\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n");

            
            #line 114 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                        
            
            #line default
            #line hidden
            
            #line 114 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                         if (robj.Images != null & robj.Images.Count > 0)
                                    {
                                        foreach (var innerOpt in robj.Images)
                                        {
                                            filterGroup = innerOpt.group.Split(',');
                                            for (int j = 0; j <= filterGroup.Length - 1; j++)
                                            {
                                                filterGroups = filterGroups + " " + filterGroup[j];
                                            }
                                        
            
            #line default
            #line hidden
            
            #line 123 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                                                                                                                       

            
            #line default
            #line hidden
WriteLiteral("                                        <div");

WriteAttribute("class", Tuple.Create(" class=\"", 6213), Tuple.Create("\"", 6301)
, Tuple.Create(Tuple.Create("", 6221), Tuple.Create("col-lg-", 6221), true)
            
            #line 124 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
, Tuple.Create(Tuple.Create("", 6228), Tuple.Create<System.Object, System.Int32>(noofportfolioCol
            
            #line default
            #line hidden
, 6228), false)
, Tuple.Create(Tuple.Create(" ", 6245), Tuple.Create("col-md-6", 6246), true)
, Tuple.Create(Tuple.Create(" ", 6254), Tuple.Create("col-sm-12", 6255), true)
, Tuple.Create(Tuple.Create(" ", 6264), Tuple.Create("col-xs-12", 6265), true)
            
            #line 124 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                         , Tuple.Create(Tuple.Create(" ", 6274), Tuple.Create<System.Object, System.Int32>(filterGroups
            
            #line default
            #line hidden
, 6275), false)
, Tuple.Create(Tuple.Create(" ", 6288), Tuple.Create("isotope-item", 6289), true)
);

WriteLiteral(">\r\n                                            <figure");

WriteAttribute("class", Tuple.Create(" class=\"", 6356), Tuple.Create("\"", 6378)
            
            #line 125 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
, Tuple.Create(Tuple.Create("", 6364), Tuple.Create<System.Object, System.Int32>(imghvr
            
            #line default
            #line hidden
, 6364), false)
, Tuple.Create(Tuple.Create(" ", 6371), Tuple.Create("imghvr", 6372), true)
);

WriteLiteral(" style=\"position:relative;\"");

WriteLiteral(">\r\n                                                <img");

WriteAttribute("src", Tuple.Create(" src=\"", 6461), Tuple.Create("\"", 6482)
            
            #line 126 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
, Tuple.Create(Tuple.Create("", 6467), Tuple.Create<System.Object, System.Int32>(innerOpt.image
            
            #line default
            #line hidden
, 6467), false)
);

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(" />\r\n                                                <a");

WriteLiteral(" class=\"magnific-popup anchorsearch\"");

WriteAttribute("href", Tuple.Create(" href=\"", 6600), Tuple.Create("\"", 6622)
            
            #line 127 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
             , Tuple.Create(Tuple.Create("", 6607), Tuple.Create<System.Object, System.Int32>(innerOpt.image
            
            #line default
            #line hidden
, 6607), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 6623), Tuple.Create("\"", 6656)
, Tuple.Create(Tuple.Create("", 6631), Tuple.Create("color:", 6631), true)
            
            #line 127 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                           , Tuple.Create(Tuple.Create("", 6637), Tuple.Create<System.Object, System.Int32>(searchSymbolColor
            
            #line default
            #line hidden
, 6637), false)
, Tuple.Create(Tuple.Create("", 6655), Tuple.Create(";", 6655), true)
);

WriteLiteral(">\r\n                                                    <i");

WriteLiteral(" class=\"fa fa-search fa-3x search_icon\"");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">\r\n                                                    </i>\r\n                    " +
"                            </a>\r\n                                            </" +
"figure>\r\n                                        </div>\r\n");

            
            #line 133 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                            filterGroups = string.Empty;
                                        }
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    </div>\r\n                                </div" +
">\r\n                            </div>\r\n                        </div>\r\n         " +
"               <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"hidtext\"");

WriteLiteral(" id=\"hidtext\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7381), Tuple.Create("\"", 7412)
            
            #line 140 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
, Tuple.Create(Tuple.Create("", 7389), Tuple.Create<System.Object, System.Int32>(filterTextColorOnClick
            
            #line default
            #line hidden
, 7389), false)
);

WriteLiteral(" />\r\n                        <input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" name=\"hidtext1\"");

WriteLiteral(" id=\"hidtext1\"");

WriteAttribute("value", Tuple.Create(" value=\"", 7492), Tuple.Create("\"", 7516)
            
            #line 141 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
  , Tuple.Create(Tuple.Create("", 7500), Tuple.Create<System.Object, System.Int32>(filterTextColor
            
            #line default
            #line hidden
, 7500), false)
);

WriteLiteral(" />\r\n                    </section>\r\n                </div>\r\n");

            
            #line 144 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
            }
        }
    }

            
            #line default
            #line hidden
WriteLiteral("    <script>\r\n        \r\n        ");

WriteLiteral("\r\n        \r\n\r\n        (function ($) {\r\n            \"use strict\";\r\n\r\n            j" +
"Query(document).ready(function ($) {\r\n\r\n                //Portfolio Popup\r\n     " +
"           $(\'#");

            
            #line 185 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
               Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral("  .magnific-popup\').magnificPopup({ type: \'image\' });\r\n            });\r\n\r\n\r\n     " +
"       jQuery(window).load(function () {\r\n\r\n                //Portfolio containe" +
"r\r\n                var $container = $(\'#");

            
            #line 192 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(@"  .portfolioContainer');
                $container.isotope({
                    filter: '*',
                    animationOptions: {
                        duration: 750,
                        easing: 'linear',
                        queue: false
                    }
                });

                $('#");

            
            #line 202 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
               Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral("  .portfolioFilter a\').on(\'click\', function () {\r\n                    $(\'#");

            
            #line 203 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                   Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(@"  .portfolioFilter a').removeClass('current');
                    $(this).addClass('current');
                    var textcolor = document.getElementById('hidtext1').value;
                    var textcoloronclick = document.getElementById('hidtext').value;
                    $('#");

            
            #line 207 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                   Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(@" .portfolioFilter a').css({ 'color': textcolor });
                    $(this).css({ 'color': textcoloronclick });

                    var selector = $(this).attr('data-filter');
                    $container.isotope({
                        filter: selector,
                        animationOptions: {
                            duration: 750,
                            easing: 'linear',
                            queue: false
                        }
                    });
                    return false;
                });
            });

        }(jQuery));
    </script>
");

WriteLiteral("    <script>\r\n        var portfoliowidth = 0;\r\n        $(document).ready(function" +
" () {\r\n            var textcolor = document.getElementById(\'hidtext1\').value;\r\n " +
"           var textcoloronclick = document.getElementById(\'hidtext\').value;\r\n   " +
"         $(\'#");

            
            #line 230 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
           Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(" .portfolioFilter a\').css({ \'color\': textcolor });\r\n            $(\'#");

            
            #line 231 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
           Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(@" .portfolioFilter a#all-categories').css({ 'color': textcoloronclick });

            //if (typeof noofportfolio != 'undefined') {
            //    var totalwidth = parseInt($('.page-block').width());
            //    if (typeof width != 'undefined') {
            //        totalwidth = parseInt(width);
            //    }
            //    var itemwidth = Math.ceil((totalwidth - 30) / parseInt(noofportfolio));
            //    portfoliowidth = itemwidth;
            //    var viewportwidth = $('.page-block').width();
            //    if (viewportwidth < totalwidth)
            //        totalwidth = parseInt(viewportwidth);
            //    var percent = Math.ceil((totalwidth) * 100 / parseInt(viewportwidth));
            //    $('.portfolio .row:first').css({ 'width': percent + '%', 'margin': 'auto' });
            //    $('.portfolioContainer .isotope-item').each(function () {
            //        $(this).css('width', itemwidth + 'px');
            //    });
            //}

            //setSize();
            var portfolioNo = 3;
            //if (typeof noofportfolio != 'undefined') {
            if (");

            
            #line 253 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
           Write(portfolioNo);

            
            #line default
            #line hidden
WriteLiteral(" != 0) {\r\n                //portfolioNo = noofportfolio;\r\n                portfol" +
"ioNo = ");

            
            #line 255 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                         Write(portfolioNo);

            
            #line default
            #line hidden
WriteLiteral(";\r\n                if (noofportfolio < 1 || noofportfolio > 12)\r\n                " +
"    portfolioNo = 3;\r\n            }\r\n            var totalwidth = parseInt($(\'.c" +
"ontainer\').width());\r\n            //if (typeof width != \'undefined\') {\r\n        " +
"    if (");

            
            #line 261 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
           Write(portFolioWidth);

            
            #line default
            #line hidden
WriteLiteral(" != 0) {\r\n                //totalwidth = parseInt(width);\r\n                totalw" +
"idth = parseInt(");

            
            #line 263 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                 Write(portFolioWidth);

            
            #line default
            #line hidden
WriteLiteral(");\r\n            }\r\n            var itemwidth = Math.ceil((totalwidth - 30) / pars" +
"eInt(portfolioNo));\r\n            portfoliowidth = itemwidth;\r\n            var pe" +
"rcent = Math.ceil((totalwidth) * 100 / parseInt(totalwidth));\r\n            //$(\'" +
"#");

            
            #line 268 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
             Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(" .portfolio .row:first\').css({ \'width\': percent + \'%\', \'margin\': \'auto\' });\r\n    " +
"        $(\'#");

            
            #line 269 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
           Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(" .portfolio .row:first\').css({ \'width\': totalwidth + \'px\', \'margin\': \'auto\' });\r\n" +
"            $(\'#");

            
            #line 270 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
           Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(" .portfolioContainer .isotope-item\').each(function () {\r\n                $(this)." +
"css(\'width\', itemwidth + \'px\');\r\n            });\r\n\r\n            $(\'#");

            
            #line 274 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
           Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(" .portfolioFilter\').css({ \'width\': totalwidth + \'px\', \'margin\': \'auto\' });\r\n     " +
"       $(\'#");

            
            #line 275 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
           Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(" .portfolioContainer\').css({ \'width\': totalwidth + \'px\', \'margin\': \'auto\' });\r\n\r\n" +
"        });\r\n\r\n        $(window).resize(function () {\r\n            var fullwidth" +
" = parseInt($(\'#");

            
            #line 280 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                    Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(" .portfolio .row\').eq(0).width());\r\n            var itemwidth = parseInt($(\'#");

            
            #line 281 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                    Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(@" .portfolioContainer .isotope-item:first').width());
            //console.log('full width: ' + parseInt($('.portfolio .row').eq(0).width()));
            //console.log('item width: ' + parseInt($('.portfolioContainer .isotope-item:first').width()));
            //if (parseInt($('.portfolio .row:first').width()) < parseInt(portfoliowidth) * 2) {
            if (parseInt($('#");

            
            #line 285 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                        Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(" .portfolio .row:first\').width()) < parseInt(itemwidth) * 2) {\r\n                $" +
"(\'#");

            
            #line 286 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
               Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(" .portfolioContainer .isotope-item\').css(\'width\', \'100%\');\r\n            }\r\n      " +
"      else {\r\n                //$(\'.portfolioContainer .isotope-item\').css(\'widt" +
"h\', portfoliowidth + \'px\');\r\n                $(\'#");

            
            #line 290 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
               Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(" .portfolioContainer .isotope-item\').css(\'width\', itemwidth + \'px\');\r\n           " +
" }\r\n\r\n            //setSize();\r\n            var portfolioNo = 3;\r\n            //" +
"if (typeof noofportfolio != \'undefined\') {\r\n            if (");

            
            #line 296 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
           Write(portfolioNo);

            
            #line default
            #line hidden
WriteLiteral(" != 0) {\r\n                //portfolioNo = noofportfolio;\r\n                portfol" +
"ioNo = ");

            
            #line 298 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                         Write(portfolioNo);

            
            #line default
            #line hidden
WriteLiteral(";\r\n                if (noofportfolio < 1 || noofportfolio > 12)\r\n                " +
"    portfolioNo = 3;\r\n            }\r\n            var totalwidth = parseInt($(\'.c" +
"ontainer\').width());\r\n            //if (typeof width != \'undefined\') {\r\n        " +
"    if (");

            
            #line 304 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
           Write(portFolioWidth);

            
            #line default
            #line hidden
WriteLiteral(" != 0) {\r\n                //totalwidth = parseInt(width);\r\n                totalw" +
"idth = parseInt(");

            
            #line 306 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
                                 Write(portFolioWidth);

            
            #line default
            #line hidden
WriteLiteral(");\r\n            }\r\n            var itemwidth = Math.ceil((totalwidth - 30) / pars" +
"eInt(portfolioNo));\r\n            portfoliowidth = itemwidth;\r\n            var pe" +
"rcent = Math.ceil((totalwidth) * 100 / parseInt(totalwidth));\r\n            //$(\'" +
"#");

            
            #line 311 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
             Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(" .portfolio .row:first\').css({ \'width\': percent + \'%\', \'margin\': \'auto\' });\r\n    " +
"        $(\'#");

            
            #line 312 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
           Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(" .portfolio .row:first\').css({ \'width\': totalwidth + \'px\', \'margin\': \'auto\' });\r\n" +
"            $(\'#");

            
            #line 313 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
           Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(" .portfolioContainer .isotope-item\').each(function () {\r\n                $(this)." +
"css(\'width\', itemwidth + \'px\');\r\n            });\r\n\r\n            $(\'#");

            
            #line 317 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
           Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(" .portfolioFilter\').css({ \'width\': totalwidth + \'px\', \'margin\': \'auto\' });\r\n     " +
"       $(\'#");

            
            #line 318 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
           Write(myPortFolioId);

            
            #line default
            #line hidden
WriteLiteral(@" .portfolioContainer').css({ 'width': totalwidth + 'px', 'margin': 'auto' });
        });
        //function colorchange() {
        //    $('.portfolioFilter  a').click(function () {
        //        var textcolor = document.getElementById('hidtext1').value;
        //        var textcoloronclick = document.getElementById('hidtext').value;
        //        $('.portfolioFilter a').css({ 'color': textcolor });
        //        $(this).css({ 'color': textcoloronclick });
        //    });
        //}

    </script>
");

            
            #line 330 "..\..\Views\Widgets\MyPortfolioWidget.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n<style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n    .portfolioFilter {\r\n        margin: 0px 0px 10px 0px;\r\n        overflow: h" +
"idden;\r\n        padding: 15px 10px;\r\n    }\r\n\r\n        .portfolioFilter a {\r\n    " +
"        text-decoration: none;\r\n            /*margin: 15px 5px 15px 5px;*/\r\n    " +
"        padding: 10px 15px;\r\n            display: inline-block;\r\n            fon" +
"t-weight: 700;\r\n            text-transform: uppercase;\r\n            color: #3636" +
"36;\r\n            font-family: sans-serif;\r\n            font-size: 20px;\r\n       " +
" }\r\n\r\n    /*.portfolioFilter a.current {\r\n                color: #4532BF;\r\n     " +
"           font-weight: 700;\r\n            }*/\r\n\r\n\r\n\r\n    .portfolioContainer a i" +
"mg {\r\n        margin: 15px auto;\r\n        width: 100%;\r\n        height: 100%;\r\n " +
"   }\r\n\r\n    .portfolioContainer1 a img {\r\n        /*margin:15px auto;*/\r\n       " +
" margin: 0px auto;\r\n        width: 100%;\r\n        height: 100%;\r\n    }\r\n\r\n    .i" +
"sotope-item {\r\n        z-index: 2;\r\n    }\r\n\r\n    .isotope-item {\r\n        text-a" +
"lign: center;\r\n    }\r\n\r\n\r\n\r\n    .isotope-hidden.isotope-item {\r\n        pointer-" +
"events: none;\r\n        z-index: 1;\r\n    }\r\n\r\n    .isotope, .isotope .isotope-ite" +
"m {\r\n        /* change duration value to whatever you like */\r\n        -webkit-t" +
"ransition-duration: 0.8s;\r\n        -moz-transition-duration: 0.8s;\r\n        tran" +
"sition-duration: 0.8s;\r\n    }\r\n\r\n    .isotope {\r\n        -webkit-transition-prop" +
"erty: height, width;\r\n        -moz-transition-property: height, width;\r\n        " +
"transition-property: height, width;\r\n    }\r\n\r\n        .isotope .isotope-item {\r\n" +
"            -webkit-transition-property: -webkit-transform, opacity;\r\n          " +
"  -moz-transition-property: -moz-transform, opacity;\r\n            transition-pro" +
"perty: transform, opacity;\r\n        }\r\n\r\n    .portfolioContainer .imghvr {\r\n    " +
"    margin-bottom: 30px;\r\n        background-color: #4532BF;\r\n    }\r\n\r\n\r\n\r\n    ." +
"isotope-item a {\r\n        /*position: absolute;*/\r\n        text-align: center;\r\n" +
"        /*padding: 29%;*/\r\n        visibility: hidden;\r\n        color: #fff;\r\n  " +
"  }\r\n\r\n    .isotope-item:hover a {\r\n        visibility: visible;\r\n        text-d" +
"ecoration: none;\r\n    }\r\n\r\n    .isotope-item i {\r\n        position: relative;\r\n " +
"       top: calc(50% - 20px);\r\n    }\r\n</style>");

        }
    }
}
#pragma warning restore 1591
