#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Widgets\Myths.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Widgets\Myths.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/Myths.cshtml")]
    public partial class _Views_Widgets_Myths_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_Myths_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/bootstrap.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/colors.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/css/style.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(@" />

<style>
    .col-xs-1, .col-sm-1, .col-md-1, .col-lg-1, .col-xs-2, .col-sm-2, .col-md-2, .col-lg-2, .col-xs-3, .col-sm-3, .col-md-3, .col-lg-3,
.col-xs-4, .col-sm-4, .col-md-4, .col-lg-4, .col-xs-5, .col-sm-5, .col-md-5, .col-lg-5, .col-xs-6, .col-sm-6, .col-md-6, .col-lg-6, 
.col-xs-7, .col-sm-7, .col-md-7, .col-lg-7, .col-xs-8, .col-sm-8, .col-md-8, .col-lg-8, .col-xs-9, .col-sm-9, .col-md-9, .col-lg-9, 
.col-xs-10, .col-sm-10, .col-md-10, .col-lg-10, .col-xs-11, .col-sm-11, .col-md-11, .col-lg-11, .col-xs-12, .col-sm-12, .col-md-12, 
.col-lg-12 {
  padding-right: 0px!important;
  padding-left: 0px!important;
}

</style>


");

            
            #line 22 "..\..\Views\Widgets\Myths.cshtml"
 if (Model != null && Model.Options != null)
{
    string guid = Guid.NewGuid().ToString();
    string objId = "myths-accordion" + guid;
    string leftImageUrl = null;
    string bgSize = null, leftContent = null, optionalRightContent = null, titleText=null;
    RenderWidgetViewModel.AccordionRootObject robj = null;
    string paddingBottom = null, buttonMargin = null, fontcolor = null, buttonCaption = null;
    foreach (var options in Model.Options)
    {
        if (options.Key == "leftImageUrl")
        {
            leftImageUrl = options.Value;
        }
        else if (options.Key == "bgSize")
        {
            bgSize = options.Value;
        }
        else if (options.Key == "paddingBottom")
        {
            paddingBottom = options.Value;
        }
        else if (options.Key == "fontcolor")
        {
            fontcolor = options.Value;
        }
        else if (options.Key == "buttonMargin")
        {
            buttonMargin = @options.Value;
        }
        else if (options.Key == "buttonCaption")
        {
            buttonCaption = @options.Value;
        }
        else if (options.Key == "leftContent")
        {
            leftContent = @options.Value;
        }
        else if (options.Key == "optionalRightContent")
        {
            optionalRightContent = @options.Value;
        }
        else if (options.Key == "titleText")
        {
            titleText = @options.Value;
        }
        else if (options.Key == "json")
        {
            robj = RenderWidgetViewModel.jsSerial.Deserialize<RenderWidgetViewModel.AccordionRootObject>(options.Value);
        }
    }





            
            #line default
            #line hidden
WriteLiteral("<!DOCTYPE html>\r\n");

WriteLiteral("<html>\r\n<head>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title></title>\r\n</head>\r\n<body>\r\n    <div>\r\n        <section");

WriteLiteral(" class=\"section-whitenopadding\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"clearfix\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-6 col-md-6 col-sm-6 col-xs-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" data-effect=\"slide-right\"");

WriteLiteral("><img");

WriteLiteral(" alt=\"Web Design Service\"");

WriteAttribute("src", Tuple.Create(" src=\"", 3137), Tuple.Create("\"", 3156)
            
            #line 88 "..\..\Views\Widgets\Myths.cshtml"
      , Tuple.Create(Tuple.Create("", 3143), Tuple.Create<System.Object, System.Int32>(leftImageUrl
            
            #line default
            #line hidden
, 3143), false)
);

WriteLiteral("></div>\r\n\r\n\r\n                </div><!-- end col-lg-6 -->\r\n                <div");

WriteLiteral(" class=\"col-lg-6 col-md-6 col-sm-6 col-xs-12\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"about_widget\"");

WriteLiteral(" data-effect=\"slide-left\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 94 "..\..\Views\Widgets\Myths.cshtml"
               Write(Html.Raw(@titleText));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        ");

WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"panel-group\"");

WriteAttribute("id", Tuple.Create(" id=\"", 3848), Tuple.Create("\"", 3859)
            
            #line 101 "..\..\Views\Widgets\Myths.cshtml"
, Tuple.Create(Tuple.Create("", 3853), Tuple.Create<System.Object, System.Int32>(objId
            
            #line default
            #line hidden
, 3853), false)
);

WriteLiteral(" style=\"width:85%;\"");

WriteLiteral(">\r\n\r\n                            ");

WriteLiteral("\r\n");

            
            #line 125 "..\..\Views\Widgets\Myths.cshtml"
 if (robj != null)
{
    if (robj.accordiondata != null && robj.accordiondata.Count > 0)
    {
                            var i = 0;
                            
            
            #line default
            #line hidden
            
            #line 130 "..\..\Views\Widgets\Myths.cshtml"
                             foreach (var opt in robj.accordiondata)
                            {
                                if (i == 0)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <button");

WriteLiteral(" class=\"accordion active\"");

WriteLiteral(">");

            
            #line 134 "..\..\Views\Widgets\Myths.cshtml"
                                                                Write(opt.heading);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

WriteLiteral("                                    <div");

WriteLiteral(" class=\"panel\"");

WriteLiteral(" style=\"display:block;\"");

WriteLiteral(">\r\n                                        <p><span");

WriteLiteral(" class=\"bblue\"");

WriteLiteral(">Fact:</span>  ");

            
            #line 136 "..\..\Views\Widgets\Myths.cshtml"
                                                                        Write(opt.content);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                    </div>\r\n");

            
            #line 138 "..\..\Views\Widgets\Myths.cshtml"

                                    i++;
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <button");

WriteLiteral(" class=\"accordion\"");

WriteLiteral(">");

            
            #line 143 "..\..\Views\Widgets\Myths.cshtml"
                                                         Write(opt.heading);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

WriteLiteral("                                    <div");

WriteLiteral(" class=\"panel\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">\r\n                                        <p><span");

WriteLiteral(" class=\"bblue\"");

WriteLiteral(">Fact:</span>  ");

            
            #line 145 "..\..\Views\Widgets\Myths.cshtml"
                                                                        Write(opt.content);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                    </div>\r\n");

            
            #line 147 "..\..\Views\Widgets\Myths.cshtml"
                                }
                            }
            
            #line default
            #line hidden
            
            #line 148 "..\..\Views\Widgets\Myths.cshtml"
                             
    }
}

            
            #line default
            #line hidden
WriteLiteral("                            <!-- end panel -->\r\n                        </div><!-" +
"- panel-group -->\r\n");

WriteLiteral("                        ");

            
            #line 153 "..\..\Views\Widgets\Myths.cshtml"
                   Write(Html.Raw(@optionalRightContent));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div><!-- end about widget -->\r\n                </div><!--" +
" end col-lg-6 -->\r\n\r\n            </div><!-- general -->\r\n        </section><!-- " +
"end section-whitebg -->\r\n    </div>\r\n    <script>\r\n        var acc = document.ge" +
"tElementById(\"");

            
            #line 161 "..\..\Views\Widgets\Myths.cshtml"
                                      Write(objId);

            
            #line default
            #line hidden
WriteLiteral("\").getElementsByClassName(\"accordion\");\r\n        var i;\r\n\r\n        for (i = 0; i " +
"< acc.length; i++) {\r\n\r\n            acc[i].onclick = function () {              " +
"  \r\n                $(\'#");

            
            #line 167 "..\..\Views\Widgets\Myths.cshtml"
               Write(objId);

            
            #line default
            #line hidden
WriteLiteral(@" .accordion.active').not(this).removeClass('active').next().css('display', 'none');
                this.classList.toggle(""active"");
                var panel = this.nextElementSibling;
                if (panel.style.display === ""block"") {
                    panel.style.display = ""none"";
                } else {
                    panel.style.display = ""block"";
                }

                
               
            }
            
        }
    </script>
</body>
</html>
");

            
            #line 184 "..\..\Views\Widgets\Myths.cshtml"

}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
