#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\NewWidget.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/NewWidget.cshtml")]
    public partial class _Views_Widgets_NewWidget_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_NewWidget_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral(@"<style>
    .gutter-10.row {
        margin-right: -5px;
        margin-left: -5px;
        background-color:red;
    }

    .gutter-10 > [class^=""col-""], .gutter-10 > [class^="" col-""] {
        padding-right: 5px;
        padding-left: 5px;
        background-color:red;
    }
</style>

");

WriteLiteral("\r\n");

            
            #line 19 "..\..\Views\Widgets\NewWidget.cshtml"
 if (Model != null)
{


            
            #line default
            #line hidden
WriteLiteral("    <h2>");

            
            #line 22 "..\..\Views\Widgets\NewWidget.cshtml"
   Write(Model.Widget.Name);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n");

            
            #line 23 "..\..\Views\Widgets\NewWidget.cshtml"
    var divcount = "";
    var text = "";
   
     
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Widgets\NewWidget.cshtml"
      if (Model.Options != null)
     {
         divcount = Model.Options[0].Value;
         text = Model.Options[1].Value;
         

            
            #line default
            #line hidden
WriteLiteral("         <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row gutter-10\"");

WriteLiteral(">\r\n");

            
            #line 33 "..\..\Views\Widgets\NewWidget.cshtml"
               
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Widgets\NewWidget.cshtml"
                for (var count = 0; count < Convert.ToInt32(divcount); count++)
                      {

            
            #line default
            #line hidden
WriteLiteral("                       <div");

WriteLiteral(" class=\"myclass\"");

WriteLiteral(" style=\"background-color:lavender;border:1px solid black;\"");

WriteLiteral(" >\r\n                          <img");

WriteLiteral(" src=\"/file/bcms-installation/content/styles/images/banner_img.jpg\"");

WriteLiteral(" style=\"height:200px;width:100%;\"");

WriteLiteral(" />\r\n                          <h3>");

            
            #line 37 "..\..\Views\Widgets\NewWidget.cshtml"
                         Write(text);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n\r\n                       </div>\r\n");

            
            #line 40 "..\..\Views\Widgets\NewWidget.cshtml"
                       }
            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n            </div>\r\n         </div>\r\n");

            
            #line 44 "..\..\Views\Widgets\NewWidget.cshtml"
     }
            
            #line default
            #line hidden
            
            #line 44 "..\..\Views\Widgets\NewWidget.cshtml"
      
}

            
            #line default
            #line hidden
WriteLiteral("<script");

WriteLiteral(" src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js\"");

WriteLiteral(" type=\"\"");

WriteLiteral("></script>\r\n<script type = \"text/javascript\" >\r\n   \r\n    $(document).ready(functi" +
"on () {\r\n        \r\n       \r\n       var count = ");

            
            #line 52 "..\..\Views\Widgets\NewWidget.cshtml"
              Write(Model.Options[0].Value);

            
            #line default
            #line hidden
WriteLiteral(";        \r\n       var value = 12 / count;       \r\n        $(\".myclass\").each(func" +
"tion () {\r\n            $(this).addClass(\"col-sm-\" + value);\r\n\r\n        });\r\n    " +
"});\r\n</script>");

        }
    }
}
#pragma warning restore 1591
