#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Widgets\ParallaxSection.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/ParallaxSection.cshtml")]
    public partial class _Views_Widgets_ParallaxSection_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_ParallaxSection_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\Widgets\ParallaxSection.cshtml"
  
    ViewBag.Title = "ResponsiveSlider";

            
            #line default
            #line hidden
WriteLiteral(@"

<style>
    .parallax {
        min-height: 1000px;
        background-attachment: fixed;
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
        padding-top:15%!important;
    }
    .container {
        padding-top:10%!important;
    }
    .row {
         text-align:center!important;
     }
</style>

");

            
            #line 25 "..\..\Views\Widgets\ParallaxSection.cshtml"
 if (Model != null && Model.Options != null)
{
    foreach (var option in Model.Options)
    {
        string parallaximage = string.Empty;
        string parallaxheading = string.Empty;
        string parallaxdiv = string.Empty;

        if (@option.Key == "json")
        {
            RenderWidgetViewModel.SliderRootObject robj = null;
            robj = RenderWidgetViewModel.jsSerial.Deserialize<RenderWidgetViewModel.SliderRootObject>(@option.Value);

            if (robj != null)
            {

                if (robj.parallaximage != null && robj.parallaxdiv != null && robj.parallaxdiv.Count > 0)
                {

                    parallaximage = robj.parallaximage;
                    parallaxheading = robj.parallaxheading;

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"parallax\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1350), Tuple.Create("\"", 1405)
, Tuple.Create(Tuple.Create("", 1358), Tuple.Create("background-image:url(", 1358), true)
            
            #line 46 "..\..\Views\Widgets\ParallaxSection.cshtml"
, Tuple.Create(Tuple.Create("", 1379), Tuple.Create<System.Object, System.Int32>(parallaximage
            
            #line default
            #line hidden
, 1379), false)
, Tuple.Create(Tuple.Create("", 1393), Tuple.Create(")!important;", 1393), true)
);

WriteLiteral(">\r\n\r\n");

WriteLiteral("                        ");

            
            #line 48 "..\..\Views\Widgets\ParallaxSection.cshtml"
                   Write(Html.Raw(@parallaxheading));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 51 "..\..\Views\Widgets\ParallaxSection.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Widgets\ParallaxSection.cshtml"
                                 foreach (var obj2 in robj.parallaxdiv)
                                {


                                    
            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Widgets\ParallaxSection.cshtml"
                               Write(Html.Raw(obj2.parallaxtext));

            
            #line default
            #line hidden
            
            #line 55 "..\..\Views\Widgets\ParallaxSection.cshtml"
                                                                
                                }

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n                            </div>\r\n                        </div>\r\n\r\n       " +
"             </div>\r\n");

            
            #line 63 "..\..\Views\Widgets\ParallaxSection.cshtml"
                }
            }
        }
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
