#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\SalvattoreWidget.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Widgets\SalvattoreWidget.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/SalvattoreWidget.cshtml")]
    public partial class _Views_Widgets_SalvattoreWidget_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_SalvattoreWidget_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/Salvattore.css\"");

WriteLiteral(">\r\n\r\n<script");

WriteLiteral(" src=\"/file/bcms-installation/scripts/js/Salvattore.js\"");

WriteLiteral("></script>\r\n\r\n<div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <figure");

WriteLiteral(" class=\"intro-grid\"");

WriteLiteral(" data-columns>\r\n        <div");

WriteLiteral(" class=\"column\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"http://bettercms.sandbox.mvc4.local.net/uploads/image/b10a1151361e4f67a53b2" +
"e92959c26f3/img_app_dev_big.png?170224164237\"");

WriteLiteral(" />\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"http://bettercms.sandbox.mvc4.local.net/uploads/image/7c7e6224e8074ed192867" +
"783cc6c9a8f/content_technology.png?170224164237\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"column\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"item\"");

WriteLiteral(">\r\n                <img");

WriteLiteral(" src=\"http://bettercms.sandbox.mvc4.local.net/uploads/image/744fcc6615ed4a7bb2dc6" +
"1fc1b085d00/cybersecurity.png?170224164237\"");

WriteLiteral(" />\r\n            </div>\r\n        </div>\r\n    </figure>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
