#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\Shuffle.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Widgets\Shuffle.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/Shuffle.cshtml")]
    public partial class _Views_Widgets_Shuffle_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_Shuffle_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/ShuffleStyle.css\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/ShuffleStyle1.css\"");

WriteLiteral(">\r\n    \r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/scripts/js/Shufflejs.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/file/bcms-installation/scripts/js/Shufflejs1.js\"");

WriteLiteral("></script>\r\n    \r\n\r\n<section");

WriteLiteral(" id=\"demo\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"container filter\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"col-9@sm\"");

WriteLiteral(">\r\n                <p");

WriteLiteral(" class=\"filter_label\"");

WriteLiteral(">Filter :</p>\r\n                <div");

WriteLiteral(" class=\"filter-options btn-group\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" class=\"btn btn--warning\"");

WriteLiteral(" data-group=\"wallpaper\"");

WriteLiteral(">Wallpapers</button>\r\n                    <button");

WriteLiteral(" class=\"btn btn--warning\"");

WriteLiteral(" data-group=\"graphics\"");

WriteLiteral(">Graphic Design</button>\r\n                    <button");

WriteLiteral(" class=\"btn btn--warning\"");

WriteLiteral(" data-group=\"photography\"");

WriteLiteral(">Photos</button>\r\n                    <button");

WriteLiteral(" class=\"btn btn--warning\"");

WriteLiteral(" data-group=\"3d\"");

WriteLiteral(">3D Renders</button>\r\n                </div>\r\n            </div>\r\n            <di" +
"v");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" id=\"grid\"");

WriteLiteral(" class=\"row my-shuffle-container shuffle\"");

WriteLiteral(">\r\n                    <figure");

WriteLiteral(" class=\"col-3@xs col-4@sm col-3@md picture-item shuffle-item shuffle-item--visibl" +
"e\"");

WriteLiteral(" data-groups=\"[&quot;photography&quot;]\"");

WriteLiteral("\r\n                            data-title=\"Baseball\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"picture-item__inner\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"aspect aspect--16x9\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"aspect__inner\"");

WriteLiteral(">                                    \r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1740), Tuple.Create("\"", 1784)
, Tuple.Create(Tuple.Create("", 1746), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 1746), false)
);

WriteLiteral(" />\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 1830), Tuple.Create("\"", 1874)
, Tuple.Create(Tuple.Create("", 1836), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 1836), false)
);

WriteLiteral(" class=\"picture-item__blur\"");

WriteLiteral(" />\r\n                                </div>\r\n                            </div>\r\n" +
"                        </div>\r\n                    </figure>\r\n                 " +
"   <figure");

WriteLiteral(" class=\"col-3@xs col-8@sm col-6@md picture-item picture-item--overlay shuffle-ite" +
"m shuffle-item--visible\"");

WriteLiteral(" data-groups=\"[&quot;wallpaper&quot;,&quot;3d&quot;]\"");

WriteLiteral(" data-title=\"Tennis\"");

WriteLiteral(" >\r\n                        <div");

WriteLiteral(" class=\"picture-item__inner\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"aspect aspect--16x9\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"aspect__inner\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2478), Tuple.Create("\"", 2522)
, Tuple.Create(Tuple.Create("", 2484), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 2484), false)
);

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"picture-item__blur\"");

WriteAttribute("src", Tuple.Create(" src=\"", 2593), Tuple.Create("\"", 2637)
, Tuple.Create(Tuple.Create("", 2599), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 2599), false)
);

WriteLiteral(">\r\n                                </div>\r\n                            </div>    " +
"                    \r\n                        </div>\r\n                    </figu" +
"re>\r\n                    <figure");

WriteLiteral(" class=\"col-3@xs col-4@sm col-3@md picture-item shuffle-item shuffle-item--visibl" +
"e\"");

WriteLiteral(" data-groups=\"[&quot;wallpaper&quot;,&quot;3d&quot;]\"");

WriteLiteral(" data-title=\"iMac\"");

WriteLiteral(" >\r\n                        <div");

WriteLiteral(" class=\"picture-item__inner\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"aspect aspect--16x9\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"aspect__inner\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3212), Tuple.Create("\"", 3256)
, Tuple.Create(Tuple.Create("", 3218), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 3218), false)
);

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"picture-item__blur\"");

WriteAttribute("src", Tuple.Create(" src=\"", 3327), Tuple.Create("\"", 3371)
, Tuple.Create(Tuple.Create("", 3333), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 3333), false)
);

WriteLiteral(">\r\n                                </div>\r\n                            </div>    " +
"                       \r\n                        </div>\r\n                    </f" +
"igure>\r\n                    <figure");

WriteLiteral(" class=\"col-6@xs col-4@sm col-3@md picture-item picture-item--h2 shuffle-item shu" +
"ffle-item--visible\"");

WriteLiteral(" data-groups=\"[&quot;graphics&quot;]\"");

WriteLiteral(" data-title=\"Master Chief\"");

WriteLiteral(" >\r\n                        <div");

WriteLiteral(" class=\"picture-item__inner\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"aspect aspect--16x9\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"aspect__inner\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 3958), Tuple.Create("\"", 4002)
, Tuple.Create(Tuple.Create("", 3964), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 3964), false)
);

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"picture-item__blur\"");

WriteAttribute("src", Tuple.Create(" src=\"", 4073), Tuple.Create("\"", 4117)
, Tuple.Create(Tuple.Create("", 4079), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 4079), false)
);

WriteLiteral(">\r\n                                </div>\r\n                            </div>\r\n  " +
"                      </div>\r\n                    </figure>\r\n                   " +
" <figure");

WriteLiteral(" class=\"col-3@xs col-4@sm col-3@md picture-item shuffle-item shuffle-item--visibl" +
"e\"");

WriteLiteral(" data-groups=\"[&quot;wallpaper&quot;,&quot;3d&quot;]\"");

WriteLiteral(" data-title=\"Eightfold\"");

WriteLiteral(" >\r\n                        <div");

WriteLiteral(" class=\"picture-item__inner\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"aspect aspect--16x9\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"aspect__inner\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 4673), Tuple.Create("\"", 4717)
, Tuple.Create(Tuple.Create("", 4679), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 4679), false)
);

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"picture-item__blur\"");

WriteAttribute("src", Tuple.Create(" src=\"", 4788), Tuple.Create("\"", 4832)
, Tuple.Create(Tuple.Create("", 4794), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 4794), false)
);

WriteLiteral(">\r\n                                </div>\r\n                            </div>\r\n  " +
"                     </div>\r\n                    </figure>\r\n                    " +
"<figure");

WriteLiteral(" class=\"col-3@xs col-8@sm col-6@md picture-item picture-item--overlay shuffle-ite" +
"m shuffle-item--visible\"");

WriteLiteral(" data-groups=\"[&quot;photography&quot;]\"");

WriteLiteral(" data-title=\"Pumpkin\"");

WriteLiteral(" >\r\n                        <div");

WriteLiteral(" class=\"picture-item__inner\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"aspect aspect--16x9\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"aspect__inner\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 5394), Tuple.Create("\"", 5438)
, Tuple.Create(Tuple.Create("", 5400), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 5400), false)
);

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"picture-item__blur\"");

WriteAttribute("src", Tuple.Create(" src=\"", 5509), Tuple.Create("\"", 5553)
, Tuple.Create(Tuple.Create("", 5515), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 5515), false)
);

WriteLiteral(">\r\n                                </div>\r\n                            </div>    " +
"                       \r\n                        </div>\r\n                    </f" +
"igure>\r\n                    <figure");

WriteLiteral(" class=\"col-3@xs col-8@sm col-6@md picture-item picture-item--h2 shuffle-item shu" +
"ffle-item--visible\"");

WriteLiteral(" data-groups=\"[&quot;wallpaper&quot;,&quot;3d&quot;]\"");

WriteLiteral(" data-title=\"Vestride\"");

WriteLiteral(" >\r\n                        <div");

WriteLiteral(" class=\"picture-item__inner\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"aspect aspect--16x9\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"aspect__inner\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 6152), Tuple.Create("\"", 6196)
, Tuple.Create(Tuple.Create("", 6158), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 6158), false)
);

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"picture-item__blur\"");

WriteAttribute("src", Tuple.Create(" src=\"", 6267), Tuple.Create("\"", 6311)
, Tuple.Create(Tuple.Create("", 6273), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 6273), false)
);

WriteLiteral(">\r\n                                </div>\r\n                            </div>    " +
"                       \r\n                        </div>\r\n                    </f" +
"igure>\r\n                    <figure");

WriteLiteral(" class=\"col-6@xs col-4@sm col-3@md picture-item picture-item--h2 shuffle-item shu" +
"ffle-item--visible\"");

WriteLiteral(" data-groups=\"[&quot;graphics&quot;]\"");

WriteLiteral(" data-title=\"Newegg\"");

WriteLiteral(" >\r\n                        <div");

WriteLiteral(" class=\"picture-item__inner\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"aspect aspect--16x9\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"aspect__inner\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 6892), Tuple.Create("\"", 6936)
, Tuple.Create(Tuple.Create("", 6898), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 6898), false)
);

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"picture-item__blur\"");

WriteAttribute("src", Tuple.Create(" src=\"", 7007), Tuple.Create("\"", 7051)
, Tuple.Create(Tuple.Create("", 7013), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 7013), false)
);

WriteLiteral(">\r\n                                </div>\r\n                            </div>    " +
"                        \r\n                        </div>\r\n                    </" +
"figure>\r\n                    <figure");

WriteLiteral(" class=\"col-3@xs col-4@sm col-3@md picture-item shuffle-item shuffle-item--visibl" +
"e\"");

WriteLiteral(" data-groups=\"[&quot;wallpaper&quot;]\"");

WriteLiteral("  data-title=\"Arc\"");

WriteLiteral(" >\r\n                        <div");

WriteLiteral(" class=\"picture-item__inner\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"aspect aspect--16x9\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"aspect__inner\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 7615), Tuple.Create("\"", 7659)
, Tuple.Create(Tuple.Create("", 7621), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 7621), false)
);

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"picture-item__blur\"");

WriteAttribute("src", Tuple.Create(" src=\"", 7730), Tuple.Create("\"", 7774)
, Tuple.Create(Tuple.Create("", 7736), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 7736), false)
);

WriteLiteral(">\r\n                                </div>\r\n                            </div>    " +
"                        \r\n                        </div>\r\n                    </" +
"figure>\r\n                    <figure");

WriteLiteral(" class=\"col-3@xs col-4@sm col-3@md picture-item shuffle-item shuffle-item--visibl" +
"e\"");

WriteLiteral(" data-groups=\"[&quot;photography&quot;]\"");

WriteLiteral(" data-title=\"Ground\"");

WriteLiteral(" >\r\n                        <div");

WriteLiteral(" class=\"picture-item__inner\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"aspect aspect--16x9\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"aspect__inner\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 8342), Tuple.Create("\"", 8386)
, Tuple.Create(Tuple.Create("", 8348), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 8348), false)
);

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"picture-item__blur\"");

WriteAttribute("src", Tuple.Create(" src=\"", 8457), Tuple.Create("\"", 8501)
, Tuple.Create(Tuple.Create("", 8463), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 8463), false)
);

WriteLiteral(">\r\n                                </div>\r\n                            </div>    " +
"                       \r\n                        </div>\r\n                    </f" +
"igure>\r\n                    <figure");

WriteLiteral(" class=\"col-3@xs col-8@sm col-6@md picture-item picture-item--overlay shuffle-ite" +
"m shuffle-item--visible\"");

WriteLiteral(" data-groups=\"[&quot;wallpaper&quot;]\"");

WriteLiteral("  data-title=\"Grass\"");

WriteLiteral(" >\r\n                        <div");

WriteLiteral(" class=\"picture-item__inner\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"aspect aspect--16x9\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"aspect__inner\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 9088), Tuple.Create("\"", 9132)
, Tuple.Create(Tuple.Create("", 9094), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 9094), false)
);

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"picture-item__blur\"");

WriteAttribute("src", Tuple.Create(" src=\"", 9203), Tuple.Create("\"", 9247)
, Tuple.Create(Tuple.Create("", 9209), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 9209), false)
);

WriteLiteral(">\r\n                                </div>\r\n                            </div>    " +
"                       \r\n                        </div>\r\n                    </f" +
"igure>\r\n                    <figure");

WriteLiteral(" class=\"col-3@xs col-4@sm col-3@md picture-item shuffle-item shuffle-item--visibl" +
"e\"");

WriteLiteral(" data-groups=\"[&quot;wallpaper&quot;,&quot;3d&quot;]\"");

WriteLiteral(" data-date-created=\"2013-05-19\"");

WriteLiteral(" data-title=\"Vestride\"");

WriteLiteral(" >\r\n                        <div");

WriteLiteral(" class=\"picture-item__inner\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"aspect aspect--16x9\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"aspect__inner\"");

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 9860), Tuple.Create("\"", 9904)
, Tuple.Create(Tuple.Create("", 9866), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 9866), false)
);

WriteLiteral(">\r\n                                    <img");

WriteLiteral(" class=\"picture-item__blur\"");

WriteAttribute("src", Tuple.Create(" src=\"", 9975), Tuple.Create("\"", 10019)
, Tuple.Create(Tuple.Create("", 9981), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Styles/images/banner_img.jpg")
, 9981), false)
);

WriteLiteral(">\r\n                                </div>\r\n                            </div>    " +
"                        \r\n                        </div>\r\n                    </" +
"figure>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r" +
"\n</section>\r\n");

        }
    }
}
#pragma warning restore 1591
