#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Widgets\Slider.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/Slider.cshtml")]
    public partial class _Views_Widgets_Slider_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_Slider_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 5 "..\..\Views\Widgets\Slider.cshtml"
  
    ViewBag.Title = "Slider";

            
            #line default
            #line hidden
WriteLiteral("\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"http://netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.cs" +
"s\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/file/bcms-installation/Content/Styles/animate.css\"");

WriteLiteral(">\r\n\r\n\r\n");

            
            #line 12 "..\..\Views\Widgets\Slider.cshtml"
 if (Model != null && Model.Options != null)
{
    RenderWidgetViewModel.SliderRootObject robj = null;
    string sliderWidgetHeight = "400";
    string sliderWidgetHeightPx = "400px";
    string guidSliderStr = Guid.NewGuid().ToString();
    foreach (var option in Model.Options)
    {
        string slidertext = string.Empty;
        if (@option.Key == "itemcount")
        {

            
            #line default
            #line hidden
WriteLiteral("            <script>\r\n                var itemcount = \'");

            
            #line 24 "..\..\Views\Widgets\Slider.cshtml"
                            Write(option.Value);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            </script>\r\n");

            
            #line 26 "..\..\Views\Widgets\Slider.cshtml"
        }
        else if (@option.Key == "json")
        {
            robj = RenderWidgetViewModel.jsSerial.Deserialize<RenderWidgetViewModel.SliderRootObject>(@option.Value);
        }
        else if (@option.Key == "height")
        {
            sliderWidgetHeight = @option.Value;
            sliderWidgetHeightPx = @option.Value + "px";
        }
    }
    if (robj != null)
    {
        if (robj.sliderhtml != null && robj.sliderhtml.Count > 0)
        {
            
            
            #line default
            #line hidden
            
            #line 41 "..\..\Views\Widgets\Slider.cshtml"
                                                                           
            
            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Widgets\Slider.cshtml"
                                         

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteAttribute("id", Tuple.Create(" id=\"", 1456), Tuple.Create("\"", 1475)
            
            #line 43 "..\..\Views\Widgets\Slider.cshtml"
, Tuple.Create(Tuple.Create("", 1461), Tuple.Create<System.Object, System.Int32>(guidSliderStr
            
            #line default
            #line hidden
, 1461), false)
);

WriteAttribute("xclass", Tuple.Create(" xclass=\"", 1476), Tuple.Create("\"", 1505)
, Tuple.Create(Tuple.Create("", 1485), Tuple.Create("slide", 1485), true)
            
            #line 43 "..\..\Views\Widgets\Slider.cshtml"
, Tuple.Create(Tuple.Create(" ", 1490), Tuple.Create<System.Object, System.Int32>(guidSliderStr
            
            #line default
            #line hidden
, 1491), false)
);

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"myCarousel\"");

WriteLiteral(" class=\"slide myCarousel\"");

WriteLiteral(" style=\"position:relative;\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"carousel-inner\"");

WriteLiteral(" role=\"listbox\"");

WriteLiteral(">\r\n\r\n");

            
            #line 47 "..\..\Views\Widgets\Slider.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 47 "..\..\Views\Widgets\Slider.cshtml"
                             foreach (var obj2 in robj.sliderhtml)
                    {

                                
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Widgets\Slider.cshtml"
                                                                                                   

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"item\"");

WriteAttribute("style", Tuple.Create(" style=\"", 1918), Tuple.Create("\"", 1965)
, Tuple.Create(Tuple.Create("", 1926), Tuple.Create("height:", 1926), true)
            
            #line 51 "..\..\Views\Widgets\Slider.cshtml"
, Tuple.Create(Tuple.Create("", 1933), Tuple.Create<System.Object, System.Int32>(sliderWidgetHeightPx
            
            #line default
            #line hidden
, 1933), false)
, Tuple.Create(Tuple.Create("", 1954), Tuple.Create("!important;", 1954), true)
);

WriteLiteral(">\r\n                                    <img");

WriteAttribute("src", Tuple.Create(" src=\"", 2009), Tuple.Create("\"", 2032)
            
            #line 52 "..\..\Views\Widgets\Slider.cshtml"
, Tuple.Create(Tuple.Create("", 2015), Tuple.Create<System.Object, System.Int32>(obj2.sliderimage
            
            #line default
            #line hidden
, 2015), false)
);

WriteLiteral(" style=\"width:100%;\"");

WriteLiteral(" />\r\n");

            
            #line 53 "..\..\Views\Widgets\Slider.cshtml"
                                    
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Widgets\Slider.cshtml"
                                     if (!string.IsNullOrWhiteSpace(obj2.slidervideo))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                        <video muted");

WriteLiteral(" id=\"video\"");

WriteLiteral(" data-interval=\"19000\"");

WriteLiteral(" preload=\"none\"");

WriteLiteral(" class=\"video\"");

WriteLiteral(">\r\n                                            <source");

WriteAttribute("src", Tuple.Create(" src=", 2345), Tuple.Create("", 2367)
            
            #line 56 "..\..\Views\Widgets\Slider.cshtml"
, Tuple.Create(Tuple.Create("", 2350), Tuple.Create<System.Object, System.Int32>(obj2.slidervideo
            
            #line default
            #line hidden
, 2350), false)
);

WriteLiteral(" type=\"video/mp4\"");

WriteLiteral(">\r\n\r\n                                        </video>\r\n");

            
            #line 59 "..\..\Views\Widgets\Slider.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <div");

WriteLiteral(" class=\"animated zoomIn center circle\"");

WriteLiteral(">\r\n                                        <h1");

WriteLiteral(" class=\"div-header\"");

WriteLiteral(">");

            
            #line 62 "..\..\Views\Widgets\Slider.cshtml"
                                                          Write(obj2.slidertext);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n                                        <a");

WriteLiteral(" class=\"animated zoomIn div-a\"");

WriteAttribute("href", Tuple.Create(" href=\"", 2711), Tuple.Create("\"", 2728)
            
            #line 63 "..\..\Views\Widgets\Slider.cshtml"
, Tuple.Create(Tuple.Create("", 2718), Tuple.Create<System.Object, System.Int32>(obj2.href
            
            #line default
            #line hidden
, 2718), false)
);

WriteLiteral(" target=\"_blank\"");

WriteAttribute("style", Tuple.Create(" style=\"", 2745), Tuple.Create("\"", 2820)
, Tuple.Create(Tuple.Create("", 2753), Tuple.Create("background-color:", 2753), true)
            
            #line 63 "..\..\Views\Widgets\Slider.cshtml"
                                                   , Tuple.Create(Tuple.Create("", 2770), Tuple.Create<System.Object, System.Int32>(obj2.buttoncolor
            
            #line default
            #line hidden
, 2770), false)
, Tuple.Create(Tuple.Create("", 2787), Tuple.Create(";border-color:", 2787), true)
            
            #line 63 "..\..\Views\Widgets\Slider.cshtml"
                                                                                  , Tuple.Create(Tuple.Create("", 2801), Tuple.Create<System.Object, System.Int32>(obj2.bordercolor
            
            #line default
            #line hidden
, 2801), false)
, Tuple.Create(Tuple.Create("", 2818), Tuple.Create(";", 2818), true)
, Tuple.Create(Tuple.Create(" ", 2819), Tuple.Create("", 2819), true)
);

WriteLiteral(">");

            
            #line 63 "..\..\Views\Widgets\Slider.cshtml"
                                                                                                                                                                                  Write(obj2.buttontext);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                    </div>\r\n                               " +
" </div>\r\n");

            
            #line 66 "..\..\Views\Widgets\Slider.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n\r\n                        <a");

WriteLiteral(" class=\"left carousel-control\"");

WriteLiteral(" xhref=\"#myCarousel\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" data-slide=\"prev\"");

WriteAttribute("style", Tuple.Create(" style=\"", 3093), Tuple.Create("\"", 3140)
, Tuple.Create(Tuple.Create("", 3101), Tuple.Create("height:", 3101), true)
            
            #line 69 "..\..\Views\Widgets\Slider.cshtml"
                                           , Tuple.Create(Tuple.Create("", 3108), Tuple.Create<System.Object, System.Int32>(sliderWidgetHeightPx
            
            #line default
            #line hidden
, 3108), false)
, Tuple.Create(Tuple.Create("", 3129), Tuple.Create("!important;", 3129), true)
);

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"glyphicon glyphicon-chevron-left\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" style=\"border-radius:50%;position:absolute;z-index:20;color:#27a8b4;width: 50px;" +
"height: 50px;padding: 10px;\"");

WriteLiteral(">\r\n                            </span>\r\n\r\n                        </a>\r\n         " +
"               <a");

WriteLiteral(" class=\"right carousel-control\"");

WriteLiteral(" xhref=\"#myCarousel\"");

WriteLiteral(" role=\"button\"");

WriteLiteral(" data-slide=\"next\"");

WriteAttribute("style", Tuple.Create(" style=\"", 3527), Tuple.Create("\"", 3574)
, Tuple.Create(Tuple.Create("", 3535), Tuple.Create("height:", 3535), true)
            
            #line 74 "..\..\Views\Widgets\Slider.cshtml"
                                            , Tuple.Create(Tuple.Create("", 3542), Tuple.Create<System.Object, System.Int32>(sliderWidgetHeightPx
            
            #line default
            #line hidden
, 3542), false)
, Tuple.Create(Tuple.Create("", 3563), Tuple.Create("!important;", 3563), true)
);

WriteLiteral(">\r\n                            <span");

WriteLiteral(" class=\"glyphicon glyphicon-chevron-right\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(" style=\"border-radius:50%;position:absolute;z-index:20;color:#27a8b4;width: 50px;" +
"height: 50px;padding: 10px;\"");

WriteLiteral(">\r\n                            </span>\r\n                        </a>\r\n           " +
"         </div>\r\n                </div>\r\n");

            
            #line 80 "..\..\Views\Widgets\Slider.cshtml"
            
            
            #line default
            #line hidden
            
            #line 80 "..\..\Views\Widgets\Slider.cshtml"
                      

            
            #line default
            #line hidden
WriteLiteral("            <script>\r\n                var index = 0;\r\n                jQuery(docu" +
"ment).ready(function ($) {\r\n                    $(\'#");

            
            #line 84 "..\..\Views\Widgets\Slider.cshtml"
                   Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral(" #myCarousel ol li:first-child\').addClass(\'active\');\r\n                    $(\'#");

            
            #line 85 "..\..\Views\Widgets\Slider.cshtml"
                   Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral(" #myCarousel div.item:first-child\').addClass(\'active\');\r\n                    //$(" +
"\'.");

            
            #line 86 "..\..\Views\Widgets\Slider.cshtml"
                     Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral("\').carousel({\r\n                    $(\'.");

            
            #line 87 "..\..\Views\Widgets\Slider.cshtml"
                   Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral(" .myCarousel\').carousel({\r\n                        interval: 19000,\r\n            " +
"            pause: \"false\"\r\n                    });\r\n                    setTime" +
"out(function () {\r\n\r\n                        if ($(\'#");

            
            #line 93 "..\..\Views\Widgets\Slider.cshtml"
                           Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral(@" #myCarousel div.item:first-child').children().find('video') != null) {
                            var videoCnt = $("".video"").length;
                            if(videoCnt >0)
                                $("".video:first"")[0].play();
                        }
                    }, 3000);
                    $('.");

            
            #line 99 "..\..\Views\Widgets\Slider.cshtml"
                   Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral(" .myCarousel\').on(\'slid.bs.carousel\', function (e) {\r\n                        set" +
"Timeout(function () {\r\n                            if ($(\'.");

            
            #line 101 "..\..\Views\Widgets\Slider.cshtml"
                               Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral("  div.active\').find(\'video\').length > 0) {\r\n                                $(\'.");

            
            #line 102 "..\..\Views\Widgets\Slider.cshtml"
                               Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral("  div.active\').find(\'video\')[0].play();\r\n                            }\r\n         " +
"               }, 3000);\r\n                    });\r\n\r\n                    var $it" +
"em = $(\'.");

            
            #line 107 "..\..\Views\Widgets\Slider.cshtml"
                               Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral(" .item\');\r\n                    //var $wHeight = \'400px\';sliderWidgetHeight\r\n     " +
"               var $wHeight = ");

            
            #line 109 "..\..\Views\Widgets\Slider.cshtml"
                              Write(sliderWidgetHeight);

            
            #line default
            #line hidden
WriteLiteral(" +\"px\";\r\n                    $item.eq(0).addClass(\'active\');\r\n                   " +
" $item.height($wHeight);\r\n                    $item.addClass(\'full-screen\');\r\n\r\n" +
"                    $(\'.");

            
            #line 114 "..\..\Views\Widgets\Slider.cshtml"
                   Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral(@" .myCarousel img').each(function () {
                        var $src = $(this).attr('src');
                        var $color = $(this).attr('data-color');
                        $(this).parent().css({
                            'background-image': 'url(' + $src + ')',
                            'background-color': $color
                        });
                        $(this).remove();
                    });

                    $(window).on('resize', function () {
                        $item.height($wHeight);
                    });

                    $('video').on('ended', function () {
                        $('.");

            
            #line 129 "..\..\Views\Widgets\Slider.cshtml"
                       Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral(" .myCarousel\').carousel(\'next\');\r\n                    });\r\n                    if" +
" (typeof itemcount != \'undefined\' && parseInt(itemcount) > 0) {\r\n               " +
"         $(\'#");

            
            #line 132 "..\..\Views\Widgets\Slider.cshtml"
                       Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral(" #myCarousel .full-screen\').slice(parseInt(itemcount)).remove();\r\n               " +
"     }\r\n\r\n                    // Enable Carousel Controls\r\n                    $" +
"(\"#");

            
            #line 136 "..\..\Views\Widgets\Slider.cshtml"
                   Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral(" .left\").click(function () {\r\n                        $(\"#");

            
            #line 137 "..\..\Views\Widgets\Slider.cshtml"
                       Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral(" #myCarousel\").carousel(\"prev\");\r\n                    });\r\n                    //" +
" Enable Carousel Controls\r\n                    $(\"#");

            
            #line 140 "..\..\Views\Widgets\Slider.cshtml"
                   Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral(" .right\").click(function () {\r\n                        $(\"#");

            
            #line 141 "..\..\Views\Widgets\Slider.cshtml"
                       Write(guidSliderStr);

            
            #line default
            #line hidden
WriteLiteral(" #myCarousel\").carousel(\"next\");\r\n                    });\r\n                });\r\n " +
"           </script>\r\n");

            
            #line 145 "..\..\Views\Widgets\Slider.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <style");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(">\r\n                video, img {\r\n                    object-fit: inherit;\r\n      " +
"              width: 100% !important;\r\n                    height: 100% !importa" +
"nt;\r\n                    object-fit: cover !important;\r\n                }\r\n\r\n   " +
"             h3 {\r\n                    display: inline-block;\r\n                 " +
"   padding: 10px;\r\n                    background: #B9121B;\r\n                   " +
" border-top-left-radius: 10px;\r\n                    border-top-right-radius: 10p" +
"x;\r\n                }\r\n\r\n                .full-screen {\r\n                    bac" +
"kground-size: cover;\r\n                    background-position: center;\r\n        " +
"            background-repeat: no-repeat;\r\n                }\r\n\r\n                " +
".full-video {\r\n                    position: absolute;\r\n                    left" +
": 0px;\r\n                    z-index: 1;\r\n                    width: 100%;\r\n     " +
"               height: 100%;\r\n                    -webkit-transition: left 1s;\r\n" +
"                    -moz-transition: left 1s;\r\n                    transition: l" +
"eft 1s;\r\n                }\r\n\r\n                    .full-video iframe {\r\n        " +
"                width: 100%;\r\n                        height: 100%;\r\n           " +
"         }\r\n\r\n                div.item {\r\n                    position: relative" +
";\r\n                }\r\n\r\n                    div.item div.center {\r\n             " +
"           position: absolute;\r\n                        left: 50%;\r\n            " +
"            top: 50%;\r\n                        transform: translate(-50%, -50%);" +
"\r\n                        width: 90%;\r\n                        height: 120%;\r\n  " +
"                      text-align: center;\r\n                        padding-top: " +
"5%;\r\n                        animation-delay: 0s;\r\n                    }\r\n\r\n    " +
"            .div-header {\r\n                    color: white;\r\n                  " +
"  text-transform: uppercase;\r\n                    font-weight: 600;\r\n           " +
"         text-align: center;\r\n                    /*margin-bottom: 8%;*/\r\n      " +
"              margin-bottom:30px;\r\n                }\r\n\r\n                div.item" +
" div.circle {\r\n                    border-radius: 50%;\r\n                    back" +
"ground: rgba(0, 0, 0, 0.05);\r\n                    letter-spacing: 1px;\r\n        " +
"        }\r\n\r\n                .div-a {\r\n                    color: white;\r\n      " +
"              padding: 12px 26px;\r\n                    text-decoration: none;\r\n " +
"                   border: 1px solid;\r\n                    font-weight: bold;\r\n " +
"                   animation-delay: 2s;\r\n                }\r\n\r\n                  " +
"  .div-a:hover {\r\n                        color: white;\r\n                       " +
" text-decoration: none;\r\n                    }\r\n\r\n                a.carousel-con" +
"trol span.glyphicon {\r\n                    position: absolute;\r\n                " +
"}\r\n            </style>\r\n");

            
            #line 233 "..\..\Views\Widgets\Slider.cshtml"
        }
    }
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
