#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/ThreeSectionWidget.cshtml")]
    public partial class _Views_Widgets_ThreeSectionWidget_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_ThreeSectionWidget_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/file/bcms-installation/content/styles/imagehover.min.css\"");

WriteLiteral(" />\r\n<link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"/file/bcms-installation/content/styles/newstyle.css\"");

WriteLiteral(" />\r\n");

            
            #line 7 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
 if (Model != null)
{
   
    string bgcolor = string.Empty;
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
     if (Model.Options != null)
    {

    foreach (var option in Model.Options)
    {
        string imageurl = string.Empty;
        string heading = string.Empty;
        string text = string.Empty;
        string iconurl = string.Empty;
         
        if (@option.Key =="Background_color")
        {
            bgcolor = @option.Value;
        }
        if (@option.Key == "JsonFile")
        {
            RenderWidgetViewModel.RootObject robj = null;
            robj = RenderWidgetViewModel.jsSerial.Deserialize<RenderWidgetViewModel.RootObject>(@option.Value);
            if (robj != null)
            {
                if (robj.data != null && robj.data.Count > 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"threesectioncontainer container\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

            
            #line 35 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
                            
            
            #line default
            #line hidden
            
            #line 35 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
                             foreach (var obj in robj.data)
                            {
                                imageurl = obj.imageurl;
                                heading = obj.heading;
                                text = obj.text;
                                iconurl = obj.iconurl;
                                if(iconurl != "")
                                { 

            
            #line default
            #line hidden
WriteLiteral("                                <div");

WriteLiteral(" class=\"widgetclass col-sm-4\"");

WriteLiteral(" >\r\n                                    <figure");

WriteLiteral(" class=\"imghvr-push-up\"");

WriteLiteral(" style=\"width:100%;\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=", 1829), Tuple.Create("", 1843)
            
            #line 45 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
, Tuple.Create(Tuple.Create("", 1834), Tuple.Create<System.Object, System.Int32>(imageurl
            
            #line default
            #line hidden
, 1834), false)
);

WriteLiteral(" style=\"width:100%;\"");

WriteLiteral(">\r\n                                        <figcaption");

WriteAttribute("style", Tuple.Create(" style=\"", 1917), Tuple.Create("\"", 1951)
, Tuple.Create(Tuple.Create("", 1925), Tuple.Create("background-color:", 1925), true)
            
            #line 46 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
, Tuple.Create(Tuple.Create("", 1942), Tuple.Create<System.Object, System.Int32>(bgcolor
            
            #line default
            #line hidden
, 1942), false)
, Tuple.Create(Tuple.Create("", 1950), Tuple.Create(";", 1950), true)
);

WriteLiteral(">\r\n                                            <div");

WriteLiteral(" class=\"three_section_icon\"");

WriteLiteral(">\r\n                                                <img");

WriteAttribute("src", Tuple.Create(" src=", 2085), Tuple.Create("", 2098)
            
            #line 48 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
, Tuple.Create(Tuple.Create("", 2090), Tuple.Create<System.Object, System.Int32>(iconurl
            
            #line default
            #line hidden
, 2090), false)
);

WriteLiteral(" />\r\n                                            </div>\r\n                        " +
"                    <h4>");

            
            #line 50 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
                                           Write(heading);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                                            <p>");

            
            #line 51 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
                                          Write(text);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                        </figcaption>\r\n                    " +
"                </figure>\r\n                                </div>\r\n");

            
            #line 55 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                  <div");

WriteLiteral(" class=\"widgetclass col-sm-4\"");

WriteLiteral(">\r\n                                     <figure");

WriteLiteral(" class=\"imghvr-push-up\"");

WriteLiteral(" style=\"width:100%;\"");

WriteLiteral(">\r\n                                        <img");

WriteAttribute("src", Tuple.Create(" src=", 2730), Tuple.Create("", 2744)
            
            #line 60 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
, Tuple.Create(Tuple.Create("", 2735), Tuple.Create<System.Object, System.Int32>(imageurl
            
            #line default
            #line hidden
, 2735), false)
);

WriteLiteral(" style=\"width:100%;\"");

WriteLiteral(">\r\n                                        <figcaption");

WriteAttribute("style", Tuple.Create(" style=\"", 2818), Tuple.Create("\"", 2852)
, Tuple.Create(Tuple.Create("", 2826), Tuple.Create("background-color:", 2826), true)
            
            #line 61 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
, Tuple.Create(Tuple.Create("", 2843), Tuple.Create<System.Object, System.Int32>(bgcolor
            
            #line default
            #line hidden
, 2843), false)
, Tuple.Create(Tuple.Create("", 2851), Tuple.Create(";", 2851), true)
);

WriteLiteral(">\r\n                                            \r\n                                " +
"            <h4>");

            
            #line 63 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
                                           Write(heading);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                                            <p");

WriteLiteral(" id=\"paragraph\"");

WriteLiteral(">");

            
            #line 64 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
                                                         Write(text);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                                        </figcaption>\r\n                    " +
"                 </figure>\r\n                                   </div>\r\n");

            
            #line 68 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
                                }

                            }
            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

            
            #line 73 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
                }
            }
        }
    }
}
            
            #line default
            #line hidden
            
            #line 77 "..\..\Views\Widgets\ThreeSectionWidget.cshtml"
 
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
