#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 6 "..\..\Views\Widgets\VidyatechCaseStudyBannerWidget.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Widgets\VidyatechCaseStudyBannerWidget.cshtml"
    using BetterCms.Module.Root.ViewModels.Cms;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Widgets/VidyatechCaseStudyBannerWidget.cshtml")]
    public partial class _Views_Widgets_VidyatechCaseStudyBannerWidget_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Root.ViewModels.Cms.RenderWidgetViewModel>
    {
        public _Views_Widgets_VidyatechCaseStudyBannerWidget_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Widgets\VidyatechCaseStudyBannerWidget.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n");

WriteLiteral("\r\n\r\n");

            
            #line 12 "..\..\Views\Widgets\VidyatechCaseStudyBannerWidget.cshtml"
 if (Model != null && Model.Options != null)
{
    string bannerImgUrl = null, Title = null, SubTitle = null;
    string guid = Guid.NewGuid().ToString();
    string objId = "myBanner" + guid;


    foreach (var options in Model.Options)
    {
        if (options.Key == "Title")
        {
            Title = options.Value;
        }
        if (options.Key == "SubTitle")
        {
            SubTitle = options.Value;
        }
   

        if (options.Key == "bannerImgUrl")
        {
            bannerImgUrl = options.Value;
        }



    }



            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" style=\"position:absolute;margin-left:5%;margin-top:3%;width:40%\"");

WriteLiteral(">\r\n\t\t\t\t<fieldset>\r\n\t\t\t\t  <legend>");

            
            #line 43 "..\..\Views\Widgets\VidyatechCaseStudyBannerWidget.cshtml"
                     Write(Title);

            
            #line default
            #line hidden
WriteLiteral("</legend>\r\n\t\t\t\t  <h4>");

            
            #line 44 "..\..\Views\Widgets\VidyatechCaseStudyBannerWidget.cshtml"
                 Write(SubTitle);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n\t\t\t\t</fieldset>\t\t\t\t\t\t\t\t\r\n\t\t\t\t</div>\r\n");

WriteLiteral("    <img");

WriteLiteral(" width=\"100%;\"");

WriteAttribute("src", Tuple.Create(" src=\"", 981), Tuple.Create("\"", 1000)
            
            #line 47 "..\..\Views\Widgets\VidyatechCaseStudyBannerWidget.cshtml"
, Tuple.Create(Tuple.Create("", 987), Tuple.Create<System.Object, System.Int32>(bannerImgUrl
            
            #line default
            #line hidden
, 987), false)
);

WriteLiteral(" />\r\n");

            
            #line 48 "..\..\Views\Widgets\VidyatechCaseStudyBannerWidget.cshtml"


}
            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
