#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\n<!DOCTYPE html>\n<html>\n<head>\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\n    <title>");

            
            #line 33 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET Application</title>\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1480), Tuple.Create("\"", 1505)
, Tuple.Create(Tuple.Create("", 1487), Tuple.Create<System.Object, System.Int32>(Href("~/Content/Site.css")
, 1487), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 1552), Tuple.Create("\"", 1586)
, Tuple.Create(Tuple.Create("", 1559), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap.min.css")
, 1559), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 1635), Tuple.Create("\"", 1669)
, Tuple.Create(Tuple.Create("", 1641), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/modernizr-2.6.2.js")
, 1641), false)
);

WriteLiteral("></script>\n</head>\n<body>\n    <div");

WriteLiteral(" class=\"navbar navbar-inverse navbar-fixed-top\"");

WriteLiteral(">\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\n            <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteLiteral(">\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\n                </button>\n");

WriteLiteral("                ");

            
            #line 47 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\n            </div>\n            <div");

WriteLiteral(" class=\"navbar-collapse collapse\"");

WriteLiteral(">\n                <ul");

WriteLiteral(" class=\"nav navbar-nav\"");

WriteLiteral(">\n                </ul>\n            </div>\n        </div>\n    </div>\n\n    <div");

WriteLiteral(" class=\"container body-content\"");

WriteLiteral(">\n");

WriteLiteral("        ");

            
            #line 57 "..\..\Views\Shared\_Layout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\n        <hr />\n        <footer>\n            <p>&copy; ");

            
            #line 60 "..\..\Views\Shared\_Layout.cshtml"
                 Write(DateTime.Now.Year);

            
            #line default
            #line hidden
WriteLiteral(" - My ASP.NET Application</p>\n        </footer>\n    </div>\n\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2629), Tuple.Create("\"", 2665)
, Tuple.Create(Tuple.Create("", 2635), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/jquery-1.10.2.min.js")
, 2635), false)
);

WriteLiteral("></script>\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 2688), Tuple.Create("\"", 2720)
, Tuple.Create(Tuple.Create("", 2694), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/bootstrap.min.js")
, 2694), false)
);

WriteLiteral("></script>\n</body>\n</html>");

        }
    }
}
#pragma warning restore 1591
