#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 28 "..\..\Views\Authentication\Login.cshtml"
    using BetterCms.Module.Root.Mvc.Helpers;
    
    #line default
    #line hidden
    
    #line 29 "..\..\Views\Authentication\Login.cshtml"
    using BetterCms.Module.Users.Content.Resources;
    
    #line default
    #line hidden
    
    #line 31 "..\..\Views\Authentication\Login.cshtml"
    using BetterCms.Module.Users.Controllers;
    
    #line default
    #line hidden
    
    #line 32 "..\..\Views\Authentication\Login.cshtml"
    using BetterCms.Module.Users.Services;
    
    #line default
    #line hidden
    
    #line 33 "..\..\Views\Authentication\Login.cshtml"
    using BetterCms.Module.Users.ViewModels;
    
    #line default
    #line hidden
    
    #line 30 "..\..\Views\Authentication\Login.cshtml"
    using Microsoft.Web.Mvc;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Authentication/Login.cshtml")]
    public partial class _Views_Authentication_Login_cshtml : System.Web.Mvc.WebViewPage<BetterCms.Module.Users.ViewModels.Authentication.LoginViewModel>
    {
        public _Views_Authentication_Login_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

WriteLiteral("\r\n");

            
            #line 37 "..\..\Views\Authentication\Login.cshtml"
  

    Layout = "~/Areas/bcms-users/Views/Shared/PublicActionLayout.cshtml";
    ViewBag.Title = "Login";

    ViewBag.googleApikey = System.Configuration.ConfigurationManager.AppSettings["googleApikey"];

    ViewBag.googleAppid = System.Configuration.ConfigurationManager.AppSettings["googleAppId"];

    ViewBag.facebookid = System.Configuration.ConfigurationManager.AppSettings["facebookAppId"];


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<script");

WriteLiteral(" src=\"http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"/file/bcms-users/scripts/google.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"https://apis.google.com/js/platform.js\"");

WriteLiteral(" async defer></script>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(" src=\"//connect.facebook.net/en_US/all.js\"");

WriteLiteral("></script>\r\n<meta");

WriteLiteral(" name=\"google-signin-client_id\"");

WriteAttribute("content", Tuple.Create(" content=\'", 2484), Tuple.Create("\'", 2516)
            
            #line 54 "..\..\Views\Authentication\Login.cshtml"
, Tuple.Create(Tuple.Create("", 2494), Tuple.Create<System.Object, System.Int32>(ViewBag.googleAppid
            
            #line default
            #line hidden
, 2494), false)
);

WriteLiteral(">\r\n\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var googleApiKey = \'");

            
            #line 57 "..\..\Views\Authentication\Login.cshtml"
                   Write(ViewBag.googleApikey);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    var facebookId = \'");

            
            #line 58 "..\..\Views\Authentication\Login.cshtml"
                 Write(ViewBag.facebookid);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n    var googleAppId = \'");

            
            #line 59 "..\..\Views\Authentication\Login.cshtml"
                  Write(ViewBag.googleAppid);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n</script>\r\n\r\n<script async defer");

WriteLiteral(" src=\"https://apis.google.com/js/api.js\"");

WriteLiteral("\r\n        onload=\"this.onload=function(){};handleClientLoad()\"");

WriteLiteral("\r\n        onreadystatechange=\"if (this.readyState === \'complete\') this.onload()\"");

WriteLiteral(">\r\n</script>\r\n\r\n<script");

WriteLiteral(" src=\"/file/bcms-users/scripts/facebook.js\"");

WriteLiteral("></script>\r\n\r\n<div");

WriteLiteral(" id=\"fb-root\"");

WriteLiteral("></div>\r\n\r\n<div");

WriteLiteral(" class=\"bcms-login-box\"");

WriteLiteral(">\r\n    <h1>TITLE OF LOGIN</h1>\r\n    <h5");

WriteLiteral(" id=\"invalidusermessage\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">This user is already registered.</h5>\r\n    <div");

WriteLiteral(" id=\"divBasicLogin\"");

WriteLiteral(">\r\n");

            
            #line 75 "..\..\Views\Authentication\Login.cshtml"
        
            
            #line default
            #line hidden
            
            #line 75 "..\..\Views\Authentication\Login.cshtml"
          
            BetterCms.Module.Users.ViewModels.Authentication.LoginViewModel model = new BetterCms.Module.Users.ViewModels.Authentication.LoginViewModel();
        
            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 78 "..\..\Views\Authentication\Login.cshtml"
        
            
            #line default
            #line hidden
            
            #line 78 "..\..\Views\Authentication\Login.cshtml"
         using (Html.BeginForm())
        {


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 81 "..\..\Views\Authentication\Login.cshtml"
                                        Write(UsersGlobalization.Login_UserName);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 82 "..\..\Views\Authentication\Login.cshtml"
            
            
            #line default
            #line hidden
            
            #line 82 "..\..\Views\Authentication\Login.cshtml"
       Write(Html.ValidationMessageFor(m => m.UserName));

            
            #line default
            #line hidden
            
            #line 82 "..\..\Views\Authentication\Login.cshtml"
                                                       

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 84 "..\..\Views\Authentication\Login.cshtml"
           Write(Html.TextBoxFor(m => m.UserName, new { id = "userName", @class = "bcms-field-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 86 "..\..\Views\Authentication\Login.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">");

            
            #line 87 "..\..\Views\Authentication\Login.cshtml"
                                        Write(UsersGlobalization.Login_Password);

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 88 "..\..\Views\Authentication\Login.cshtml"
            
            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Authentication\Login.cshtml"
       Write(Html.ValidationMessageFor(m => m.Password));

            
            #line default
            #line hidden
            
            #line 88 "..\..\Views\Authentication\Login.cshtml"
                                                       

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 90 "..\..\Views\Authentication\Login.cshtml"
           Write(Html.PasswordFor(m => m.Password, new { @class = "bcms-field-text" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 92 "..\..\Views\Authentication\Login.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"bcms-field-wrapper bcms-remember-box\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 94 "..\..\Views\Authentication\Login.cshtml"
           Write(Html.CheckBoxFor(m => m.RememberMe));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 95 "..\..\Views\Authentication\Login.cshtml"
           Write(Html.LabelFor(m => m.RememberMe));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");

            
            #line 97 "..\..\Views\Authentication\Login.cshtml"

            Dictionary<string, object> submitProperties = new Dictionary<string, object>();
            submitProperties.Add("class", "bcms-btn-primary");
            if (!Model.IsFormsAuthenticationEnabled)
            {
                submitProperties.Add("disabled", "disabled");
            }

            
            
            #line default
            #line hidden
            
            #line 105 "..\..\Views\Authentication\Login.cshtml"
       Write(Html.SubmitButton("submit", "Login", submitProperties));

            
            #line default
            #line hidden
            
            #line 105 "..\..\Views\Authentication\Login.cshtml"
                                                                   

            
            
            #line default
            #line hidden
            
            #line 107 "..\..\Views\Authentication\Login.cshtml"
       Write(Html.HiddenFor(m => m.ReturnUrl));

            
            #line default
            #line hidden
            
            #line 107 "..\..\Views\Authentication\Login.cshtml"
                                             
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 110 "..\..\Views\Authentication\Login.cshtml"
        
            
            #line default
            #line hidden
            
            #line 110 "..\..\Views\Authentication\Login.cshtml"
         if (@ViewBag.googleAppid != "")
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" style=\"height:50px;width:100%;\"");

WriteLiteral("></div>\r\n");

            
            #line 113 "..\..\Views\Authentication\Login.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"socialbutton\"");

WriteLiteral(" id=\"gsign_d\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"g-signin2\"");

WriteLiteral("  data-onsuccess=\"onSignIn\"");

WriteLiteral("></div>\r\n            </div>\r\n");

            
            #line 117 "..\..\Views\Authentication\Login.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 119 "..\..\Views\Authentication\Login.cshtml"
        
            
            #line default
            #line hidden
            
            #line 119 "..\..\Views\Authentication\Login.cshtml"
         if (@ViewBag.facebookid != "")
        {

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"socialbutton\"");

WriteLiteral(" id=\"facebookIn_d\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" id=\"facebookIn\"");

WriteLiteral(" onclick=\"javascript:Login();\"");

WriteLiteral(">f <span>sign in</span></button>\r\n            </div>\r\n");

            
            #line 124 "..\..\Views\Authentication\Login.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"socialbutton\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" class=\"bcms-btn-primary\"");

WriteLiteral(" style=\"width:120px;margin-top:8px;\"");

WriteLiteral(" id=\"signup\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 5314), Tuple.Create("\"", 5381)
, Tuple.Create(Tuple.Create("", 5324), Tuple.Create("javascript:window.location.href=\'", 5324), true)
            
            #line 126 "..\..\Views\Authentication\Login.cshtml"
                                                       , Tuple.Create(Tuple.Create("", 5357), Tuple.Create<System.Object, System.Int32>(Url.RouteUrl("Signup")
            
            #line default
            #line hidden
, 5357), false)
, Tuple.Create(Tuple.Create("", 5380), Tuple.Create("\'", 5380), true)
);

WriteLiteral(">Signup</button>\r\n        </div>\r\n    </div>\r\n    <div");

WriteLiteral(" id=\"emailaddress\"");

WriteLiteral(" style=\"display: none;\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"bcms-content-titles\"");

WriteLiteral(">Email</div>\r\n        <span");

WriteLiteral(" class=\"field-validation-error\"");

WriteLiteral(" data-valmsg-for=\"Email\"");

WriteLiteral(" data-valmsg-replace=\"true\"");

WriteLiteral(" style=\"display:none\"");

WriteLiteral(">\r\n            Email is required.\r\n        </span>\r\n        <div");

WriteLiteral(" class=\"bcms-field-wrapper\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" class=\"input-validation-error bcms-field-text\"");

WriteLiteral(" data-val=\"true\"");

WriteLiteral(" data-val-required=\"Email is required.\"");

WriteLiteral(" id=\"Email\"");

WriteLiteral(" name=\"Email\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" value=\"\"");

WriteLiteral(">\r\n        </div>\r\n        <button");

WriteLiteral(" class=\"bcms-btn-primary\"");

WriteLiteral(" id=\"submitfacebookemail\"");

WriteLiteral(" onclick=\"javascript:FacebookLogin();\"");

WriteLiteral(">Submit</button>\r\n    </div>\r\n</div>\r\n<a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" id=\"auth-logoutlink\"");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">logout</a>\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    //$(document).ready(function () {\r\n    //    localStorage.setItem(\'GuserLo" +
"ggedIn\', \"No\");\r\n    //});\r\n\r\n    (function (d, s, id) {\r\n        var js, fjs = " +
"d.getElementsByTagName(s)[0];\r\n        if (d.getElementById(id)) { return; }\r\n  " +
"      js = d.createElement(s); js.id = id;\r\n        js.src = \"//connect.facebook" +
".net/en_US/sdk.js\";\r\n        fjs.parentNode.insertBefore(js, fjs);\r\n    }(docume" +
"nt, \'script\', \'facebook-jssdk\'));\r\n\r\n    window.fbAsyncInit = function () {\r\n   " +
"     FB.init({\r\n            appId: facebookId,//\'337763920005658\',\r\n            " +
"xfbml: true,\r\n            version: \'v2.10\'\r\n        });\r\n       // FB.AppEvents." +
"logPageView();\r\n\r\n        // listen for and handle auth.statusChange events\r\n   " +
"     //FB.Event.subscribe(\'auth.statusChange\', function (response) {\r\n        //" +
"    //if (response.authResponse) {\r\n        //    //    // user has auth\'d your " +
"app and is logged into Facebook\r\n\r\n        //    //    FB.api(\'/me\', function (m" +
"e) {\r\n        //    //        if (me.name) {\r\n        //    //            docume" +
"nt.getElementById(\'auth-displayname\').innerHTML = me.name;\r\n\r\n        //    //  " +
"      }\r\n        //    //    })\r\n        //    //    document.getElementById(\'au" +
"th-loggedout\').style.display = \'none\';\r\n        //    //    document.getElementB" +
"yId(\'auth-loggedin\').style.display = \'block\';\r\n        //    //} else {\r\n       " +
" //    //    // user has not auth\'d your app, or is not logged into Facebook\r\n  " +
"      //    //    document.getElementById(\'auth-loggedout\').style.display = \'blo" +
"ck\';\r\n        //    //    document.getElementById(\'auth-loggedin\').style.display" +
" = \'none\';\r\n        //    //}\r\n        //});\r\n        if (localStorage.getItem(\'" +
"FBloggedIn\') == \'yes\') {\r\n            setTimeout(function () { \r\n               " +
" $(\"#auth-logoutlink\").click();\r\n            }, 1000);\r\n        }\r\n        //$(\"" +
"#auth-loginlink\").click(function () { FB.login(); });\r\n        $(\"#auth-logoutli" +
"nk\").click(function () {\r\n            localStorage.setItem(\'FBloggedIn\', \'no\');\r" +
"\n            fbLogoutUser();\r\n        });\r\n\r\n       // FB.getLoginStatus(handleS" +
"essionResponse);\r\n    }\r\n\r\n    function fbLogoutUser() {\r\n        FB.login(funct" +
"ion (response1) {\r\n            if (response1 && response1.status === \'connected\'" +
") {\r\n                FB.logout(function (response) {\r\n                   // docu" +
"ment.location.reload();\r\n                });\r\n            }\r\n        });\r\n    }\r" +
"\n\r\n    function handleSessionResponse(response) {\r\n        //if we dont have a s" +
"ession (which means the user has been logged out, redirect the user)\r\n        if" +
" (!response.session) {\r\n            window.location.href = window.location.href;" +
"// \"/mysite/Login.aspx\";\r\n            return;\r\n        }\r\n\r\n        //if we do h" +
"ave a non-null response.session, call FB.logout(),\r\n        //the JS method will" +
" log the user out of Facebook and remove any authorization cookies\r\n        FB.l" +
"ogout(handleSessionResponse);\r\n    }\r\n\r\n    function onSignIn(googleUser) {\r\n   " +
"     var loginStatusGoogle = localStorage.getItem(\'GuserLoggedIn\');\r\n        if " +
"(loginStatusGoogle == \'yes\') {\r\n            localStorage.setItem(\'GuserLoggedIn\'" +
", \"No\");\r\n            document.location.href = \"https://www.google.com/accounts/" +
"Logout?continue=https://appengine.google.com/_ah/logout?continue=http://bettercm" +
"s.sandbox.mvc4.local.net/login\";\r\n        }\r\n        else {\r\n            var pro" +
"file = googleUser.getBasicProfile();\r\n            console.log(\'ID: \' + profile.g" +
"etId()); // Do not send to your backend! Use an ID token instead.\r\n            v" +
"ar str = profile.getId();\r\n            var data = { \'SocialId\': profile.getId()," +
" \'FirstName\': profile.getGivenName(), \'LastName\': profile.getFamilyName(), \'Emai" +
"l\': profile.getEmail(), \'Type\': \'google\' }\r\n            console.log(data);\r\n\r\n  " +
"          $.ajax({\r\n                url: \"/bcms-users/Authentication/SocialLogin" +
"?Socialid=\" + str,\r\n                type: \'POST\',\r\n                async: false," +
"\r\n                dataType: \'json\',\r\n                data: data,\r\n              " +
"  success: function (response) {\r\n                    localStorage.setItem(\'Guse" +
"rLoggedIn\', \"yes\");\r\n                    if (response == 0) {\r\n                 " +
"       $(\'#invalidusermessage\').html(\'This user is already registered.\').show();" +
"\r\n                    }\r\n                    else {\r\n                        win" +
"dow.location.href = window.location.href;// \"http://bettercms.sandbox.mvc4.local" +
".net/\";\r\n                    }\r\n                },\r\n                error: funct" +
"ion (jqXHR, textStatus, err) {\r\n                    //alert(textStatus);\r\n      " +
"          }\r\n            });\r\n\r\n        }\r\n    }\r\n\r\n    (function () {\r\n        " +
"document.getElementById(\'userName\').focus();\r\n    })();\r\n\r\n    function Login() " +
"{\r\n        FB.login(function (response) {\r\n            // handle the response\r\n " +
"           if (response.status === \'unknown\') {\r\n                location.reload" +
"();\r\n            }\r\n            else {\r\n                localStorage.setItem(\'FB" +
"loggedIn\', \'yes\');\r\n                var loginStatusFB = localStorage.getItem(\'FB" +
"loggedIn\');\r\n                localStorage.setItem(\"response\", response);\r\n      " +
"          if (loginStatusFB == \'yes\') {\r\n\r\n                    FB.api(\'/me\', \'ge" +
"t\', { fields: \'id,name,gender,email,first_name,last_name\' }, function (response)" +
" {\r\n                        var profile_id = response.id;\r\n                     " +
"   var email = response.email;\r\n                        var data = { \'SocialId\':" +
" response.id, \'FirstName\': response.first_name, \'LastName\': response.last_name, " +
"\'Email\': \'\', \'Type\': \'facebook\' }\r\n                        var IsRegistered = 0;" +
"\r\n                        $.ajax({\r\n                            url: \"/bcms-user" +
"s/Authentication/IsSocialIdExists?Socialid=\" + data.SocialId,\r\n                 " +
"           type: \'GET\',\r\n                            async: false,\r\n            " +
"                dataType: \'json\',\r\n                            success: function" +
" (response) {\r\n                                IsRegistered = response;\r\n       " +
"                     },\r\n                            error: function (jqXHR, tex" +
"tStatus, err) {\r\n                                // alert(textStatus);\r\n        " +
"                    }\r\n                        });\r\n\r\n                        if" +
" (typeof response.email == \'undefined\' && IsRegistered == 0) {\r\n                " +
"            $(\'#emailaddress\').show();\r\n                            $(\'#divBasic" +
"Login\').hide();\r\n                            postdata = data;\r\n                 " +
"       }\r\n                        else {\r\n                            RegisterFa" +
"cebookUser(data, email)\r\n                        }\r\n                    });\r\n   " +
"             }\r\n                // window.location = \"http://bettercms.sandbox.m" +
"vc4.local.net/\";\r\n            }\r\n\r\n        }, { scope: \'public_profile,email\' })" +
";\r\n    }\r\n\r\n    // // // google user\r\n    var auth21;\r\n\r\n    function handleClie" +
"ntLoad() {\r\n        // Loads the client library and the auth2 library together f" +
"or efficiency.\r\n        // Loading the auth2 library is optional here since `gap" +
"i.client.init` function will load\r\n        // it if not already loaded. Loading " +
"it upfront can save one network request.\r\n        gapi.load(\'client:auth2\', init" +
"Client);\r\n    }\r\n\r\n    function initClient() {\r\n        // Initialize the client" +
" with API key and People API, and initialize OAuth with an\r\n        // OAuth 2.0" +
" client ID and scopes (space delimited string) to request access.\r\n        gapi." +
"client.init({\r\n            apiKey: googleApiKey,\r\n            discoveryDocs: [\"h" +
"ttps://people.googleapis.com/$discovery/rest?version=v1\"],\r\n            clientId" +
": googleAppId,\r\n            scope: \'profile\'\r\n        }).then(function () {\r\n   " +
"         // Listen for sign-in state changes.\r\n            gapi.auth2.getAuthIns" +
"tance().isSignedIn.listen(updateSigninStatus);\r\n\r\n            // Handle the init" +
"ial sign-in state.\r\n            updateSigninStatus(gapi.auth2.getAuthInstance()." +
"isSignedIn.get());\r\n        });\r\n    }\r\n\r\n    function updateSigninStatus(isSign" +
"edIn) {\r\n        // When signin status changes, this function is called.\r\n      " +
"  // If the signin status is changed to signedIn, we make an API call.\r\n        " +
"if (isSignedIn) {\r\n            makeApiCall();\r\n        }\r\n    }\r\n\r\n    function " +
"handleSignInClick(event) {\r\n        // Ideally the button should only show up af" +
"ter gapi.client.init finishes, so that this\r\n        // handler won\'t be called " +
"before OAuth is initialized.\r\n        gapi.auth2.getAuthInstance().signIn();\r\n  " +
"  }\r\n\r\n\r\n    function makeApiCall() {\r\n        // Make an API call to the People" +
" API, and print the user\'s given name.\r\n\r\n        gapi.client.people.people.get(" +
"{\r\n            resourceName: \'people/me\',\r\n\r\n        }).then(function (response)" +
" {\r\n            var str = response.result.resourceName;\r\n            var profile" +
"Id = str.substring(7);\r\n            alert(\"login.cshtml3\");\r\n            localSt" +
"orage.setItem(\"response\", response);\r\n            alert(profileId);\r\n           " +
" $.ajax({\r\n                url: \"/bcms-users/Authentication/SocialLogin?Socialid" +
"=\" + profileId,\r\n                type: \'POST\',\r\n                async: false,\r\n " +
"               dataType: \'json\',\r\n                data: response,\r\n             " +
"   success: function (response) {\r\n                    status = true;\r\n         " +
"           //if (response === 1) status = true;\r\n                },\r\n           " +
"     error: function (jqXHR, textStatus, err) {\r\n                    //alert(tex" +
"tStatus);\r\n                }\r\n            });\r\n            localStorage.setItem(" +
"\'GuserLoggedIn\', \"yes\");\r\n            window.location.href = window.location.hre" +
"f; //\"http://bettercms.sandbox.mvc4.local.net/\";\r\n            //console.log(\'Hel" +
"lo, \' + response.result.names[0].givenName);\r\n        }, function (reason) {\r\n  " +
"          console.log(\'Error: \' + reason.result.error.message);\r\n        });\r\n  " +
"  }\r\n\r\n    function RegisterFacebookUser(data, email) {\r\n        data.Email = em" +
"ail;\r\n        $.ajax({\r\n            url: \"/bcms-users/Authentication/SocialLogin" +
"?Socialid=\" + data.SocialId,\r\n            type: \'POST\',\r\n            async: fals" +
"e,\r\n            dataType: \'json\',\r\n            data: data,\r\n            success:" +
" function (response) {\r\n                if (response == 0) {\r\n                  " +
"  // alert(\'This user is already registered\');\r\n                    $(\'#invalidu" +
"sermessage\').html(\'This user is already registered.\').show();\r\n                }" +
"\r\n                else {\r\n                    window.location.href = window.loca" +
"tion.href;\r\n                }\r\n                //status = true;\r\n               " +
" //if (response === 1) status = true;\r\n            },\r\n            error: functi" +
"on (jqXHR, textStatus, err) {\r\n                // alert(textStatus);\r\n          " +
"  }\r\n        });\r\n        // window.location = window.location;// \"http://better" +
"cms.sandbox.mvc4.local.net/\";\r\n    }\r\n\r\n    function FacebookLogin() {\r\n        " +
"var filter = /^([\\w-\\.]+)");

WriteLiteral("@((\\[[0-9]{1,3}\\.[0-9]{1,3}\\.[0-9]{1,3}\\.)|(([\\w-]+\\.)+))([a-zA-Z]{2,4}|[0-9]{1,3" +
"})(\\]?)$/;\r\n        if ($.trim($(\'#Email\').val()) == \'\' || !filter.test($.trim($" +
"(\'#Email\').val()))) {\r\n            $(\'span[data-valmsg-for=Email]\').show();\r\n   " +
"         return false;\r\n        }\r\n        else {\r\n            $(\'span[data-valm" +
"sg-for=Email]\').hide();\r\n            RegisterFacebookUser(postdata, $.trim($(\'#E" +
"mail\').val()));\r\n        }\r\n    }\r\n    var postdata = [];\r\n</script>\r\n\r\n<style>\r" +
"\n    #facebookIn {\r\n        background: #3b5998;\r\n        background: -webkit-li" +
"near-gradient(#3b5998, #3b5998);\r\n        background: linear-gradient(#3b5998, #" +
"3b5998);\r\n        color: #fff;\r\n        display: inline-block;\r\n        font: no" +
"rmal 700 24px/1 \"Calibri\", sans-serif;\r\n        text-align: center;\r\n        tex" +
"t-shadow: 1px 1px 0 #000;\r\n        margin-top: 8px;\r\n        height: 36px;\r\n    " +
"    width: 120px;\r\n        border: 0;\r\n    }\r\n\r\n    .socialbutton {\r\n        /*w" +
"idth: 100%;\r\n        text-align: center;*/\r\n        width: 125px;\r\n        margi" +
"n: 0 auto;\r\n    }\r\n\r\n    .googleIn {\r\n        background: #fff;\r\n        backgro" +
"und: -webkit-linear-gradient(#fff, #fff);\r\n        background: linear-gradient(#" +
"fff, #fff);\r\n        border: 1px solid #ccc;\r\n        border-radius: 5px;\r\n     " +
"   box-shadow: 0 1px 0 0 #444;\r\n        color: #f00;\r\n        display: inline-bl" +
"ock;\r\n        padding: 8px 20px;\r\n        font: normal 700 24px/1 \"Calibri\", san" +
"s-serif;\r\n        text-align: center;\r\n        text-shadow: none;\r\n    }\r\n\r\n    " +
"button {\r\n        padding: 0px;\r\n    }\r\n    \r\n</style>");

        }
    }
}
#pragma warning restore 1591
